#include "measure/isa.hpp"

#include <algorithm>
#include <atomic>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <random>
#include <thread>

#ifdef _WIN32
#define popen _popen
#define pclose _pclose
#endif

namespace sopt {
namespace {

namespace fs = std::filesystem;

const char* kSwizzle[4] = {"x", "y", "z", "w"};

std::string runCommand(const std::string& cmd, int& status) {
#ifdef _WIN32
  const std::string full = "\"" + cmd + "\"";  // cmd /c strips one pair of outer quotes
#else
  const std::string& full = cmd;
#endif
  std::string out;
  FILE* p = popen(full.c_str(), "r");
  if (!p) {
    status = -1;
    return out;
  }
  char buf[4096];
  size_t n;
  while ((n = std::fread(buf, 1, sizeof(buf), p)) > 0) out.append(buf, n);
  status = pclose(p);
  return out;
}

std::string quote(const std::string& s) { return "\"" + s + "\""; }

// Value of "key": <int> inside [begin, end) of s, or -1 (atoi skips the space).
int jsonInt(const std::string& s, size_t begin, size_t end, const char* key) {
  const std::string k = std::string("\"") + key + "\":";
  const size_t pos = s.find(k, begin);
  if (pos == std::string::npos || pos >= end) return -1;
  return std::atoi(s.c_str() + pos + k.size());
}

std::string firstLines(const std::string& s, int lines) {
  size_t pos = 0;
  for (int i = 0; i < lines && pos != std::string::npos; ++i) {
    pos = s.find('\n', pos);
    if (pos != std::string::npos) ++pos;
  }
  std::string out = s.substr(0, pos == std::string::npos ? s.size() : pos);
  while (!out.empty() && (out.back() == '\n' || out.back() == '\r')) out.pop_back();
  return out;
}

}  // namespace

std::string emitEffect(const Expr& e, const std::vector<InputDecl>& inputs) {
  const size_t numTex = (inputs.size() + 3) / 4;
  std::string s = "// Generated by sopt: ISA measurement of one candidate.\n";
  for (size_t t = 0; t < numTex; ++t) {
    const std::string n = std::to_string(t);
    s += "texture2D SoptTex" + n + " { Width = 1; Height = 1; Format = RGBA32F; };\n";
    s += "sampler2D SoptSamp" + n + " { Texture = SoptTex" + n + "; };\n";
  }
  s += "\nfloat sopt_region(";
  for (size_t i = 0; i < inputs.size(); ++i) s += (i ? ", float " : "float ") + inputs[i].name;
  s += ")\n{\n\treturn " + toString(e, inputs) + ";\n}\n\n";
  // Interpolated texcoord and tex2Dlod: no VALU outside the region (an integer
  // tex2Dfetch coordinate would cost two conversions).
  s += "void SoptVS(in uint id : SV_VertexID, out float4 position : SV_Position,"
       " out float2 texcoord : TEXCOORD)\n{\n"
       "\ttexcoord = float2(id == 2 ? 2.0 : 0.0, id == 1 ? 2.0 : 0.0);\n"
       "\tposition = float4(texcoord * float2(2.0, -2.0) + float2(-1.0, 1.0), 0.0, 1.0);\n}\n\n";
  s += "float4 SoptPS(float4 vpos : SV_Position, float2 texcoord : TEXCOORD) : SV_Target\n{\n";
  for (size_t t = 0; t < numTex; ++t)
    s += "\tconst float4 in" + std::to_string(t) + " = tex2Dlod(SoptSamp" + std::to_string(t) +
         ", float4(texcoord, 0.0, 0.0));\n";
  s += "\treturn sopt_region(";
  for (size_t i = 0; i < inputs.size(); ++i) {
    if (i) s += ", ";
    s += "in" + std::to_string(i / 4) + "." + kSwizzle[i % 4];
  }
  s += ");\n}\n\ntechnique Sopt\n{\n\tpass\n\t{\n\t\tVertexShader = SoptVS;\n"
       "\t\tPixelShader = SoptPS;\n\t}\n}\n";
  return s;
}

IsaCost parseFxstatJson(const std::string& json) {
  IsaCost c;
  const size_t stage = json.find("\"stage\": \"pixel\"");
  const size_t isa = stage == std::string::npos ? stage : json.find("\"isa\":", stage);
  if (isa == std::string::npos) {
    c.error = json.find('{') == std::string::npos ? firstLines(json, 3) : "no pixel ISA in fxstat output";
    if (c.error.empty()) c.error = "no output from fxstat";
    return c;
  }
  const size_t end = json.find('}', isa);
  auto get = [&](const char* key) { return jsonInt(json, isa, end, key); };
  c.valu = get("valu");
  c.trans = get("trans");
  c.salu = get("salu");
  c.vmem = get("vmem");
  c.vgprs = get("vgprs");
  c.cost = get("cost");
  c.ok = c.valu >= 0 && c.cost >= 0;
  if (!c.ok) c.error = "malformed fxstat isa object";
  return c;
}

std::vector<IsaCost> measureIsa(const std::vector<const Expr*>& exprs,
                                const std::vector<InputDecl>& inputs, const IsaConfig& cfg) {
  std::vector<IsaCost> out(exprs.size());
  if (exprs.empty()) return out;

  fs::path dir;
  std::error_code ec;
  if (!cfg.keepDir.empty()) {
    dir = cfg.keepDir;
  } else {
    std::random_device rd;
    dir = fs::temp_directory_path(ec) / ("sopt-isa-" + std::to_string(rd()));
  }
  fs::create_directories(dir, ec);
  if (ec) {
    for (auto& c : out) c.error = "cannot create " + dir.string() + ": " + ec.message();
    return out;
  }

  std::atomic<size_t> next{0};
  auto worker = [&] {
    for (size_t i = next++; i < exprs.size(); i = next++) {
      const fs::path file = dir / ("sopt_" + std::to_string(i) + ".fx");
      {
        std::ofstream f(file, std::ios::binary);
        f << emitEffect(*exprs[i], inputs);
        if (!f) {
          out[i].error = "cannot write " + file.string();
          continue;
        }
      }
      std::string cmd = quote(cfg.fxstat) + " --json --rga " + quote(cfg.rga);
      if (!cfg.asic.empty()) cmd += " --asic " + quote(cfg.asic);
      cmd += " " + quote(file.string()) + " 2>&1";
      int status = 0;
      const std::string text = runCommand(cmd, status);
      out[i] = parseFxstatJson(text);
      if (!out[i].ok && status != 0 && out[i].error.empty()) out[i].error = "fxstat failed";
    }
  };
  unsigned threads = cfg.threads ? cfg.threads : std::max(1u, std::thread::hardware_concurrency());
  threads = static_cast<unsigned>(std::min<size_t>(threads, exprs.size()));
  std::vector<std::thread> pool;
  for (unsigned t = 0; t < threads; ++t) pool.emplace_back(worker);
  for (auto& th : pool) th.join();

  if (cfg.keepDir.empty()) fs::remove_all(dir, ec);
  return out;
}

}  // namespace sopt
