#include "measure/isa.hpp"

#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <sstream>

#include "measure/tools.hpp"

namespace sopt {
namespace {

namespace fs = std::filesystem;

const char* kSwizzle[4] = {"x", "y", "z", "w"};

// Value of "key": <int> inside [begin, end) of s, or -1 (atoi skips the space).
int jsonInt(const std::string& s, size_t begin, size_t end, const char* key) {
  const std::string k = std::string("\"") + key + "\":";
  const size_t pos = s.find(k, begin);
  if (pos == std::string::npos || pos >= end) return -1;
  return std::atoi(s.c_str() + pos + k.size());
}

}  // namespace

std::string emitEffect(const Expr& e, const std::vector<InputDecl>& inputs) {
  // Every input component is one texture channel: slot k is texture k / 4, channel k % 4.
  const std::vector<uint32_t> slots = inputSlots(inputs);
  uint32_t numSlots = 0;
  for (const auto& d : inputs) numSlots += width(d.type);
  const size_t numTex = (numSlots + 3) / 4;
  auto typeName = [](Type t) {
    return width(t) == 1 ? std::string("float") : "float" + std::to_string(width(t));
  };
  const Type rt = e.nodes[e.root].type;
  std::string s = "// Generated by sopt: ISA measurement of one candidate.\n";
  for (size_t t = 0; t < numTex; ++t) {
    const std::string n = std::to_string(t);
    s += "texture2D SoptTex" + n + " { Width = 1; Height = 1; Format = RGBA32F; };\n";
    s += "sampler2D SoptSamp" + n + " { Texture = SoptTex" + n + "; };\n";
  }
  s += "\n" + typeName(rt) + " sopt_region(";
  for (size_t i = 0; i < inputs.size(); ++i)
    s += (i ? ", " : "") + typeName(inputs[i].type) + " " + inputs[i].name;
  if (needsPrecise(e))  // as sopt-fx writes it, so fxc cannot fold (v + c) - c
    s += ")\n{\n\tprecise " + typeName(rt) + " r = " + toString(e, inputs) + ";\n\treturn r;\n}\n\n";
  else
    s += ")\n{\n\treturn " + toString(e, inputs) + ";\n}\n\n";
  // Interpolated texcoord and tex2Dlod: no VALU outside the region (an integer
  // tex2Dfetch coordinate would cost two conversions).
  s += "void SoptVS(in uint id : SV_VertexID, out float4 position : SV_Position,"
       " out float2 texcoord : TEXCOORD)\n{\n"
       "\ttexcoord = float2(id == 2 ? 2.0 : 0.0, id == 1 ? 2.0 : 0.0);\n"
       "\tposition = float4(texcoord * float2(2.0, -2.0) + float2(-1.0, 1.0), 0.0, 1.0);\n}\n\n";
  s += "float4 SoptPS(float4 vpos : SV_Position, float2 texcoord : TEXCOORD) : SV_Target\n{\n";
  for (size_t t = 0; t < numTex; ++t)
    s += "\tconst float4 in" + std::to_string(t) + " = tex2Dlod(SoptSamp" + std::to_string(t) +
         ", float4(texcoord, 0.0, 0.0));\n";
  s += "\tconst " + typeName(rt) + " r = sopt_region(";
  for (size_t i = 0; i < inputs.size(); ++i) {
    if (i) s += ", ";
    const unsigned w = width(inputs[i].type);
    std::string comps;
    for (unsigned c = 0; c < w; ++c) {
      const uint32_t k = slots[i] + c;
      comps += (c ? ", " : "") + ("in" + std::to_string(k / 4) + "." + kSwizzle[k % 4]);
    }
    s += w == 1 ? comps : typeName(inputs[i].type) + "(" + comps + ")";
  }
  s += ");\n";
  static const char* widen[] = {"r", "r", "float4(r, 0.0, 0.0)", "float4(r, 0.0)", "r"};
  s += std::string("\treturn ") + widen[width(rt)] + ";\n}\n\n";
  s += "technique Sopt\n{\n\tpass\n\t{\n\t\tVertexShader = SoptVS;\n"
       "\t\tPixelShader = SoptPS;\n\t}\n}\n";
  return s;
}

std::string emitGlsl(const Expr& e, const std::vector<InputDecl>& inputs) {
  const std::vector<uint32_t> slots = inputSlots(inputs);
  uint32_t numSlots = 0;
  for (const auto& d : inputs) numSlots += width(d.type);
  const size_t numTex = (numSlots + 3) / 4;
  auto typeName = [](Type t) { return width(t) == 1 ? std::string("float") : "vec" + std::to_string(width(t)); };
  const Type rt = e.nodes[e.root].type;
  std::string s = "#version 450\n// Generated by sopt: ISA measurement of one candidate.\n"
                  "layout(location = 0) in vec2 soptUv;\nlayout(location = 0) out vec4 soptOut;\n";
  for (size_t t = 0; t < numTex; ++t)
    s += "layout(set = 0, binding = " + std::to_string(t) + ") uniform sampler2D soptTex" + std::to_string(t) + ";\n";
  s += "\n" + typeName(rt) + " sopt_region(";
  for (size_t i = 0; i < inputs.size(); ++i) s += (i ? ", " : "") + typeName(inputs[i].type) + " " + inputs[i].name;
  if (needsPrecise(e))
    s += ")\n{\n\tprecise " + typeName(rt) + " r = " + toGlsl(e, inputs) + ";\n\treturn r;\n}\n\n";
  else
    s += ")\n{\n\treturn " + toGlsl(e, inputs) + ";\n}\n\n";
  s += "void main()\n{\n";
  for (size_t t = 0; t < numTex; ++t)
    s += "\tvec4 in" + std::to_string(t) + " = textureLod(soptTex" + std::to_string(t) + ", soptUv, 0.0);\n";
  s += "\t" + typeName(rt) + " r = sopt_region(";
  for (size_t i = 0; i < inputs.size(); ++i) {
    if (i) s += ", ";
    const unsigned w = width(inputs[i].type);
    std::string comps;
    for (unsigned c = 0; c < w; ++c) {
      const uint32_t k = slots[i] + c;
      comps += (c ? ", " : "") + ("in" + std::to_string(k / 4) + "." + kSwizzle[k % 4]);
    }
    s += w == 1 ? comps : typeName(inputs[i].type) + "(" + comps + ")";
  }
  s += ");\n";
  static const char* widen[] = {"vec4(r)", "vec4(r)", "vec4(r, 0.0, 0.0)", "vec4(r, 0.0)", "r"};
  return s + "\tsoptOut = " + widen[width(rt)] + ";\n}\n";
}

IsaCost parseRgaIsa(const std::string& isa, const std::string& csv) {
  auto starts = [](const std::string& s, const char* p) { return s.rfind(p, 0) == 0; };
  IsaCost c;
  int total = 0;
  std::istringstream lines(isa);
  for (std::string line; std::getline(lines, line);) {
    if (line.empty() || line[0] != '\t') continue;
    std::istringstream words(line);
    std::string op;
    words >> op;
    if (op.empty() || starts(op, "//") || op.back() == ':') continue;
    ++total;
    if (starts(op, "image_") || starts(op, "buffer_") || starts(op, "global_") || starts(op, "tbuffer_") ||
        starts(op, "flat_"))
      ++c.vmem;
    else if (starts(op, "s_load") || starts(op, "s_buffer_load") || op == "s_branch" || starts(op, "s_cbranch"))
      continue;
    else if (starts(op, "s_")) {
      const bool bookkeeping = starts(op, "s_waitcnt") || op == "s_delay_alu" || op == "s_clause" || op == "s_nop" ||
                               op == "s_endpgm" || op == "s_sendmsg" || op == "s_inst_prefetch" ||
                               op == "s_set_inst_prefetch_distance";
      if (!bookkeeping) ++c.salu;
    } else if (starts(op, "v_") && !starts(op, "v_interp")) {
      ++c.valu;
      for (const char* t : {"v_exp_", "v_log_", "v_rcp_", "v_rsq_", "v_sqrt_", "v_sin_", "v_cos_"})
        if (starts(op, t)) {
          ++c.trans;
          break;
        }
    }
  }
  std::istringstream rows(csv);
  std::string header, values, f;
  std::getline(rows, header);
  std::getline(rows, values);
  std::vector<std::string> keys, vals;
  for (std::istringstream h(header); std::getline(h, f, ',');) keys.push_back(f);
  for (std::istringstream v(values); std::getline(v, f, ',');) vals.push_back(f);
  for (size_t i = 0; i < keys.size() && i < vals.size(); ++i) {
    if (keys[i] == "USED_VGPRs") c.vgprs = std::atoi(vals[i].c_str());
    if (keys[i] == "USED_SGPRs") c.sgprs = std::atoi(vals[i].c_str());
  }
  c.cost = c.valu + 3 * c.trans;
  c.ok = total > 0;
  if (!c.ok) c.error = "RGA produced an empty ISA listing";
  return c;
}

IsaCost parseFxstatJson(const std::string& json) {
  IsaCost c;
  const size_t stage = json.find("\"stage\": \"pixel\"");
  const size_t isa = stage == std::string::npos ? stage : json.find("\"isa\":", stage);
  if (isa == std::string::npos) {
    c.error = json.find('{') == std::string::npos ? firstLines(json, 3) : "no pixel ISA in fxstat output";
    if (c.error.empty()) c.error = "no output from fxstat";
    return c;
  }
  const size_t end = json.find('}', isa);
  auto get = [&](const char* key) { return jsonInt(json, isa, end, key); };
  c.valu = get("valu");
  c.trans = get("trans");
  c.salu = get("salu");
  c.vmem = get("vmem");
  c.vgprs = get("vgprs");
  c.sgprs = get("sgprs");
  c.cost = get("cost");
  c.ok = c.valu >= 0 && c.cost >= 0;
  if (!c.ok) c.error = "malformed fxstat isa object";
  return c;
}

std::vector<IsaCost> measureIsa(const std::vector<const Expr*>& exprsIn,
                                const std::vector<InputDecl>& inputsIn, const IsaConfig& cfg) {
  const Specialized sp = specializeForCompiler(exprsIn, inputsIn);
  const auto& exprs = sp.exprs;
  const auto& inputs = sp.inputs;
  std::vector<IsaCost> out(exprs.size());
  if (exprs.empty()) return out;

  std::string err;
  const fs::path dir = makeWorkDir(cfg.keepDir, "sopt-isa-", err);
  if (dir.empty()) {
    for (auto& c : out) c.error = err;
    return out;
  }

  if (cfg.glsl) {
    parallelFor(exprs.size(), cfg.threads, [&](size_t i) {
      const fs::path sub = dir / ("sopt_" + std::to_string(i));
      std::error_code ec;
      fs::create_directories(sub, ec);
      const fs::path file = sub / "sopt.frag";
      {
        std::ofstream f(file, std::ios::binary);
        f << emitGlsl(*exprs[i], inputs);
        if (!f) {
          out[i].error = "cannot write " + file.string();
          return;
        }
      }
      const std::string cmd = quote(cfg.rga) + " -s vk-offline -c " + (cfg.asic.empty() ? "gfx1100" : cfg.asic) +
                              " --frag " + quote(file.string()) + " --isa " + quote((sub / "out.isa").string()) +
                              " -a " + quote((sub / "out.csv").string()) + " 2>&1";
      int status = 0;
      const std::string log = runCommand(cmd, status);
      // RGA prefixes the output names with the ASIC and suffixes the stage: search for them.
      std::string isaText, csvText;
      for (const auto& entry : fs::directory_iterator(sub, ec)) {
        std::ifstream f(entry.path(), std::ios::binary);
        std::stringstream ss;
        ss << f.rdbuf();
        if (entry.path().extension() == ".isa") isaText = ss.str();
        if (entry.path().extension() == ".csv") csvText = ss.str();
      }
      if (isaText.empty()) {
        out[i].error = "RGA failed: " + firstLines(log, 3);
        return;
      }
      out[i] = parseRgaIsa(isaText, csvText);
    });
    std::error_code ec;
    if (cfg.keepDir.empty()) fs::remove_all(dir, ec);
    return out;
  }

  parallelFor(exprs.size(), cfg.threads, [&](size_t i) {
    const fs::path file = dir / ("sopt_" + std::to_string(i) + ".fx");
    {
      std::ofstream f(file, std::ios::binary);
      f << emitEffect(*exprs[i], inputs);
      if (!f) {
        out[i].error = "cannot write " + file.string();
        return;
      }
    }
    std::string cmd = quote(cfg.fxstat) + " --json --rga " + quote(cfg.rga);
    if (!cfg.asic.empty()) cmd += " --asic " + quote(cfg.asic);
    cmd += " " + quote(file.string()) + " 2>&1";
    int status = 0;
    const std::string text = runCommand(cmd, status);
    out[i] = parseFxstatJson(text);
    if (!out[i].ok && status != 0 && out[i].error.empty()) out[i].error = "fxstat failed";
  });

  std::error_code ec;
  if (cfg.keepDir.empty()) fs::remove_all(dir, ec);
  return out;
}

}  // namespace sopt
