#!/usr/bin/env python3
"""Share of Steam users per SweetOpt cost model, from the Steam Hardware & Software Survey's video card page.

Owner (2026-10-09): easy mode weighs a variant that is faster on some GPU families and slower on others by how
many people own each family; the survey is read when a version is released (workflow steam-survey.yml), not by
SweetOpt itself. Usage: steam_share.py <videocard.html> <out.txt>

Cards are mapped to cost models with the web page's MODEL_RULES (tools/site/build.py) plus NEAREST rules for
families without a model of their own (marked "nearest" in the file). Unmapped cards count as "other".
"""
import html
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build import MODEL_RULES, clean_name  # noqa: E402

# Families without a measured model: the closest one (by architecture; RX 590 = GCN 4 measured like GCN 5 on
# simple ops, RDNA 1 lacks RDNA 2's extras but issues alike, Kepler is closest to Maxwell, Arc is Xe like Gen12).
NEAREST = [
    (r"RX 5[5-7]\d\d", "amd-rdna2"),
    (r"RX (4[6-9]\d|5[5-9]\d)\b|R9 |R7 |RX 640", "amd-gcn5"),
    (r"GTX (6[5-9]\d|7[5-9]\d|TITAN)\b|GT 7\d\d", "nvidia-maxwell"),
    (r"\bArc\b", "intel-gen12"),
    (r"Radeon [78][4-9]0M", "rdna3"),
    (r"Radeon 6[0-9]0M", "amd-rdna2"),
]


def model_of(card):
    for pattern, model in MODEL_RULES:
        if re.search(pattern, card):
            return model, False
    for pattern, model in NEAREST:
        if re.search(pattern, card):
            return model, True
    return None, False


def parse(text):
    """(month, [(card, percent)]) from the page: the 'ALL VIDEO CARDS' block, latest month's column."""
    month = ""
    m = re.search(r"Steam Hardware &amp; Software Survey:\s*([A-Za-z]+ \d{4})", text) or re.search(
        r"Steam Hardware & Software Survey:\s*([A-Za-z]+ \d{4})", text)
    if m:
        month = m.group(1)
    start = text.find("ALL VIDEO CARDS")
    if start < 0:
        raise SystemExit("no 'ALL VIDEO CARDS' block on the page")
    block = text[start:]
    # The next block (the DirectX tables) starts with another heading in capitals.
    nxt = re.search(r"DIRECTX 1[0-2] GPUS|DIRECTX 9", block[20:])
    if nxt:
        block = block[: nxt.start() + 20]
    cards = []
    for row in re.finditer(r'class="substats_col_left"[^>]*>(.*?)</div>(.*?)(?=class="substats_col_left"|$)', block, re.S):
        name = html.unescape(re.sub(r"<[^>]+>", "", row.group(1))).strip()
        # The month columns, then the latest month and its change (signed): the share is the next to last value.
        pcts = re.findall(r"([-+]?\d+(?:\.\d+)?)%", re.sub(r"<[^>]+>", " ", row.group(2)))
        if not name or len(pcts) < 2:
            continue
        pct = float(pcts[-2])
        cards.append((name, pct))
    if not cards:
        raise SystemExit("no card rows found (page layout changed?)")
    if any(p < 0 for _, p in cards):
        raise SystemExit("negative shares: the columns were misread (page layout changed?)")
    return month, cards


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    text = open(sys.argv[1], encoding="utf-8", errors="replace").read()
    month, cards = parse(text)
    share, lines = {}, []
    for name, pct in cards:
        model, near = model_of(clean_name(name))
        key = model or "other"
        share[key] = share.get(key, 0.0) + pct
        lines.append("# %-48s %6.2f  %s%s" % (name, pct, key, " (nearest)" if near else ""))
    total = sum(share.values())
    out = [
        "# Share of Steam users per SweetOpt cost model, in percent (Steam Hardware & Software Survey%s, all video"
        % (", " + month if month else ""),
        "# cards). Generated by tools/site/steam_share.py (workflow steam-survey.yml); easy mode weighs a variant that is",
        "# faster on some families and slower on others by these shares. Cards without a model are \"other\".",
        "# survey: %s" % (month or "unknown"),
    ]
    for key in sorted(share, key=lambda k: (k == "other", -share[k])):
        out.append("%s %.2f" % (key, share[key]))
    out.append("# total %.2f" % total)
    out.append("#")
    out.append("# Cards (name, percent, model):")
    out += lines
    with open(sys.argv[2], "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    print("\n".join(out[:4 + len(share) + 1]))


if __name__ == "__main__":
    main()
