// Generated by tools/windows/gen_expected.py from docs/opbench: do not edit, rerun it when reports are added.
// What cards of each family (cost model) measure in the OpBench throughput tests: the median cost over the
// family's cards (one report each). Only hardware, no names of the people who ran them.
#pragma once

namespace expected {

struct Family {
  const char* model;
  const char* label;  // architectures
  int cards;
  const char* costs;  // "test cost test cost ..."
};

inline const Family kFamilies[] = {
    {"amd-gcn5", "GCN 5 (Vega)", 3,
     "aAdd 6.8 aAdd1 251.6 aAnd 6.8 aAnd1 251.5 aCmpXchg 10.9 aCmpXchg1 251.6 aMax 6.8 aMax1 251.6 "
     "aMin 6.8 aMin1 251.5 aOr 6.8 aOr1 251.6 aXchg 6.8 aXchg1 251.7 aXor 6.8 aXor1 251.6 abs -0.0 "
     "acos 33.0 add 2.1 add16 1.5 arraybase 9.3 arrayread 163.2 arraywrite 267.8 asin 35.6 atan 45.9 "
     "atan2 52.4 atombase 8.2 barrier 0.0 bitcast 0.0 bitor 2.3 bitrev 2.1 branchdiv 83.8 branchuni 44.5 "
     "ceil 2.2 clamp 4.2 constarray 117.3 contract 4.2 cos 10.6 cosh 21.2 cross 12.4 cvt1 0.2 det3 13.5 "
     "distance 26.9 div 7.2 divxy 10.0 dot2 0.2 dot3 0.7 dot4 0.9 exp 10.7 exp2 8.5 exp2_16 8.7 "
     "f16round 3.2 faceforward 17.0 fbh 8.3 fbl 2.1 floor 2.0 flooradd 12.4 fma+cvt -0.1 fma+fma -0.1 "
     "fma+half 1.8 fma+int 1.6 fma+minmax -0.0 fma+rcp -3.2 fma1 2.1 fmod 10.3 frac 2.2 fracadd 11.9 "
     "frexp 20.7 ftoitof 9.8 ftou 2.1 groupbarrier 0.0 gsbase 16.0 gsbase32 16.8 gsread 1.9 gsread32 104.5 "
     "gswrite 3.9 gswrite32 112.7 gswriteread 8.5 half1 -2.8 iadd 2.1 iand 2.1 icmpsel 6.2 idiv 57.1 "
     "imin 2.1 imod 44.6 imul 0.7 int -1.6 irot 2.1 ishr 4.2 isinf 8.5 isnan 6.3 itof 2.1 ixmul 6.5 "
     "ldexp 10.5 length 20.7 lerp 6.3 log 8.8 log10 8.8 log2 8.5 mad 4.0 mad16 -2.9 mad2 4.2 mad2v 4.2 "
     "mad3v 8.7 mad4v 12.8 matmul4 25.7 max 2.2 max3 1.1 membarrier -0.0 min 2.2 minmax 2.1 minmax1 0.2 "
     "modf 6.3 mul -1.5 mul16 1.5 neg -0.0 negabs -0.0 normalize 11.4 omod0.125 2.4 omod0.25 2.2 omod2 0.0 "
     "omod3 2.2 omod4 -0.0 omod8 2.4 omodhalf -0.0 popc -0.0 pow 18.9 radians 0.2 rcp 8.5 rcp1 6.5 "
     "rcp16 8.7 rcpmax 10.4 reflect 12.4 refract 39.6 round 2.2 roundadd 5.5 rsqrt 8.5 satmad -1.0 "
     "saturate -1.4 select 6.3 selectboth 83.6 sign 10.5 signbits 4.3 signclamp 4.3 signmad 4.4 "
     "signsat 6.3 signsel 8.5 signsel2 4.1 sin 10.6 sincos 18.8 sinh 21.2 smoothstep 10.9 sqrt 8.5 "
     "sqrt16 8.6 step 4.2 sub 2.1 tan 32.8 tanh 33.5 trunc 2.2 udiv 44.7 umod 34.2 unitf 6.3 utof 2.1 "},
    {"amd-rdna2", "RDNA 2", 5,
     "aAdd 3.9 aAdd1 344.3 aAnd 4.1 aAnd1 344.0 aCmpXchg 6.8 aCmpXchg1 344.2 aMax 4.1 aMax1 344.0 aMin 4.1 "
     "aMin1 344.2 aOr 4.1 aOr1 344.1 aXchg 4.1 aXchg1 344.0 aXor 4.1 aXor1 344.1 abs -0.0 acos 32.5 "
     "add 3.0 add16 1.5 arraybase 13.2 arrayread 297.2 arraywrite 377.1 asin 35.3 atan 52.3 atan2 60.4 "
     "atombase 8.0 barrier 3.1 bitcast 0.2 bitor 3.0 bitrev 2.8 branchdiv 86.1 branchuni 42.1 ceil 3.0 "
     "clamp 5.8 constarray 0.3 contract 4.0 cos 7.9 cosh 19.0 cross 11.5 cvt1 2.0 det3 16.5 distance 24.5 "
     "div 7.8 divxy 6.3 dot2 1.9 dot3 2.0 dot4 2.2 exp 7.9 exp2 7.6 exp2_16 10.2 f16round -0.1 "
     "faceforward 16.4 fbh 11.8 fbl 2.8 floor 3.0 flooradd 16.6 fma+cvt -1.6 fma+fma 0.1 fma+half 0.8 "
     "fma+int 0.0 fma+minmax -1.6 fma+rcp -5.6 fma1 3.0 fmod 14.3 frac 3.0 fracadd 16.7 frexp 24.4 "
     "ftoitof 12.7 ftou 3.0 groupbarrier 4.5 gsbase 15.6 gsbase32 15.7 gsread 4.1 gsread32 138.4 "
     "gswrite 7.3 gswrite32 160.8 gswriteread 11.4 half1 -2.4 iadd 2.9 iand 2.9 icmpsel 8.4 idiv 76.9 "
     "imin 2.8 imod 60.0 imul 11.4 int -0.0 irot 2.8 ishr 2.9 isinf 7.6 isnan 4.8 itof 2.8 ixmul 10.7 "
     "ldexp 5.8 length 14.6 lerp 6.9 log 7.7 log10 7.3 log2 7.7 mad 4.0 mad16 -2.5 mad2 4.0 mad2v 5.9 "
     "mad3v 11.7 mad4v 17.9 matmul4 36.0 max 3.0 max3 1.1 membarrier 4.5 min 3.0 minmax 2.9 minmax1 2.0 "
     "modf 8.6 mul -1.0 mul16 1.5 neg -0.0 negabs 0.0 normalize 8.1 omod0.125 1.1 omod0.25 1.1 omod2 -0.0 "
     "omod3 1.1 omod4 -0.0 omod8 1.1 omodhalf 0.0 popc 0.0 pow 19.3 radians 2.0 rcp 7.8 rcp1 7.3 "
     "rcp16 10.2 rcpmax 7.8 reflect 11.9 refract 39.9 round 3.0 roundadd 7.7 rsqrt 7.7 satmad -0.0 "
     "saturate 0.2 select 5.0 selectboth 85.8 sign 13.8 signbits 5.9 signclamp 5.9 signmad 5.8 signsat 7.8 "
     "signsel 10.8 signsel2 4.9 sin 7.9 sincos 16.5 sinh 19.0 smoothstep 13.8 sqrt 7.6 sqrt16 10.1 "
     "step 4.9 sub 3.0 tan 32.0 tanh 30.0 trunc 3.0 udiv 60.0 umod 46.0 unitf 8.7 utof 2.8 "},
    {"amd-rdna4", "RDNA 4", 1,
     "aAdd 15.5 aAdd1 887.1 aAnd 14.8 aAnd1 883.9 aCmpXchg 27.4 aCmpXchg1 877.3 aMax 15.1 aMax1 882.8 "
     "aMin 14.9 aMin1 880.6 aOr 15.1 aOr1 884.2 aXchg 15.0 aXchg1 877.3 aXor 15.4 aXor1 887.0 abs 0.0 "
     "acos 56.0 acos1 40.9 acos4 60.2 add 3.8 add16 3.6 arraybase 30.0 arrayread 481.8 arraywrite 806.4 "
     "asin 59.8 atan 82.2 atan2 99.0 atan2q 39.2 atan4 23.0 atan5a 53.8 atombase 11.3 barrier 0.5 "
     "bitcast -0.0 bitor 7.7 bitrev 7.2 branchdiv 252.3 branchuni 249.9 ceil 7.7 clamp 7.6 constarray 2.6 "
     "contract 3.9 cos 25.8 cosh 56.8 cross 25.4 cvt1 7.7 det3 32.5 distance 57.1 div 25.3 divxy 22.5 "
     "dot2 8.6 dot3 14.5 dot4 24.5 exp 25.8 exp2 25.4 exp2_16 25.2 exp2ceil 57.6 exp2floor 60.4 "
     "f16round 3.3 faceforward 43.9 fbh 26.2 fbl 7.4 floor 7.8 flooradd 23.0 fma+cvt -4.2 fma+fma 0.0 "
     "fma+half 0.4 fma+int -1.7 fma+minmax -1.7 fma+rcp -14.3 fma1 3.7 fmod 30.0 frac 7.8 fracadd 22.2 "
     "frexp 55.5 ftoitof 25.5 ftou 7.3 groupbarrier 1.1 gsbase 30.9 gsbase32 30.6 gsread 8.3 "
     "gsread32 350.5 gswrite 25.3 gswrite32 418.1 gswriteread 32.3 half1 -0.4 iadd 7.3 iand 7.1 "
     "icmpsel 18.7 idiv 209.4 imin 7.1 imod 147.1 imul 28.9 int 3.3 irot 7.4 ishr 7.3 isinf 18.2 "
     "isnan 11.5 itof 7.2 ixmul 32.0 ldexp 27.5 length 42.1 lerp 9.5 log 25.6 log10 25.8 log2 25.5 "
     "log2_16 25.1 mad 4.0 mad16 -0.4 mad16v3 -1.0 mad2 3.9 mad2v 4.0 mad3v 8.0 mad4v 11.8 matmul4 69.4 "
     "max 4.6 max16 3.6 max3 3.2 membarrier 0.7 min 4.6 minmax 3.2 minmax1 3.2 mix16 6.8 modf 15.1 mul 0.2 "
     "mul16 0.3 neg -0.0 negabs -0.0 normalize 34.1 omod0.125 2.9 omod0.25 2.9 omod2 0.0 omod3 2.9 "
     "omod4 0.0 omod8 2.9 omodhalf 0.0 popc -0.0 pow 57.0 pow2ceil 14.9 pow2floor 7.7 radians 3.3 rcp 25.3 "
     "rcp1 24.9 rcp16 25.2 rcpmax 28.4 rcpnr0 7.7 rcpnr1 15.4 reflect 27.8 refract 73.0 round 7.7 "
     "roundadd 10.4 rsqrt 25.2 rsqrtnr0 15.0 rsqrtnr1 29.5 satmad -0.0 saturate 1.2 select 11.9 "
     "selectboth 248.8 sign 38.0 signbits 14.1 signclamp 10.8 signmad 7.1 signsat 10.1 signsel 23.0 "
     "signsel2 10.9 sin 25.6 sincos 53.1 sinh 67.1 smoothstep 18.5 sqrt 25.4 sqrt16 25.1 sqrtnr0 14.9 "
     "step 12.1 sub 4.5 tan 87.3 tanh 88.0 trunc 7.8 udiv 169.7 umod 112.7 unitf 19.0 utof 7.1 "},
    {"amd-terascale2", "TeraScale 2", 1,
     "abs 2.6 add 2.6 ceil 2.6 clamp 5.2 contract 2.6 cos 13.5 div 10.7 divxy 8.2 exp 10.7 exp2 10.6 "
     "floor 2.6 frac 2.6 lerp 5.2 log 10.7 log2 10.6 mad 4.0 mad2 2.6 max 2.6 max3 2.6 min 2.6 minmax 2.6 "
     "mul 2.6 neg 0.0 negabs 2.6 omod2 0.2 omod3 0.2 omodhalf 0.2 pow 23.9 rcp 10.6 rcpmax 10.7 round 2.6 "
     "rsqrt 10.6 satmad 0.0 saturate 0.2 select 5.2 sign 10.9 sin 16.1 sqrt 10.6 step 2.6 sub 2.6 "},
    {"intel-gen12", "Xe-LP", 1,
     "aAdd 18.0 aAdd1 47.6 aAnd 18.0 aAnd1 454.1 aCmpXchg 31.9 aCmpXchg1 2278.0 aMax 18.0 aMax1 454.7 "
     "aMin 18.0 aMin1 454.7 aOr 18.0 aOr1 456.0 aXchg 18.1 aXchg1 454.7 aXor 17.9 aXor1 454.8 abs 0.0 "
     "acos 41.1 acos1 30.9 acos4 45.3 add 3.9 add16 1.8 arraybase 23.0 arrayread 62.1 arraywrite 16061.0 "
     "asin 44.9 atan 64.7 atan2 76.3 atan2q 31.6 atan4 22.7 atan5a 39.7 atombase 13.2 barrier 30.9 "
     "bitcast 0.0 bitor 3.7 bitrev 3.9 branchdiv 112.6 branchuni 54.4 ceil 3.9 clamp 7.7 constarray 90.1 "
     "contract 4.0 cos 10.6 cosh 25.5 cross 25.0 cvt1 3.5 det3 33.0 distance 40.0 div 10.6 divxy 7.1 "
     "dot2 8.1 dot3 19.0 dot4 24.6 exp 10.7 exp2 10.6 exp2_16 12.6 exp2ceil 25.3 exp2floor 25.3 "
     "f16round 4.3 faceforward 27.3 fbh 13.0 fbl 4.2 floor 3.7 flooradd 20.0 fma+cvt -1.8 fma+fma -0.0 "
     "fma+half 0.9 fma+int -1.9 fma+minmax -1.9 fma+rcp -7.1 fma1 4.0 fmod 15.1 frac 3.7 fracadd 21.1 "
     "frexp 40.1 ftoitof 14.9 ftou 4.1 groupbarrier 2.2 gsbase 27.0 gsbase32 26.8 gsread 0.1 gsread32 0.9 "
     "gswrite 11.8 gswrite32 13.3 gswriteread 16.8 half1 -1.9 iadd 4.0 iand 4.0 icmpsel 7.9 idiv 137.1 "
     "imin 4.2 imod 137.0 imul 7.9 int 3.7 irot 11.9 ishr 7.8 isinf 11.3 isnan 7.6 itof 4.0 ixmul 7.6 "
     "ldexp 6.7 length 28.1 lerp 7.6 log 10.6 log10 10.6 log2 10.6 log2_16 12.6 mad 4.0 mad16 -1.9 "
     "mad16v3 -6.1 mad2 4.0 mad2v 4.1 mad3v 8.0 mad4v 12.6 matmul4 68.9 max 3.9 max16 1.9 max3 3.7 "
     "membarrier 16.5 min 3.9 minmax 3.7 minmax1 3.7 mix16 4.0 modf 7.4 mul 0.0 mul16 0.2 neg -0.0 "
     "negabs 0.0 normalize 22.1 omod0.125 0.3 omod0.25 0.3 omod2 0.5 omod3 0.3 omod4 0.3 omod8 0.7 "
     "omodhalf 0.4 popc 4.3 pow 25.3 pow2ceil 7.5 pow2floor 3.8 radians 0.1 rcp 10.6 rcp1 10.6 rcp16 12.6 "
     "rcpmax 10.8 rcpnr0 3.7 rcpnr1 14.2 reflect 29.6 refract 65.7 round 3.8 roundadd 7.4 rsqrt 10.7 "
     "rsqrtnr0 7.4 rsqrtnr1 26.3 satmad 0.0 saturate 0.2 select 7.8 selectboth 112.6 sign 17.8 "
     "signbits 7.0 signclamp 10.8 signmad 7.4 signsat 11.0 signsel 13.9 signsel2 3.1 sin 10.6 sincos 20.6 "
     "sinh 25.5 smoothstep 19.1 sqrt 10.6 sqrt16 12.6 sqrtnr0 7.4 step 7.5 sub 4.2 tan 39.8 tanh 40.0 "
     "trunc 3.8 udiv 139.5 umod 138.6 unitf 11.2 utof 4.0 "},
    {"intel-gen7.5", "Gen7.5", 1,
     "aAdd 45.5 aAdd1 200.1 aAnd 47.6 aAnd1 239.8 aCmpXchg 67.5 aCmpXchg1 240.0 aMax 45.5 aMax1 242.6 "
     "aMin 45.7 aMin1 239.7 aOr 46.0 aOr1 241.8 aXchg 49.3 aXchg1 237.5 aXor 45.7 aXor1 240.0 abs -0.0 "
     "acos 39.5 add 3.6 add16 3.6 arraybase 30.7 arrayread 37.9 arraywrite 400.3 asin 43.9 atan 62.5 "
     "atan2 74.0 atombase 27.1 barrier 27.2 bitcast -0.0 bitor 3.8 bitrev 6.5 branchdiv 64.4 "
     "branchuni 48.0 ceil 3.8 clamp 11.7 constarray 33.6 contract 3.7 cos 3.4 cosh 13.5 cross 19.4 "
     "cvt1 3.7 det3 29.8 distance 38.5 div 3.5 divxy 7.1 dot2 7.2 dot3 10.2 dot4 15.2 exp 6.8 exp2 3.4 "
     "exp2_16 3.4 f16round 14.4 faceforward 25.0 fbh 26.5 fbl 6.6 floor 3.8 flooradd 17.0 fma+cvt -1.3 "
     "fma+fma 0.0 fma+half 0.0 fma+int -5.0 fma+minmax -5.2 fma+rcp -1.4 fma1 5.9 fmod 18.8 frac 3.8 "
     "fracadd 16.9 frexp 59.1 ftoitof 17.4 ftou 6.1 groupbarrier 3.7 gsbase 38.9 gsbase32 39.2 gsread 5.4 "
     "gsread32 206.7 gswrite 12.9 gswrite32 225.6 gswriteread 21.0 half1 0.0 iadd 6.4 iand 6.5 "
     "icmpsel 19.7 idiv 103.4 imin 6.5 imod 105.7 imul 23.0 int 10.2 irot 19.6 ishr 13.1 isinf 16.6 "
     "isnan 7.3 itof 6.6 ixmul 26.7 ldexp 7.3 length 29.7 lerp 6.9 log 3.5 log10 3.5 log2 3.4 mad 4.0 "
     "mad16 -0.0 mad2 3.7 mad2v 4.5 mad3v 9.2 mad4v 13.5 matmul4 59.3 max 6.7 max3 5.0 membarrier 50.6 "
     "min 6.7 minmax 5.0 minmax1 9.9 modf 11.3 mul 0.7 mul16 0.7 neg -0.0 negabs 0.0 normalize 27.4 "
     "omod0.125 4.4 omod0.25 4.3 omod2 4.2 omod3 4.3 omod4 4.4 omod8 4.3 omodhalf 4.4 popc 6.6 pow 11.5 "
     "radians 0.7 rcp 3.4 rcp1 3.4 rcp16 3.4 rcpmax 7.7 reflect 25.8 refract 61.2 round 3.7 roundadd 6.9 "
     "rsqrt 3.4 satmad 0.0 saturate 0.5 select 7.3 selectboth 54.5 sign 14.7 signbits 7.5 signclamp 12.4 "
     "signmad 7.7 signsat 10.0 signsel 19.1 signsel2 3.6 sin 3.4 sincos 9.6 sinh 13.5 smoothstep 17.6 "
     "sqrt 3.4 sqrt16 3.4 step 7.3 sub 3.6 tan 22.7 tanh 26.5 trunc 3.7 udiv 108.3 umod 105.6 unitf 15.6 "
     "utof 6.6 "},
    {"intel-gen9", "Gen9 / Gen9.5", 3,
     "aAdd 26.5 aAdd1 69.8 aAnd 27.9 aAnd1 249.4 aCmpXchg 39.6 aCmpXchg1 233.4 aMax 27.2 aMax1 255.4 "
     "aMin 26.0 aMin1 242.6 aOr 27.2 aOr1 245.7 aXchg 26.7 aXchg1 245.6 aXor 26.3 aXor1 251.7 abs 0.0 "
     "acos 46.2 acos1 30.8 acos4 46.2 add 3.9 add16 2.8 arraybase 22.5 arrayread 25.9 arraywrite 116.0 "
     "asin 52.6 atan 63.3 atan2 82.5 atan2q 34.9 atan4 22.0 atan5a 39.6 atombase 15.2 barrier 35.6 "
     "bitcast 0.0 bitor 3.8 bitrev 4.7 branchdiv 112.9 branchuni 54.5 ceil 4.0 clamp 7.6 constarray 97.1 "
     "contract 4.0 cos 12.2 cosh 30.4 cross 22.1 cvt1 3.9 det3 31.9 distance 41.6 div 12.2 divxy 11.5 "
     "dot2 7.5 dot3 14.3 dot4 18.4 exp 14.7 exp2 12.1 exp2_16 12.6 exp2ceil 28.0 exp2floor 27.9 "
     "f16round 16.6 faceforward 22.6 fbh 13.0 fbl 4.8 floor 4.0 flooradd 19.3 fma+cvt -1.9 fma+fma -0.1 "
     "fma+half 0.9 fma+int -2.1 fma+minmax -1.9 fma+rcp -6.5 fma1 4.1 fmod 15.3 frac 4.0 fracadd 19.1 "
     "frexp 36.9 ftoitof 14.8 ftou 3.7 groupbarrier 5.4 gsbase 26.2 gsbase32 26.3 gsread 1.3 gsread32 35.3 "
     "gswrite 11.4 gswrite32 36.7 gswriteread 28.5 half1 -1.8 iadd 3.6 iand 3.6 icmpsel 7.3 idiv 136.8 "
     "imin 3.6 imod 137.2 imul 7.5 int 4.0 irot 17.9 ishr 7.3 isinf 11.4 isnan 7.1 itof 3.6 ixmul 7.5 "
     "ldexp 14.5 length 32.8 lerp 7.6 log 12.3 log10 12.3 log2 12.1 log2_16 12.8 mad 4.0 mad16 -1.8 "
     "mad16v3 -5.2 mad2 3.9 mad2v 4.4 mad3v 8.6 mad4v 12.7 matmul4 61.7 max 4.0 max16 2.6 max3 3.6 "
     "membarrier 72.3 min 3.9 minmax 3.6 minmax1 4.0 mix16 4.0 modf 7.6 mul 0.1 mul16 0.7 neg -0.0 "
     "negabs -0.0 normalize 28.3 omod0.125 0.7 omod0.25 0.4 omod2 0.7 omod3 0.5 omod4 0.4 omod8 0.4 "
     "omodhalf 0.4 popc 5.0 pow 27.4 pow2ceil 7.6 pow2floor 4.0 radians 0.1 rcp 12.1 rcp1 11.9 rcp16 12.7 "
     "rcpmax 15.2 rcpnr0 4.0 rcpnr1 11.3 reflect 26.0 refract 62.9 round 4.0 roundadd 7.7 rsqrt 12.1 "
     "rsqrtnr0 7.5 rsqrtnr1 22.1 satmad 0.1 saturate 0.2 select 7.6 selectboth 115.2 sign 14.5 "
     "signbits 7.3 signclamp 11.0 signmad 7.3 signsat 10.9 signsel 11.0 signsel2 3.6 sin 12.1 sincos 22.6 "
     "sinh 29.8 smoothstep 18.8 sqrt 12.1 sqrt16 12.7 sqrtnr0 7.6 step 4.2 sub 3.9 tan 41.5 tanh 46.7 "
     "trunc 4.0 udiv 140.2 umod 139.8 unitf 10.9 utof 3.5 "},
    {"nvidia-ampere", "Ampere / Ada Lovelace", 6,
     "aAdd 0.8 aAdd1 252.6 aAnd 0.5 aAnd1 412.7 aCmpXchg 4.9 aCmpXchg1 827.3 aMax 0.5 aMax1 414.5 aMin 0.6 "
     "aMin1 414.2 aOr 0.1 aOr1 409.7 aXchg 0.1 aXchg1 414.3 aXor 0.5 aXor1 412.8 abs 0.0 acos 41.7 "
     "acos4 51.2 add 3.4 add16 3.9 arraybase 25.0 arrayread 26.3 arraywrite 1506.5 asin 45.1 atan 63.8 "
     "atan2 78.6 atan4 20.0 atombase 23.8 barrier 13.1 bitcast 0.0 bitor 4.6 bitrev 20.9 branchdiv 228.7 "
     "branchuni 111.8 ceil 23.7 clamp 9.9 constarray 409.6 contract 3.9 cos 23.9 cosh 51.1 cross 21.0 "
     "cvt1 3.0 det3 31.1 distance 37.2 div 23.7 divxy 20.6 dot2 7.4 dot3 11.1 dot4 15.3 exp 24.0 exp2 23.7 "
     "exp2_16 23.9 exp2ceil 66.1 exp2floor 79.3 f16round 5.3 faceforward 24.3 fbh 21.1 fbl 47.3 floor 23.7 "
     "flooradd 17.4 fma+cvt -0.9 fma+fma -0.0 fma+half 0.5 fma+int -7.0 fma+minmax -6.9 fma+rcp -13.7 "
     "fma1 3.5 fmod 28.0 frac 24.2 fracadd 17.5 frexp 52.1 ftoitof 24.2 ftou 14.5 groupbarrier 48.4 "
     "gsbase 24.6 gsbase32 25.1 gsread 4.0 gsread32 343.3 gswrite 7.3 gswrite32 410.7 gswriteread 27.4 "
     "half1 -0.3 iadd 1.0 iand 2.1 icmpsel 13.9 idiv 78.7 imin 6.9 imod 80.4 imul 1.3 int 9.9 irot 13.8 "
     "ishr 6.9 isinf 17.2 isnan 11.4 itof 6.9 ixmul 3.1 ldexp 20.6 length 28.1 lerp 7.4 log 24.4 "
     "log10 24.0 log2 23.7 log2_16 17.0 mad 4.0 mad16 -0.3 mad16v3 3.0 mad2 3.9 mad2v 3.5 mad3v 7.0 "
     "mad4v 10.4 matmul4 58.0 max 4.5 max3 5.4 membarrier 83.6 min 4.5 minmax 5.4 minmax1 9.9 mix16 6.3 "
     "modf 24.1 mul 0.5 mul16 3.8 neg 0.0 negabs 0.0 normalize 28.2 omod0.125 0.5 omod0.25 0.3 omod2 0.4 "
     "omod3 0.4 omod4 0.4 omod8 -0.2 omodhalf 0.4 popc 19.6 pow 51.8 pow2ceil 6.3 pow2floor 4.0 "
     "radians 3.0 rcp 23.7 rcp1 23.8 rcp16 23.9 rcpmax 23.8 rcpnr0 2.6 rcpnr1 15.7 reflect 26.2 "
     "refract 63.9 round 23.7 roundadd 7.0 rsqrt 23.7 rsqrtnr0 13.5 rsqrtnr1 15.2 satmad -0.0 saturate 0.1 "
     "select 11.0 selectboth 219.9 sign 27.6 signbits 11.4 signclamp 14.0 signmad 7.0 signsat 10.7 "
     "signsel 27.4 signsel2 6.5 sin 23.9 sincos 46.1 sinh 51.6 smoothstep 17.5 sqrt 23.7 sqrt16 23.9 "
     "sqrtnr0 2.9 step 4.5 sub 3.4 tan 78.9 tanh 80.0 trunc 23.6 udiv 64.0 umod 66.7 unitf 6.9 utof 6.9 "},
    {"nvidia-blackwell", "Blackwell", 2,
     "aAdd -0.2 aAdd1 244.7 aAnd 0.9 aAnd1 399.6 aCmpXchg 7.5 aCmpXchg1 852.0 aMax 0.1 aMax1 399.4 "
     "aMin 0.9 aMin1 410.8 aOr 0.9 aOr1 414.2 aXchg 0.9 aXchg1 411.6 aXor 1.0 aXor1 427.9 abs -0.1 "
     "acos 42.1 add 3.5 add16 3.0 arraybase 25.2 arrayread 25.8 arraywrite 1187.5 asin 45.6 atan 64.5 "
     "atan2 72.0 atombase 23.5 barrier 23.1 bitcast 0.0 bitor 3.7 bitrev 20.4 branchdiv 218.3 "
     "branchuni 107.2 ceil 23.0 clamp 7.9 constarray 410.1 contract 4.5 cos 24.4 cosh 51.2 cross 24.9 "
     "cvt1 3.0 det3 35.5 distance 43.4 div 22.8 divxy 20.4 dot2 6.7 dot3 10.7 dot4 13.2 exp 24.7 exp2 23.7 "
     "exp2_16 24.0 f16round 7.2 faceforward 27.0 fbh 21.4 fbl 47.7 floor 23.0 flooradd 17.9 fma+cvt -1.2 "
     "fma+fma 0.0 fma+half 0.8 fma+int -4.3 fma+minmax 0.4 fma+rcp -13.5 fma1 3.6 fmod 28.7 frac 23.4 "
     "fracadd 17.9 frexp 36.4 ftoitof 23.6 ftou 14.7 groupbarrier 143.7 gsbase 25.2 gsbase32 24.9 "
     "gsread 4.0 gsread32 338.4 gswrite 6.0 gswrite32 410.3 gswriteread 26.1 half1 -0.4 iadd 0.2 iand 0.7 "
     "icmpsel 10.2 idiv 78.1 imin 3.5 imod 80.5 imul 0.7 int 6.3 irot 13.0 ishr 6.8 isinf 11.4 isnan 6.9 "
     "itof 6.7 ixmul 3.0 ldexp 20.2 length 28.7 lerp 7.6 log 23.3 log10 23.5 log2 23.2 mad 4.0 mad16 -0.4 "
     "mad2 4.6 mad2v 3.8 mad3v 7.0 mad4v 11.7 matmul4 64.2 max 3.4 max3 4.2 membarrier 175.8 min 3.4 "
     "minmax 4.5 minmax1 3.0 modf 23.7 mul 0.5 mul16 3.6 neg -0.1 negabs 0.0 normalize 30.2 omod0.125 0.9 "
     "omod0.25 0.8 omod2 0.5 omod3 1.0 omod4 1.7 omod8 -1.1 omodhalf 1.0 popc 19.7 pow 50.5 radians 0.3 "
     "rcp 23.0 rcp1 23.3 rcp16 24.0 rcpmax 23.0 reflect 27.9 refract 69.2 round 23.2 roundadd 6.9 "
     "rsqrt 23.2 satmad -0.0 saturate 0.2 select 8.2 selectboth 215.8 sign 18.0 signbits 9.3 "
     "signclamp 10.8 signmad 7.2 signsat 10.7 signsel 14.6 signsel2 3.0 sin 24.1 sincos 47.6 sinh 51.2 "
     "smoothstep 19.2 sqrt 23.2 sqrt16 24.1 step 3.1 sub 3.6 tan 75.8 tanh 78.7 trunc 23.4 udiv 65.4 "
     "umod 66.4 unitf 7.1 utof 6.8 "},
    {"nvidia-maxwell", "Maxwell", 2,
     "aAdd 8.4 aAdd1 254.9 aAnd 8.4 aAnd1 428.6 aCmpXchg 16.5 aCmpXchg1 428.7 aMax 8.4 aMax1 428.6 "
     "aMin 8.4 aMin1 428.6 aOr 8.4 aOr1 428.6 aXchg 8.4 aXchg1 428.6 aXor 8.4 aXor1 428.7 abs 3.5 "
     "acos 42.2 add 3.5 add16 3.5 arraybase 14.4 arrayread 214.2 arraywrite 1081.2 asin 46.5 atan 66.5 "
     "atan2 96.8 atombase 10.7 barrier 19.8 bitcast 0.0 bitor 3.5 bitrev 3.6 branchdiv 157.9 "
     "branchuni 82.0 ceil 9.9 clamp 11.5 constarray 202.3 contract 3.9 cos 10.0 cosh 24.0 cross 22.1 "
     "cvt1 9.9 det3 34.2 distance 37.1 div 10.0 divxy 6.5 dot2 6.7 dot3 10.5 dot4 14.7 exp 10.0 exp2 10.0 "
     "exp2_16 10.0 f16round 23.9 faceforward 25.3 fbh 14.0 fbl 10.9 floor 9.9 flooradd 17.7 fma+cvt -6.9 "
     "fma+fma -0.0 fma+half 0.0 fma+int -1.3 fma+minmax -6.9 fma+rcp -7.0 fma1 3.6 fmod 14.9 frac 10.0 "
     "fracadd 17.7 frexp 31.9 ftoitof 23.5 ftou 0.6 groupbarrier 32.0 gsbase 17.8 gsbase32 17.9 gsread 1.6 "
     "gsread32 362.6 gswrite 7.0 gswrite32 419.9 gswriteread 17.0 half1 -0.0 iadd 0.6 iand 3.4 icmpsel 7.8 "
     "idiv 94.9 imin 3.6 imod 114.6 imul 2.3 int 3.1 irot 7.9 ishr 3.8 isinf 13.7 isnan 11.8 itof 0.3 "
     "ixmul 10.1 ldexp 8.0 length 24.8 lerp 7.5 log 10.0 log10 10.0 log2 10.0 mad 4.0 mad16 -0.0 mad2 3.9 "
     "mad2v 3.6 mad3v 7.4 mad4v 11.2 matmul4 63.4 max 4.8 max3 6.8 membarrier 32.0 min 4.8 minmax 6.8 "
     "minmax1 10.0 modf 10.0 mul 0.4 mul16 0.4 neg 0.0 negabs 3.5 normalize 24.1 omod0.125 0.0 "
     "omod0.25 0.0 omod2 0.0 omod3 0.0 omod4 0.0 omod8 0.0 omodhalf 0.0 popc 6.7 pow 23.9 radians 0.4 "
     "rcp 10.0 rcp1 9.9 rcp16 10.0 rcpmax 10.0 reflect 26.2 refract 71.5 round 9.9 roundadd 7.1 rsqrt 10.0 "
     "satmad -0.0 saturate 0.2 select 11.8 selectboth 108.1 sign 10.0 signbits 7.0 signclamp 15.1 "
     "signmad 7.1 signsat 10.5 signsel 15.4 signsel2 7.3 sin 10.0 sincos 20.4 sinh 24.0 smoothstep 18.0 "
     "sqrt 16.9 sqrt16 16.9 step 4.8 sub 3.5 tan 37.3 tanh 37.8 trunc 9.9 udiv 90.0 umod 112.5 unitf 7.1 "
     "utof 0.3 "},
    {"nvidia-pascal", "Pascal", 3,
     "aAdd 7.2 aAdd1 198.9 aAnd 7.3 aAnd1 425.5 aCmpXchg 17.3 aCmpXchg1 425.4 aMax 7.2 aMax1 426.9 "
     "aMin 7.2 aMin1 426.7 aOr 7.2 aOr1 426.8 aXchg 7.2 aXchg1 426.2 aXor 7.2 aXor1 426.7 abs 3.5 "
     "acos 38.5 add 3.5 add16 3.5 arraybase 14.3 arrayread 105.3 arraywrite 1178.5 asin 42.1 atan 60.9 "
     "atan2 81.5 atombase 10.9 barrier 14.2 bitcast -0.0 bitor 3.5 bitrev 3.7 branchdiv 137.1 "
     "branchuni 66.7 ceil 10.0 clamp 13.8 constarray 201.2 contract 3.9 cos 10.0 cosh 23.9 cross 22.0 "
     "cvt1 9.8 det3 31.4 distance 32.9 div 10.0 divxy 6.5 dot2 6.7 dot3 10.3 dot4 14.5 exp 10.0 exp2 10.0 "
     "exp2_16 9.8 f16round 23.9 faceforward 25.5 fbh 13.9 fbl 10.6 floor 10.0 flooradd 17.4 fma+cvt -6.9 "
     "fma+fma 0.0 fma+half -0.0 fma+int -1.3 fma+minmax -5.5 fma+rcp -6.9 fmod 14.8 frac 10.0 fracadd 17.4 "
     "frexp 32.0 ftoitof 23.1 ftou 0.7 groupbarrier 22.0 gsbase 15.5 gsbase32 15.5 gsread 1.4 "
     "gsread32 365.7 gswrite 6.5 gswrite32 419.9 gswriteread 16.1 half1 0.0 iadd 0.8 iand 3.6 icmpsel 7.9 "
     "idiv 85.6 imin 3.8 imod 102.8 imul 2.5 int 3.0 irot 8.8 ishr 3.9 isinf 13.8 isnan 12.0 itof 0.4 "
     "ixmul 9.8 ldexp 7.9 length 22.3 lerp 7.4 log 10.0 log10 10.0 log2 10.0 mad 4.0 mad16 0.0 mad2 4.0 "
     "mad2v 3.6 mad3v 7.2 mad4v 11.4 matmul4 58.6 max 6.7 max3 7.0 membarrier 21.9 min 6.7 minmax 7.1 "
     "minmax1 9.8 modf 9.9 mul 0.4 mul16 0.4 neg 0.0 negabs 3.5 normalize 23.5 omod0.125 0.0 omod0.25 -0.0 "
     "omod2 0.0 omod3 0.0 omod4 -0.0 omod8 0.0 omodhalf 0.0 popc 6.3 pow 23.9 radians 0.4 rcp 10.0 "
     "rcp1 9.8 rcp16 9.8 rcpmax 10.0 reflect 25.6 refract 60.7 round 10.0 roundadd 7.2 rsqrt 10.0 "
     "satmad 0.0 saturate 0.2 select 12.0 selectboth 106.2 sign 10.3 signbits 7.0 signclamp 16.9 "
     "signmad 7.1 signsat 10.5 signsel 18.1 signsel2 7.6 sin 10.0 sincos 20.1 sinh 24.0 smoothstep 17.6 "
     "sqrt 10.0 sqrt16 9.8 step 6.7 sub 3.5 tan 37.2 tanh 37.6 trunc 10.0 udiv 76.1 umod 94.5 unitf 7.2 "
     "utof 0.5 "},
    {"nvidia-turing", "Turing", 5,
     "aAdd 0.6 aAdd1 166.2 aAnd 0.5 aAnd1 494.0 aCmpXchg 16.3 aCmpXchg1 999.3 aMax 0.6 aMax1 492.6 "
     "aMin 0.6 aMin1 494.1 aOr 0.6 aOr1 494.2 aXchg 0.6 aXchg1 494.2 aXor 0.6 aXor1 494.1 abs 0.0 "
     "acos 32.0 acos1 19.6 acos4 35.9 add 4.0 add16 2.0 arraybase 12.1 arrayread 40.4 arraywrite 700.9 "
     "asin 36.5 atan 50.1 atan2 59.3 atan2q 28.2 atan4 23.5 atan5a 32.1 atombase 12.3 barrier 19.6 "
     "bitcast -0.0 bitor 0.7 bitrev 11.9 branchdiv 128.8 branchuni 69.1 ceil 12.0 clamp 4.1 "
     "constarray 235.1 contract 4.0 cos 12.0 cosh 28.0 cross 24.1 cvt1 12.0 det3 33.4 distance 36.6 "
     "div 12.0 divxy 8.0 dot2 8.0 dot3 12.0 dot4 16.2 exp 12.0 exp2 12.0 exp2_16 16.1 exp2ceil 44.1 "
     "exp2floor 44.1 f16round -0.0 faceforward 24.1 fbh 11.9 fbl 27.4 floor 12.0 flooradd 20.1 "
     "fma+cvt -8.0 fma+fma 0.0 fma+half -0.0 fma+int -4.0 fma+minmax -4.0 fma+rcp -8.0 fma1 4.0 fmod 14.1 "
     "frac 12.0 fracadd 20.1 frexp 24.3 ftoitof 27.7 ftou 8.0 groupbarrier 44.0 gsbase 12.8 gsbase32 12.8 "
     "gsread 3.5 gsread32 431.6 gswrite 5.6 gswrite32 485.2 gswriteread 16.5 half1 0.0 iadd 0.6 iand 1.1 "
     "icmpsel 8.0 idiv 83.4 imin 3.8 imod 83.6 imul 0.8 int 4.0 irot 8.1 ishr 4.0 isinf 8.1 isnan 4.6 "
     "itof 11.9 ixmul 0.1 ldexp 8.0 length 24.3 lerp 8.0 log 12.0 log10 12.0 log2 12.0 log2_16 16.1 "
     "mad 4.0 mad16 0.0 mad16v3 -6.3 mad2 4.0 mad2v 4.0 mad3v 8.2 mad4v 12.2 matmul4 67.4 max 0.7 "
     "max16 17.4 max3 3.4 membarrier 63.7 min 0.7 minmax 3.4 minmax1 4.0 mix16 16.7 modf 12.0 mul 0.5 "
     "mul16 2.0 neg 0.0 negabs 0.0 normalize 24.5 omod0.125 -0.0 omod0.25 0.0 omod2 -0.0 omod3 0.0 "
     "omod4 -0.4 omod8 0.0 omodhalf 0.0 popc 11.3 pow 28.0 pow2ceil 3.9 pow2floor 0.7 radians 0.5 rcp 12.0 "
     "rcp1 12.0 rcp16 16.1 rcpmax 12.0 rcpnr0 0.7 rcpnr1 8.0 reflect 28.1 refract 46.0 round 12.0 "
     "roundadd 8.0 rsqrt 12.0 rsqrtnr0 3.9 rsqrtnr1 12.0 satmad -0.0 saturate 0.2 select 4.4 "
     "selectboth 123.7 sign 8.6 signbits 0.8 signclamp 4.1 signmad 8.0 signsat 12.1 signsel 12.2 "
     "signsel2 0.1 sin 12.0 sincos 24.0 sinh 28.0 smoothstep 20.1 sqrt 12.0 sqrt16 16.1 sqrtnr0 0.7 "
     "step 0.7 sub 4.0 tan 43.6 tanh 44.1 trunc 12.0 udiv 64.9 umod 70.8 unitf 4.0 utof 11.9 "},
    {"rdna3", "RDNA 3", 1,
     "aAdd 14.5 aAdd1 900.4 aAnd 14.3 aAnd1 904.0 aCmpXchg 29.3 aCmpXchg1 896.2 aMax 14.9 aMax1 902.5 "
     "aMin 14.3 aMin1 900.4 aOr 14.6 aOr1 900.6 aXchg 15.3 aXchg1 903.6 aXor 14.8 aXor1 901.9 abs -0.0 "
     "acos 54.4 add 3.7 add16 3.7 arraybase 31.3 arrayread 381.0 arraywrite 626.7 asin 58.7 atan 87.4 "
     "atan2 102.9 atombase 11.5 barrier 1.5 bitcast 0.1 bitor 7.9 bitrev 7.2 branchdiv 239.3 "
     "branchuni 117.6 ceil 7.8 clamp 7.8 constarray 10.4 contract 3.9 cos 28.4 cosh 59.6 cross 27.6 "
     "cvt1 7.6 det3 34.6 distance 55.8 div 25.8 divxy 25.0 dot2 8.8 dot3 13.9 dot4 20.5 exp 28.5 exp2 26.8 "
     "exp2_16 25.5 f16round 3.3 faceforward 42.4 fbh 25.4 fbl 7.3 floor 7.8 flooradd 22.2 fma+cvt -4.1 "
     "fma+fma 0.0 fma+half 1.3 fma+int -1.8 fma+minmax -1.7 fma+rcp -14.0 fma1 3.7 fmod 29.9 frac 7.8 "
     "fracadd 22.0 frexp 55.0 ftoitof 25.6 ftou 7.3 groupbarrier -0.3 gsbase 30.4 gsbase32 30.8 gsread 7.6 "
     "gsread32 358.2 gswrite 25.2 gswrite32 429.1 gswriteread 33.8 half1 0.0 iadd 7.3 iand 7.2 "
     "icmpsel 18.1 idiv 208.7 imin 7.2 imod 145.6 imul 29.3 int 3.3 irot 7.0 ishr 7.4 isinf 18.0 "
     "isnan 10.9 itof 7.1 ixmul 32.3 ldexp 23.2 length 38.2 lerp 9.6 log 27.4 log10 27.2 log2 26.7 mad 4.0 "
     "mad16 0.2 mad2 3.9 mad2v 3.9 mad3v 8.0 mad4v 11.7 matmul4 65.8 max 4.6 max3 3.0 membarrier -0.1 "
     "min 4.7 minmax 3.2 minmax1 3.2 modf 15.1 mul 0.3 mul16 1.8 neg 0.0 negabs -0.0 normalize 31.1 "
     "omod0.125 2.4 omod0.25 2.5 omod2 -0.1 omod3 2.4 omod4 -0.1 omod8 2.4 omodhalf -0.1 popc -0.1 "
     "pow 57.1 radians 3.3 rcp 26.8 rcp1 25.4 rcp16 25.7 rcpmax 29.4 reflect 23.5 refract 71.0 round 7.8 "
     "roundadd 10.4 rsqrt 27.3 satmad -0.0 saturate 1.2 select 10.9 selectboth 234.4 sign 35.5 "
     "signbits 14.2 signclamp 11.0 signmad 7.2 signsat 9.9 signsel 23.3 signsel2 10.8 sin 28.6 sincos 51.1 "
     "sinh 59.6 smoothstep 18.1 sqrt 26.9 sqrt16 26.1 step 12.1 sub 4.5 tan 85.9 tanh 95.3 trunc 7.9 "
     "udiv 168.2 umod 112.1 unitf 19.0 utof 7.1 "},
};

// Card name (without (R) / (TM)) -> family, first match wins (ECMAScript regex search).
struct Rule {
  const char* pattern;
  const char* model;
};
inline const Rule kRules[] = {
    {R"(RTX 50\d\d)", "nvidia-blackwell"},
    {R"(RTX (30|40)\d\d)", "nvidia-ampere"},
    {R"(GTX 16\d\d|RTX 20\d\d)", "nvidia-turing"},
    {R"(GTX 10\d\d|GT 10\d\d)", "nvidia-pascal"},
    {R"(GTX (9\d\d|8\d\dM)|Quadro M\d)", "nvidia-maxwell"},
    {R"(RX 9\d\d\d)", "amd-rdna4"},
    {R"(RX 7\d\d\d)", "rdna3"},
    {R"(RX 6\d\d\d|Radeon 6[68]0M|Raphael|Granite Ridge)", "amd-rdna2"},
    {R"(Vega)", "amd-gcn5"},
    {R"(HD [67]\d\d\dM?\b)", "amd-terascale2"},
    {R"(Iris\S* Xe|UHD Graphics 7\d\d)", "intel-gen12"},
    {R"(Iris\S* (Graphics )?5\d\d|U?HD Graphics 6\d\d|HD Graphics 5\d\d)", "intel-gen9"},
    {R"(HD Graphics 4[2-6]\d\d|Iris\S* (Pro )?(Graphics )?5[12]00)", "intel-gen7.5"},
};

// Generic names that only the device ID tells apart.
struct Device {
  unsigned id;
  const char* model;
};
inline const Device kDevices[] = {
    {0x13C0, "amd-rdna2"},
    {0x15D8, "amd-gcn5"},
    {0x1636, "amd-gcn5"},
    {0x164E, "amd-rdna2"},
    {0x1681, "amd-rdna2"},
};

}  // namespace expected
