// Generated by tools/windows/gen_expected.py from docs/opbench: do not edit, rerun it when reports are added.
// What cards of each family (cost model) measure in the OpBench throughput tests: the median cost over the
// family's cards (one report each). Only hardware, no names of the people who ran them.
#pragma once

namespace expected {

struct Family {
  const char* model;
  const char* label;  // architectures
  int cards;
  const char* costs;  // "test cost test cost ..."
};

inline const Family kFamilies[] = {
    {"amd-gcn5", "GCN 5 (Vega)", 2,
     "aAdd 5.5 aAdd1 227.9 aAnd 5.9 aAnd1 217.8 aCmpXchg 12.0 aCmpXchg1 224.7 aMax 7.1 aMax1 232.5 "
     "aMin 6.1 aMin1 213.7 aOr 7.7 aOr1 210.6 aXchg 5.7 aXchg1 234.7 aXor 4.9 aXor1 234.3 abs -0.1 "
     "acos 25.7 add 2.0 add16 1.5 arraybase 8.1 arrayread 146.2 arraywrite 232.4 asin 28.9 atan 39.8 "
     "atan2 46.8 atombase 7.5 barrier 0.1 bitcast -0.1 bitor 2.4 bitrev 1.6 branchdiv 76.3 branchuni 44.5 "
     "ceil 2.0 clamp 4.1 constarray 100.8 contract 4.0 cos 10.1 cosh 19.0 cross 12.0 cvt1 0.2 det3 10.9 "
     "distance 21.8 div 8.1 divxy 10.2 dot2 -0.1 dot3 1.1 dot4 1.1 exp 10.0 exp2 8.3 exp2_16 7.4 "
     "f16round 2.8 faceforward 17.9 fbh 7.0 fbl 1.9 floor 2.1 flooradd 11.6 fma+cvt -0.1 fma+fma -0.2 "
     "fma+half 1.9 fma+int 1.4 fma+minmax 0.2 fma+rcp -3.1 fmod 11.6 frac 2.1 fracadd 10.5 frexp 20.0 "
     "ftoitof 6.1 ftou 1.7 groupbarrier 0.4 gsbase 14.7 gsbase32 14.6 gsread 1.6 gsread32 101.8 "
     "gswrite 3.9 gswrite32 107.4 gswriteread 7.0 half1 -2.8 iadd 1.7 iand 1.7 icmpsel 5.7 idiv 50.1 "
     "imin 1.5 imod 36.9 imul 0.7 int -1.6 irot 1.6 ishr 4.2 isinf 8.0 isnan 6.3 itof 2.1 ixmul 6.0 "
     "ldexp 9.1 length 21.5 lerp 6.0 log 8.1 log10 7.0 log2 8.1 mad 4.0 mad16 -2.7 mad2 4.0 mad2v 4.2 "
     "mad3v 7.3 mad4v 11.1 matmul4 25.2 max 1.9 max3 1.3 membarrier -0.6 min 2.1 minmax 2.0 minmax1 -0.0 "
     "modf 5.4 mul 0.2 mul16 1.6 neg -0.1 negabs -0.2 normalize 21.2 omod0.125 2.9 omod0.25 2.2 omod2 0.2 "
     "omod3 2.2 omod4 0.4 omod8 3.1 omodhalf -0.2 popc 0.1 pow 17.9 radians 0.1 rcp 7.9 rcp1 6.0 rcp16 7.7 "
     "rcpmax 9.9 reflect 10.4 refract 35.7 round 1.9 roundadd 4.6 rsqrt 8.1 satmad -0.8 saturate -1.5 "
     "select 6.3 selectboth 75.7 sign 10.2 signbits 4.2 signclamp 3.8 signmad 4.4 signsat 4.9 signsel 7.5 "
     "signsel2 3.4 sin 10.4 sincos 17.3 sinh 18.5 smoothstep 9.1 sqrt 7.9 sqrt16 8.0 step 3.9 sub 2.0 "
     "tan 25.4 tanh 29.1 trunc 1.7 udiv 41.0 umod 34.2 unitf 5.2 utof 1.8 "},
    {"amd-rdna2", "RDNA 2", 4,
     "aAdd 3.4 aAdd1 331.1 aAnd 3.4 aAnd1 331.3 aCmpXchg 6.5 aCmpXchg1 331.6 aMax 3.4 aMax1 330.9 aMin 3.4 "
     "aMin1 331.2 aOr 3.4 aOr1 331.1 aXchg 3.4 aXchg1 330.9 aXor 3.4 aXor1 331.3 abs -0.0 acos 32.9 "
     "add 3.0 add16 1.5 arraybase 12.6 arrayread 286.3 arraywrite 363.2 asin 35.8 atan 52.7 atan2 61.4 "
     "atombase 7.6 barrier 3.0 bitcast 0.0 bitor 2.9 bitrev 2.8 branchdiv 82.7 branchuni 40.4 ceil 3.0 "
     "clamp 5.9 constarray 0.3 contract 4.0 cos 7.9 cosh 18.1 cross 11.6 cvt1 1.8 det3 15.9 distance 24.5 "
     "div 7.8 divxy 6.5 dot2 2.0 dot3 2.1 dot4 2.2 exp 7.9 exp2 7.7 exp2_16 10.3 f16round -0.2 "
     "faceforward 15.8 fbh 11.9 fbl 2.7 floor 3.0 flooradd 16.7 fma+cvt -1.5 fma+fma -0.0 fma+half 0.8 "
     "fma+int 0.0 fma+minmax -1.5 fma+rcp -5.4 fmod 14.3 frac 3.0 fracadd 16.7 frexp 23.4 ftoitof 12.7 "
     "ftou 3.0 groupbarrier 4.3 gsbase 14.8 gsbase32 14.9 gsread 3.9 gsread32 133.3 gswrite 7.0 "
     "gswrite32 154.9 gswriteread 10.9 half1 -2.5 iadd 2.9 iand 2.9 icmpsel 8.1 idiv 73.8 imin 2.9 "
     "imod 57.8 imul 11.6 int -0.2 irot 2.8 ishr 3.0 isinf 7.2 isnan 4.5 itof 2.7 ixmul 10.7 ldexp 5.6 "
     "length 14.7 lerp 7.0 log 7.8 log10 6.9 log2 7.7 mad 4.0 mad16 -2.5 mad2 4.0 mad2v 5.9 mad3v 11.7 "
     "mad4v 17.6 matmul4 34.6 max 3.0 max3 1.1 membarrier 4.3 min 3.0 minmax 2.9 minmax1 1.8 modf 8.2 "
     "mul -1.0 mul16 1.5 neg -0.0 negabs 0.0 normalize 8.5 omod0.125 1.1 omod0.25 1.1 omod2 0.0 omod3 1.1 "
     "omod4 0.0 omod8 1.1 omodhalf 0.0 popc -0.0 pow 19.4 radians 1.7 rcp 7.8 rcp1 6.9 rcp16 10.2 "
     "rcpmax 7.8 reflect 12.0 refract 38.5 round 3.0 roundadd 7.7 rsqrt 7.8 satmad -0.0 saturate 0.2 "
     "select 5.0 selectboth 82.4 sign 14.0 signbits 5.9 signclamp 5.9 signmad 5.8 signsat 7.8 signsel 10.9 "
     "signsel2 4.9 sin 7.9 sincos 16.6 sinh 18.1 smoothstep 13.8 sqrt 7.7 sqrt16 10.1 step 4.9 sub 3.0 "
     "tan 32.3 tanh 28.7 trunc 2.8 udiv 57.7 umod 44.3 unitf 8.8 utof 2.9 "},
    {"amd-rdna4", "RDNA 4", 1,
     "aAdd 15.1 aAdd1 878.3 aAnd 14.6 aAnd1 877.9 aCmpXchg 28.2 aCmpXchg1 882.8 aMax 16.6 aMax1 871.0 "
     "aMin 15.6 aMin1 887.5 aOr 15.0 aOr1 883.9 aXchg 16.4 aXchg1 875.7 aXor 16.5 aXor1 872.8 abs 0.0 "
     "acos 56.3 add 3.8 add16 3.6 arraybase 29.7 arrayread 481.4 arraywrite 812.7 asin 61.4 atan 84.9 "
     "atan2 103.2 atombase 11.0 barrier 0.1 bitcast -0.0 bitor 7.8 bitrev 7.4 branchdiv 227.5 "
     "branchuni 225.1 ceil 7.7 clamp 7.7 constarray 1.6 contract 4.0 cos 25.2 cosh 53.6 cross 25.6 "
     "cvt1 7.8 det3 33.5 distance 50.7 div 24.7 divxy 21.3 dot2 9.5 dot3 14.7 dot4 24.4 exp 24.9 exp2 24.6 "
     "exp2_16 24.7 f16round 3.2 faceforward 44.2 fbh 25.6 fbl 7.0 floor 7.8 flooradd 23.4 fma+cvt -4.3 "
     "fma+fma -0.0 fma+half 0.5 fma+int -1.7 fma+minmax -1.6 fma+rcp -14.5 fmod 30.8 frac 7.9 fracadd 22.2 "
     "frexp 55.2 ftoitof 25.4 ftou 7.5 groupbarrier 1.7 gsbase 30.2 gsbase32 30.1 gsread 9.8 "
     "gsread32 357.2 gswrite 25.8 gswrite32 417.9 gswriteread 35.4 half1 -0.4 iadd 8.1 iand 7.7 "
     "icmpsel 19.7 idiv 209.4 imin 7.3 imod 148.2 imul 28.5 int 3.2 irot 7.8 ishr 7.4 isinf 18.4 "
     "isnan 11.5 itof 7.4 ixmul 31.9 ldexp 22.4 length 39.4 lerp 9.5 log 24.5 log10 24.2 log2 24.3 mad 4.0 "
     "mad16 -0.4 mad2 4.0 mad2v 3.9 mad3v 7.9 mad4v 11.5 matmul4 71.9 max 4.6 max3 3.1 membarrier 1.1 "
     "min 4.6 minmax 3.2 minmax1 3.1 modf 15.5 mul 0.3 mul16 0.2 neg 0.0 negabs 0.0 normalize 28.6 "
     "omod0.125 2.2 omod0.25 2.1 omod2 0.4 omod3 2.1 omod4 0.4 omod8 2.4 omodhalf 0.6 popc -0.7 pow 53.0 "
     "radians 3.3 rcp 24.5 rcp1 24.8 rcp16 25.0 rcpmax 24.3 reflect 27.5 refract 71.3 round 7.7 "
     "roundadd 10.4 rsqrt 24.7 satmad -0.2 saturate 1.0 select 12.1 selectboth 224.3 sign 37.9 "
     "signbits 13.5 signclamp 10.4 signmad 7.2 signsat 11.0 signsel 23.4 signsel2 11.3 sin 24.9 "
     "sincos 49.3 sinh 54.1 smoothstep 18.1 sqrt 24.8 sqrt16 24.7 step 12.1 sub 4.6 tan 79.1 tanh 82.5 "
     "trunc 7.8 udiv 168.8 umod 111.9 unitf 18.9 utof 7.4 "},
    {"amd-terascale2", "TeraScale 2", 1,
     "abs 2.6 add 2.6 ceil 2.6 clamp 5.2 contract 2.6 cos 13.5 div 10.7 divxy 8.2 exp 10.7 exp2 10.6 "
     "floor 2.6 frac 2.6 lerp 5.2 log 10.7 log2 10.6 mad 4.0 mad2 2.6 max 2.6 max3 2.6 min 2.6 minmax 2.6 "
     "mul 2.6 neg 0.0 negabs 2.6 omod2 0.2 omod3 0.2 omodhalf 0.2 pow 23.9 rcp 10.6 rcpmax 10.7 round 2.6 "
     "rsqrt 10.6 satmad 0.0 saturate 0.2 select 5.2 sign 10.9 sin 16.1 sqrt 10.6 step 2.6 sub 2.6 "},
    {"intel-gen12", "Xe-LP", 1,
     "aAdd 18.0 aAdd1 47.5 aAnd 17.8 aAnd1 455.0 aCmpXchg 32.5 aCmpXchg1 2261.6 aMax 18.3 aMax1 458.2 "
     "aMin 18.1 aMin1 451.7 aOr 17.8 aOr1 456.4 aXchg 18.4 aXchg1 448.1 aXor 18.6 aXor1 456.8 abs 0.0 "
     "acos 40.2 add 3.8 add16 1.9 arraybase 23.0 arrayread 60.4 arraywrite 16508.2 asin 45.5 atan 65.2 "
     "atan2 77.1 atombase 13.1 barrier 31.2 bitcast 0.0 bitor 3.5 bitrev 3.8 branchdiv 112.7 "
     "branchuni 54.2 ceil 3.7 clamp 7.7 constarray 90.8 contract 3.9 cos 10.5 cosh 26.0 cross 25.0 "
     "cvt1 3.5 det3 31.9 distance 40.6 div 10.7 divxy 6.8 dot2 8.1 dot3 19.4 dot4 25.1 exp 10.7 exp2 10.7 "
     "exp2_16 12.3 f16round 4.3 faceforward 27.1 fbh 13.2 fbl 4.2 floor 3.8 flooradd 19.5 fma+cvt -1.7 "
     "fma+fma -0.0 fma+half 0.9 fma+int -1.9 fma+minmax -2.1 fma+rcp -7.3 fmod 15.3 frac 3.8 fracadd 20.8 "
     "frexp 40.1 ftoitof 15.2 ftou 4.1 groupbarrier 1.9 gsbase 27.3 gsbase32 25.7 gsread -0.4 gsread32 1.7 "
     "gswrite 11.7 gswrite32 15.2 gswriteread 16.7 half1 -1.9 iadd 4.1 iand 4.2 icmpsel 8.1 idiv 135.6 "
     "imin 4.1 imod 137.9 imul 7.9 int 3.7 irot 11.4 ishr 7.8 isinf 11.2 isnan 7.6 itof 4.0 ixmul 7.5 "
     "ldexp 7.5 length 28.4 lerp 7.6 log 10.7 log10 10.6 log2 10.7 mad 4.0 mad16 -1.8 mad2 4.1 mad2v 4.1 "
     "mad3v 7.9 mad4v 12.6 matmul4 70.9 max 4.0 max3 3.6 membarrier 16.1 min 4.0 minmax 3.7 minmax1 3.8 "
     "modf 7.3 mul 0.0 mul16 0.2 neg -0.1 negabs 0.0 normalize 21.6 omod0.125 -0.0 omod0.25 0.4 omod2 0.5 "
     "omod3 0.2 omod4 0.2 omod8 0.3 omodhalf 0.3 popc 3.9 pow 25.2 radians 0.0 rcp 10.7 rcp1 10.8 "
     "rcp16 12.5 rcpmax 10.9 reflect 29.6 refract 65.8 round 3.6 roundadd 7.1 rsqrt 10.7 satmad -0.1 "
     "saturate 0.2 select 7.7 selectboth 112.8 sign 17.6 signbits 7.4 signclamp 11.0 signmad 7.6 "
     "signsat 11.2 signsel 14.1 signsel2 3.7 sin 10.6 sincos 21.5 sinh 25.6 smoothstep 18.8 sqrt 10.9 "
     "sqrt16 12.5 step 7.2 sub 3.9 tan 39.8 tanh 39.6 trunc 3.9 udiv 141.2 umod 138.1 unitf 11.2 utof 4.1 "},
    {"intel-gen7.5", "Gen7.5", 1,
     "aAdd 47.5 aAdd1 200.6 aAnd 48.0 aAnd1 241.6 aCmpXchg 67.4 aCmpXchg1 239.3 aMax 46.2 aMax1 242.4 "
     "aMin 45.6 aMin1 240.0 aOr 45.5 aOr1 242.0 aXchg 47.5 aXchg1 240.0 aXor 45.7 aXor1 238.1 abs 0.3 "
     "acos 39.5 add 3.6 add16 3.6 arraybase 30.7 arrayread 38.1 arraywrite 402.9 asin 42.6 atan 62.5 "
     "atan2 74.0 atombase 27.0 barrier 30.9 bitcast 0.0 bitor 3.7 bitrev 6.5 branchdiv 62.3 branchuni 48.0 "
     "ceil 3.8 clamp 11.7 constarray 31.5 contract 3.7 cos 3.4 cosh 13.5 cross 21.3 cvt1 3.7 det3 29.8 "
     "distance 40.2 div 3.5 divxy 7.1 dot2 7.3 dot3 10.3 dot4 15.1 exp 6.8 exp2 3.4 exp2_16 3.4 "
     "f16round 14.3 faceforward 25.0 fbh 26.2 fbl 8.5 floor 3.7 flooradd 16.9 fma+cvt -1.3 fma+fma 0.0 "
     "fma+half -0.3 fma+int -5.0 fma+minmax -5.2 fma+rcp -1.4 fmod 18.7 frac 3.8 fracadd 16.9 frexp 55.5 "
     "ftoitof 17.4 ftou 6.1 groupbarrier 3.8 gsbase 38.7 gsbase32 38.7 gsread 5.6 gsread32 208.2 "
     "gswrite 13.1 gswrite32 225.8 gswriteread 21.8 half1 0.3 iadd 6.5 iand 6.5 icmpsel 19.7 idiv 104.2 "
     "imin 6.5 imod 103.5 imul 23.2 int 10.2 irot 19.8 ishr 15.7 isinf 16.6 isnan 7.4 itof 6.5 ixmul 26.7 "
     "ldexp 7.3 length 29.2 lerp 6.9 log 3.5 log10 3.5 log2 3.4 mad 4.0 mad16 -0.0 mad2 3.7 mad2v 4.4 "
     "mad3v 9.1 mad4v 13.5 matmul4 61.1 max 6.7 max3 5.0 membarrier 49.1 min 6.7 minmax 5.0 minmax1 9.9 "
     "modf 11.3 mul 0.7 mul16 0.7 neg -0.0 negabs 0.0 normalize 30.0 omod0.125 4.3 omod0.25 4.3 omod2 4.2 "
     "omod3 4.3 omod4 4.4 omod8 4.4 omodhalf 4.3 popc 6.7 pow 11.5 radians 0.7 rcp 3.4 rcp1 3.3 rcp16 3.4 "
     "rcpmax 7.7 reflect 25.9 refract 59.7 round 3.8 roundadd 7.0 rsqrt 3.4 satmad 0.0 saturate 0.5 "
     "select 7.3 selectboth 56.5 sign 14.7 signbits 7.5 signclamp 12.5 signmad 7.8 signsat 10.0 "
     "signsel 19.1 signsel2 3.7 sin 3.4 sincos 9.6 sinh 13.5 smoothstep 17.6 sqrt 3.4 sqrt16 3.4 step 7.3 "
     "sub 3.6 tan 22.7 tanh 26.6 trunc 3.8 udiv 107.6 umod 105.0 unitf 15.6 utof 6.6 "},
    {"intel-gen9", "Gen9 / Gen9.5", 3,
     "aAdd 26.5 aAdd1 70.1 aAnd 27.9 aAnd1 250.0 aCmpXchg 39.4 aCmpXchg1 234.2 aMax 27.1 aMax1 256.4 "
     "aMin 26.2 aMin1 243.2 aOr 27.2 aOr1 246.4 aXchg 26.8 aXchg1 245.2 aXor 26.4 aXor1 251.3 abs -0.0 "
     "acos 46.4 add 3.9 add16 2.8 arraybase 22.6 arrayread 26.0 arraywrite 116.3 asin 52.7 atan 63.4 "
     "atan2 82.6 atombase 15.3 barrier 35.6 bitcast 0.0 bitor 3.9 bitrev 4.7 branchdiv 113.3 "
     "branchuni 54.7 ceil 4.0 clamp 7.6 constarray 97.2 contract 4.0 cos 12.1 cosh 30.3 cross 22.1 "
     "cvt1 3.9 det3 31.9 distance 41.5 div 12.2 divxy 11.5 dot2 7.5 dot3 14.4 dot4 18.4 exp 14.7 exp2 12.2 "
     "exp2_16 12.6 f16round 16.6 faceforward 22.7 fbh 13.1 fbl 4.8 floor 4.0 flooradd 19.2 fma+cvt -1.7 "
     "fma+fma -0.1 fma+half 1.0 fma+int -1.9 fma+minmax -1.7 fma+rcp -6.5 fma1 4.1 fmod 15.5 frac 4.0 "
     "fracadd 19.1 frexp 37.0 ftoitof 14.8 ftou 3.7 groupbarrier 5.4 gsbase 26.3 gsbase32 26.4 gsread 1.2 "
     "gsread32 35.6 gswrite 11.3 gswrite32 36.8 gswriteread 28.6 half1 -1.8 iadd 3.6 iand 3.6 icmpsel 7.3 "
     "idiv 137.4 imin 3.7 imod 137.4 imul 7.6 int 4.0 irot 18.0 ishr 7.3 isinf 11.4 isnan 7.1 itof 3.6 "
     "ixmul 7.5 ldexp 14.5 length 32.9 lerp 7.6 log 12.3 log10 12.3 log2 12.1 mad 4.0 mad16 -1.8 mad2 3.9 "
     "mad2v 4.5 mad3v 8.6 mad4v 12.8 matmul4 61.8 max 4.0 max3 3.6 membarrier 72.1 min 3.9 minmax 3.7 "
     "minmax1 4.0 modf 7.6 mul 0.1 mul16 0.7 neg -0.0 negabs -0.0 normalize 28.4 omod0.125 0.8 "
     "omod0.25 0.5 omod2 0.9 omod3 0.5 omod4 0.6 omod8 0.5 omodhalf 0.4 popc 4.9 pow 27.4 radians 0.1 "
     "rcp 12.1 rcp1 12.0 rcp16 12.8 rcpmax 15.2 reflect 26.1 refract 63.1 round 4.0 roundadd 7.7 "
     "rsqrt 12.1 satmad 0.1 saturate 0.2 select 7.6 selectboth 115.3 sign 14.5 signbits 7.2 signclamp 10.9 "
     "signmad 7.3 signsat 10.9 signsel 11.0 signsel2 3.6 sin 12.2 sincos 22.6 sinh 29.9 smoothstep 18.8 "
     "sqrt 12.1 sqrt16 12.8 step 4.2 sub 4.0 tan 41.5 tanh 46.9 trunc 3.9 udiv 140.5 umod 140.4 unitf 10.8 "
     "utof 3.5 "},
    {"nvidia-ampere", "Ampere / Ada Lovelace", 4,
     "aAdd 1.0 aAdd1 251.9 aAnd 0.8 aAnd1 398.7 aCmpXchg 4.5 aCmpXchg1 850.6 aMax 0.8 aMax1 413.1 aMin 1.0 "
     "aMin1 412.3 aOr 0.9 aOr1 416.2 aXchg 0.8 aXchg1 412.8 aXor 0.9 aXor1 413.0 abs 0.0 acos 40.7 add 3.4 "
     "add16 3.2 arraybase 25.9 arrayread 26.5 arraywrite 1560.6 asin 45.6 atan 64.1 atan2 78.6 "
     "atombase 24.4 barrier 13.9 bitcast 0.0 bitor 4.4 bitrev 20.9 branchdiv 226.8 branchuni 111.7 "
     "ceil 23.7 clamp 9.9 constarray 407.4 contract 3.9 cos 24.0 cosh 52.2 cross 21.4 cvt1 3.1 det3 31.2 "
     "distance 37.5 div 23.7 divxy 20.6 dot2 7.7 dot3 10.8 dot4 15.5 exp 23.9 exp2 23.7 exp2_16 23.5 "
     "f16round 5.3 faceforward 24.6 fbh 21.6 fbl 47.8 floor 23.7 flooradd 16.7 fma+cvt -0.9 fma+fma 0.0 "
     "fma+half 0.5 fma+int -7.0 fma+minmax -6.9 fma+rcp -13.7 fmod 28.1 frac 24.2 fracadd 17.3 frexp 51.2 "
     "ftoitof 24.4 ftou 14.5 groupbarrier 49.4 gsbase 25.3 gsbase32 25.5 gsread 4.3 gsread32 358.3 "
     "gswrite 7.7 gswrite32 412.2 gswriteread 27.6 half1 -0.3 iadd 0.8 iand 1.8 icmpsel 13.8 idiv 78.9 "
     "imin 6.8 imod 81.5 imul 1.2 int 10.1 irot 13.8 ishr 6.9 isinf 17.3 isnan 11.5 itof 7.0 ixmul 3.2 "
     "ldexp 20.9 length 28.5 lerp 7.3 log 24.3 log10 24.7 log2 23.7 mad 4.0 mad16 -0.2 mad2 3.9 mad2v 3.4 "
     "mad3v 7.0 mad4v 10.7 matmul4 59.1 max 4.5 max3 5.4 membarrier 85.1 min 4.5 minmax 5.4 minmax1 9.9 "
     "modf 24.4 mul 0.5 mul16 3.9 neg 0.0 negabs 0.0 normalize 29.3 omod0.125 0.4 omod0.25 0.4 omod2 0.4 "
     "omod3 0.4 omod4 0.4 omod8 0.4 omodhalf 0.4 popc 19.9 pow 51.9 radians 2.9 rcp 23.7 rcp1 23.8 "
     "rcp16 24.2 rcpmax 23.8 reflect 26.6 refract 65.1 round 23.7 roundadd 7.0 rsqrt 23.7 satmad 0.0 "
     "saturate 0.2 select 11.0 selectboth 219.0 sign 27.6 signbits 11.4 signclamp 14.7 signmad 7.1 "
     "signsat 10.5 signsel 27.5 signsel2 6.5 sin 23.9 sincos 48.3 sinh 52.2 smoothstep 18.0 sqrt 23.7 "
     "sqrt16 24.2 step 4.5 sub 3.4 tan 79.6 tanh 80.1 trunc 22.3 udiv 64.3 umod 67.0 unitf 6.9 utof 6.9 "},
    {"nvidia-blackwell", "Blackwell", 2,
     "aAdd -0.2 aAdd1 244.7 aAnd 0.9 aAnd1 399.6 aCmpXchg 7.5 aCmpXchg1 852.0 aMax 0.1 aMax1 399.4 "
     "aMin 0.9 aMin1 410.8 aOr 0.9 aOr1 414.2 aXchg 0.9 aXchg1 411.6 aXor 1.0 aXor1 427.9 abs -0.1 "
     "acos 42.1 add 3.5 add16 3.0 arraybase 25.2 arrayread 25.8 arraywrite 1187.5 asin 45.6 atan 64.5 "
     "atan2 72.0 atombase 23.5 barrier 23.1 bitcast 0.0 bitor 3.7 bitrev 20.4 branchdiv 218.3 "
     "branchuni 107.2 ceil 23.0 clamp 7.9 constarray 410.1 contract 4.5 cos 24.4 cosh 51.2 cross 24.9 "
     "cvt1 3.0 det3 35.5 distance 43.4 div 22.8 divxy 20.4 dot2 6.7 dot3 10.7 dot4 13.2 exp 24.7 exp2 23.7 "
     "exp2_16 24.0 f16round 7.2 faceforward 27.0 fbh 21.4 fbl 47.7 floor 23.0 flooradd 17.9 fma+cvt -1.2 "
     "fma+fma 0.0 fma+half 0.8 fma+int -4.3 fma+minmax 0.4 fma+rcp -13.5 fma1 3.6 fmod 28.7 frac 23.4 "
     "fracadd 17.9 frexp 36.4 ftoitof 23.6 ftou 14.7 groupbarrier 143.7 gsbase 25.2 gsbase32 24.9 "
     "gsread 4.0 gsread32 338.4 gswrite 6.0 gswrite32 410.3 gswriteread 26.1 half1 -0.4 iadd 0.2 iand 0.7 "
     "icmpsel 10.2 idiv 78.1 imin 3.5 imod 80.5 imul 0.7 int 6.3 irot 13.0 ishr 6.8 isinf 11.4 isnan 6.9 "
     "itof 6.7 ixmul 3.0 ldexp 20.2 length 28.7 lerp 7.6 log 23.3 log10 23.5 log2 23.2 mad 4.0 mad16 -0.4 "
     "mad2 4.6 mad2v 3.8 mad3v 7.0 mad4v 11.7 matmul4 64.2 max 3.4 max3 4.2 membarrier 175.8 min 3.4 "
     "minmax 4.5 minmax1 3.0 modf 23.7 mul 0.5 mul16 3.6 neg -0.1 negabs 0.0 normalize 30.2 omod0.125 0.9 "
     "omod0.25 0.8 omod2 0.5 omod3 1.0 omod4 1.7 omod8 -1.1 omodhalf 1.0 popc 19.7 pow 50.5 radians 0.3 "
     "rcp 23.0 rcp1 23.3 rcp16 24.0 rcpmax 23.0 reflect 27.9 refract 69.2 round 23.2 roundadd 6.9 "
     "rsqrt 23.2 satmad -0.0 saturate 0.2 select 8.2 selectboth 215.8 sign 18.0 signbits 9.3 "
     "signclamp 10.8 signmad 7.2 signsat 10.7 signsel 14.6 signsel2 3.0 sin 24.1 sincos 47.6 sinh 51.2 "
     "smoothstep 19.2 sqrt 23.2 sqrt16 24.1 step 3.1 sub 3.6 tan 75.8 tanh 78.7 trunc 23.4 udiv 65.4 "
     "umod 66.4 unitf 7.1 utof 6.8 "},
    {"nvidia-maxwell", "Maxwell", 2,
     "aAdd 8.4 aAdd1 254.9 aAnd 8.4 aAnd1 428.5 aCmpXchg 16.5 aCmpXchg1 428.9 aMax 8.4 aMax1 428.6 "
     "aMin 8.4 aMin1 428.6 aOr 8.4 aOr1 428.6 aXchg 8.4 aXchg1 428.7 aXor 8.4 aXor1 428.7 abs 3.5 "
     "acos 42.1 add 3.5 add16 3.5 arraybase 14.4 arrayread 214.2 arraywrite 1081.6 asin 46.5 atan 66.5 "
     "atan2 96.8 atombase 10.7 barrier 19.4 bitcast -0.0 bitor 3.5 bitrev 3.6 branchdiv 157.7 "
     "branchuni 82.2 ceil 9.9 clamp 11.5 constarray 202.3 contract 3.9 cos 10.0 cosh 24.0 cross 22.1 "
     "cvt1 9.9 det3 34.2 distance 37.1 div 10.0 divxy 6.5 dot2 6.7 dot3 10.5 dot4 14.7 exp 10.0 exp2 10.0 "
     "exp2_16 10.0 f16round 23.9 faceforward 25.4 fbh 14.0 fbl 10.9 floor 9.9 flooradd 17.7 fma+cvt -6.9 "
     "fma+fma 0.0 fma+half 0.0 fma+int -1.3 fma+minmax -6.9 fma+rcp -7.0 fmod 14.9 frac 10.0 fracadd 17.7 "
     "frexp 31.9 ftoitof 23.5 ftou 0.6 groupbarrier 32.7 gsbase 16.7 gsbase32 16.7 gsread 1.4 "
     "gsread32 366.5 gswrite 7.5 gswrite32 420.7 gswriteread 17.5 half1 0.0 iadd 0.6 iand 3.4 icmpsel 7.8 "
     "idiv 94.9 imin 3.6 imod 114.5 imul 2.2 int 3.1 irot 7.9 ishr 3.8 isinf 13.7 isnan 11.8 itof 0.3 "
     "ixmul 10.1 ldexp 8.0 length 24.8 lerp 7.5 log 10.0 log10 10.0 log2 10.0 mad 4.0 mad16 -0.0 mad2 3.9 "
     "mad2v 3.6 mad3v 7.4 mad4v 11.2 matmul4 63.5 max 4.8 max3 6.8 membarrier 32.7 min 4.8 minmax 6.8 "
     "minmax1 10.0 modf 10.0 mul 0.4 mul16 0.4 neg 0.0 negabs 3.5 normalize 24.1 omod0.125 0.0 "
     "omod0.25 0.0 omod2 0.0 omod3 0.0 omod4 0.0 omod8 0.0 omodhalf 0.0 popc 6.7 pow 23.9 radians 0.4 "
     "rcp 10.0 rcp1 9.9 rcp16 10.0 rcpmax 10.0 reflect 26.2 refract 71.5 round 9.9 roundadd 7.1 rsqrt 10.0 "
     "satmad -0.0 saturate 0.2 select 11.8 selectboth 108.1 sign 10.0 signbits 7.0 signclamp 15.2 "
     "signmad 7.1 signsat 10.5 signsel 15.4 signsel2 7.3 sin 10.0 sincos 20.4 sinh 24.0 smoothstep 18.0 "
     "sqrt 16.9 sqrt16 16.9 step 4.8 sub 3.5 tan 37.2 tanh 37.8 trunc 9.9 udiv 89.8 umod 112.7 unitf 7.2 "
     "utof 0.3 "},
    {"nvidia-pascal", "Pascal", 3,
     "aAdd 7.2 aAdd1 198.9 aAnd 7.3 aAnd1 425.5 aCmpXchg 17.3 aCmpXchg1 425.4 aMax 7.2 aMax1 426.9 "
     "aMin 7.2 aMin1 426.7 aOr 7.2 aOr1 426.8 aXchg 7.2 aXchg1 426.2 aXor 7.2 aXor1 426.7 abs 3.5 "
     "acos 38.5 add 3.5 add16 3.5 arraybase 14.3 arrayread 105.3 arraywrite 1178.5 asin 42.1 atan 60.9 "
     "atan2 81.5 atombase 10.9 barrier 14.2 bitcast -0.0 bitor 3.5 bitrev 3.7 branchdiv 137.1 "
     "branchuni 66.7 ceil 10.0 clamp 13.8 constarray 201.2 contract 3.9 cos 10.0 cosh 23.9 cross 22.0 "
     "cvt1 9.8 det3 31.4 distance 32.9 div 10.0 divxy 6.5 dot2 6.7 dot3 10.3 dot4 14.5 exp 10.0 exp2 10.0 "
     "exp2_16 9.8 f16round 23.9 faceforward 25.5 fbh 13.9 fbl 10.6 floor 10.0 flooradd 17.4 fma+cvt -6.9 "
     "fma+fma 0.0 fma+half -0.0 fma+int -1.3 fma+minmax -5.5 fma+rcp -6.9 fmod 14.8 frac 10.0 fracadd 17.4 "
     "frexp 32.0 ftoitof 23.1 ftou 0.7 groupbarrier 22.0 gsbase 15.5 gsbase32 15.5 gsread 1.4 "
     "gsread32 365.7 gswrite 6.5 gswrite32 419.9 gswriteread 16.1 half1 0.0 iadd 0.8 iand 3.6 icmpsel 7.9 "
     "idiv 85.6 imin 3.8 imod 102.8 imul 2.5 int 3.0 irot 8.8 ishr 3.9 isinf 13.8 isnan 12.0 itof 0.4 "
     "ixmul 9.8 ldexp 7.9 length 22.3 lerp 7.4 log 10.0 log10 10.0 log2 10.0 mad 4.0 mad16 0.0 mad2 4.0 "
     "mad2v 3.6 mad3v 7.2 mad4v 11.4 matmul4 58.6 max 6.7 max3 7.0 membarrier 21.9 min 6.7 minmax 7.1 "
     "minmax1 9.8 modf 9.9 mul 0.4 mul16 0.4 neg 0.0 negabs 3.5 normalize 23.5 omod0.125 0.0 omod0.25 -0.0 "
     "omod2 0.0 omod3 0.0 omod4 -0.0 omod8 0.0 omodhalf 0.0 popc 6.3 pow 23.9 radians 0.4 rcp 10.0 "
     "rcp1 9.8 rcp16 9.8 rcpmax 10.0 reflect 25.6 refract 60.7 round 10.0 roundadd 7.2 rsqrt 10.0 "
     "satmad 0.0 saturate 0.2 select 12.0 selectboth 106.2 sign 10.3 signbits 7.0 signclamp 16.9 "
     "signmad 7.1 signsat 10.5 signsel 18.1 signsel2 7.6 sin 10.0 sincos 20.1 sinh 24.0 smoothstep 17.6 "
     "sqrt 10.0 sqrt16 9.8 step 6.7 sub 3.5 tan 37.2 tanh 37.6 trunc 10.0 udiv 76.1 umod 94.5 unitf 7.2 "
     "utof 0.5 "},
    {"nvidia-turing", "Turing", 5,
     "aAdd 0.6 aAdd1 166.2 aAnd 0.6 aAnd1 494.2 aCmpXchg 16.3 aCmpXchg1 1001.6 aMax 0.6 aMax1 494.1 "
     "aMin 0.6 aMin1 494.2 aOr 0.7 aOr1 494.2 aXchg 0.6 aXchg1 494.2 aXor 0.6 aXor1 494.1 abs 0.0 "
     "acos 32.1 add 4.0 add16 2.0 arraybase 12.0 arrayread 40.4 arraywrite 721.9 asin 36.5 atan 50.1 "
     "atan2 59.3 atombase 12.3 barrier 19.6 bitcast 0.0 bitor 0.7 bitrev 11.9 branchdiv 129.5 "
     "branchuni 69.1 ceil 12.0 clamp 4.1 constarray 236.9 contract 4.0 cos 12.0 cosh 28.0 cross 24.1 "
     "cvt1 12.0 det3 33.4 distance 36.6 div 12.0 divxy 8.0 dot2 8.0 dot3 12.1 dot4 16.2 exp 12.0 exp2 12.0 "
     "exp2_16 16.1 f16round 0.0 faceforward 24.1 fbh 11.9 fbl 27.3 floor 12.0 flooradd 20.1 fma+cvt -8.0 "
     "fma+fma 0.0 fma+half -0.0 fma+int -4.0 fma+minmax -4.0 fma+rcp -8.0 fma1 4.0 fmod 14.1 frac 12.0 "
     "fracadd 20.1 frexp 24.4 ftoitof 27.5 ftou 8.0 groupbarrier 43.4 gsbase 12.4 gsbase32 12.4 gsread 3.0 "
     "gsread32 431.6 gswrite 5.5 gswrite32 494.2 gswriteread 16.2 half1 0.0 iadd 0.6 iand 1.1 icmpsel 8.0 "
     "idiv 83.4 imin 4.0 imod 83.7 imul 0.8 int 4.1 irot 8.0 ishr 4.0 isinf 8.1 isnan 4.6 itof 11.9 "
     "ixmul 0.1 ldexp 8.0 length 24.3 lerp 8.0 log 12.0 log10 12.0 log2 12.0 mad 4.0 mad16 0.0 mad2 4.0 "
     "mad2v 4.0 mad3v 8.2 mad4v 12.2 matmul4 67.9 max 0.7 max3 3.4 membarrier 63.6 min 0.7 minmax 3.4 "
     "minmax1 4.0 modf 12.0 mul 0.5 mul16 2.0 neg 0.0 negabs 0.0 normalize 24.7 omod0.125 -0.3 "
     "omod0.25 -0.0 omod2 -0.0 omod3 0.0 omod4 -0.3 omod8 0.0 omodhalf 0.0 popc 11.3 pow 28.0 radians 0.5 "
     "rcp 12.0 rcp1 12.0 rcp16 16.1 rcpmax 12.0 reflect 28.1 refract 46.3 round 12.0 roundadd 8.0 "
     "rsqrt 12.0 satmad -0.0 saturate 0.2 select 4.4 selectboth 123.8 sign 8.5 signbits 0.7 signclamp 4.1 "
     "signmad 8.0 signsat 12.1 signsel 12.1 signsel2 0.1 sin 12.0 sincos 24.0 sinh 28.0 smoothstep 20.1 "
     "sqrt 12.0 sqrt16 16.0 step 0.7 sub 4.0 tan 43.6 tanh 44.1 trunc 12.0 udiv 65.1 umod 71.0 unitf 4.0 "
     "utof 11.9 "},
    {"rdna3", "RDNA 3", 1,
     "aAdd 14.5 aAdd1 900.4 aAnd 14.3 aAnd1 904.0 aCmpXchg 29.3 aCmpXchg1 896.2 aMax 14.9 aMax1 902.5 "
     "aMin 14.3 aMin1 900.4 aOr 14.6 aOr1 900.6 aXchg 15.3 aXchg1 903.6 aXor 14.8 aXor1 901.9 abs -0.0 "
     "acos 54.4 add 3.7 add16 3.7 arraybase 31.3 arrayread 381.0 arraywrite 626.7 asin 58.7 atan 87.4 "
     "atan2 102.9 atombase 11.5 barrier 1.5 bitcast 0.1 bitor 7.9 bitrev 7.2 branchdiv 239.3 "
     "branchuni 117.6 ceil 7.8 clamp 7.8 constarray 10.4 contract 3.9 cos 28.4 cosh 59.6 cross 27.6 "
     "cvt1 7.6 det3 34.6 distance 55.8 div 25.8 divxy 25.0 dot2 8.8 dot3 13.9 dot4 20.5 exp 28.5 exp2 26.8 "
     "exp2_16 25.5 f16round 3.3 faceforward 42.4 fbh 25.4 fbl 7.3 floor 7.8 flooradd 22.2 fma+cvt -4.1 "
     "fma+fma 0.0 fma+half 1.3 fma+int -1.8 fma+minmax -1.7 fma+rcp -14.0 fma1 3.7 fmod 29.9 frac 7.8 "
     "fracadd 22.0 frexp 55.0 ftoitof 25.6 ftou 7.3 groupbarrier -0.3 gsbase 30.4 gsbase32 30.8 gsread 7.6 "
     "gsread32 358.2 gswrite 25.2 gswrite32 429.1 gswriteread 33.8 half1 0.0 iadd 7.3 iand 7.2 "
     "icmpsel 18.1 idiv 208.7 imin 7.2 imod 145.6 imul 29.3 int 3.3 irot 7.0 ishr 7.4 isinf 18.0 "
     "isnan 10.9 itof 7.1 ixmul 32.3 ldexp 23.2 length 38.2 lerp 9.6 log 27.4 log10 27.2 log2 26.7 mad 4.0 "
     "mad16 0.2 mad2 3.9 mad2v 3.9 mad3v 8.0 mad4v 11.7 matmul4 65.8 max 4.6 max3 3.0 membarrier -0.1 "
     "min 4.7 minmax 3.2 minmax1 3.2 modf 15.1 mul 0.3 mul16 1.8 neg 0.0 negabs -0.0 normalize 31.1 "
     "omod0.125 2.4 omod0.25 2.5 omod2 -0.1 omod3 2.4 omod4 -0.1 omod8 2.4 omodhalf -0.1 popc -0.1 "
     "pow 57.1 radians 3.3 rcp 26.8 rcp1 25.4 rcp16 25.7 rcpmax 29.4 reflect 23.5 refract 71.0 round 7.8 "
     "roundadd 10.4 rsqrt 27.3 satmad -0.0 saturate 1.2 select 10.9 selectboth 234.4 sign 35.5 "
     "signbits 14.2 signclamp 11.0 signmad 7.2 signsat 9.9 signsel 23.3 signsel2 10.8 sin 28.6 sincos 51.1 "
     "sinh 59.6 smoothstep 18.1 sqrt 26.9 sqrt16 26.1 step 12.1 sub 4.5 tan 85.9 tanh 95.3 trunc 7.9 "
     "udiv 168.2 umod 112.1 unitf 19.0 utof 7.1 "},
};

// Card name (without (R) / (TM)) -> family, first match wins (ECMAScript regex search).
struct Rule {
  const char* pattern;
  const char* model;
};
inline const Rule kRules[] = {
    {R"(RTX 50\d\d)", "nvidia-blackwell"},
    {R"(RTX (30|40)\d\d)", "nvidia-ampere"},
    {R"(GTX 16\d\d|RTX 20\d\d)", "nvidia-turing"},
    {R"(GTX 10\d\d|GT 10\d\d)", "nvidia-pascal"},
    {R"(GTX (9\d\d|8\d\dM)|Quadro M\d)", "nvidia-maxwell"},
    {R"(RX 9\d\d\d)", "amd-rdna4"},
    {R"(RX 7\d\d\d)", "rdna3"},
    {R"(RX 6\d\d\d|Radeon 6[68]0M|Raphael)", "amd-rdna2"},
    {R"(Vega)", "amd-gcn5"},
    {R"(HD [67]\d\d\dM?\b)", "amd-terascale2"},
    {R"(Iris\S* Xe|UHD Graphics 7\d\d)", "intel-gen12"},
    {R"(Iris\S* (Graphics )?5\d\d|U?HD Graphics 6\d\d|HD Graphics 5\d\d)", "intel-gen9"},
    {R"(HD Graphics 4[2-6]\d\d|Iris\S* (Pro )?(Graphics )?5[12]00)", "intel-gen7.5"},
};

// Generic names that only the device ID tells apart.
struct Device {
  unsigned id;
  const char* model;
};
inline const Device kDevices[] = {
    {0x1636, "amd-gcn5"},
    {0x164E, "amd-rdna2"},
    {0x1681, "amd-rdna2"},
};

}  // namespace expected
