#!/usr/bin/env python3
"""Writes tools/windows/expected.hpp: what other cards of the same family measure in each OpBench test (owner,
2026-10-06: OpBench tells the user when their card differs from its family, so such reports get noticed).

    gen_expected.py            (rerun when reports are added to docs/opbench)

Families are the cost models (tools/site/build.py MODEL_RULES, the card name; NAME_BY_DEVICE for generic names).
Expected value per test = the median over the family's cards of the throughput cost (units_vs_base), one report
per card (its newest), only clean reports (neg ~0) and readings with consensus. Only hardware is stored.
"""
import csv
import importlib.util
import json
import os
import re
import statistics
import sys

sys.dont_write_bytecode = True  # importing tools/site/build.py would leave a __pycache__ in the repo

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
spec = importlib.util.spec_from_file_location("site_build", os.path.join(ROOT, "tools", "site", "build.py"))
site = importlib.util.module_from_spec(spec)
spec.loader.exec_module(site)

# Reports whose clock moved during the run (see CLAUDE.md): left out.
UNRELIABLE = {
    "nvidia-rtx-3050-laptop.csv", "nvidia-rtx-4070.csv", "nvidia-gtx-1660-ti.csv", "nvidia-gtx-1660-ti-2.csv",
    "nvidia-rtx-4090-laptop.csv", "nvidia-rtx-4090-laptop-dgpu.csv", "amd-radeon-680m-rembrandt.csv",
}


# Free steps whose readings swing by several units on clean runs (noise, not the card).
NOISY = {"transpose"}


def version_key(info, base):
    v = tuple(int(x) for x in info.get("version", "0.0").split(".") if x.isdigit())
    m = re.search(r"-v(\d+)", base)
    return (v, int(m.group(1)) if m else 0)


def rows_of(path):
    with open(path, encoding="utf-8", errors="replace") as f:
        lines = [l for l in f.read().splitlines() if l and not l.startswith("#")]
    return list(csv.DictReader(lines))


def main():
    arch = json.load(open(os.path.join(ROOT, "tools", "site", "architectures.json")))
    labels = {}
    for v in arch["vendors"]:
        for a in v["architectures"]:
            if a["model"]:
                labels.setdefault(a["model"], []).append(a["name"])
    cards = {}  # name -> (key, model, rows)
    for path in sorted(os.listdir(os.path.join(ROOT, "docs", "opbench"))):
        if not path.endswith(".csv") or path in UNRELIABLE:
            continue
        full = os.path.join(ROOT, "docs", "opbench", path)
        info = site.read_report(full)
        if info.get("device") in site.SKIP_DEVICES:
            continue
        name = site.clean_name(site.NAME_BY_FILE.get(path) or site.NAME_BY_DEVICE.get(info.get("device", "")) or info.get("gpu", ""))
        model = site.model_of(name)
        if not model:
            continue
        rows = [r for r in rows_of(full) if r.get("config") == "tput"]
        neg = [float(r["units_vs_base"]) for r in rows if r["test"] == "neg"]
        if not neg or abs(neg[0]) > 0.3:
            continue
        key = version_key(info, path[:-4])
        if name not in cards or key > cards[name][0]:
            cards[name] = (key, model, rows)
    families = {}
    for name, (key, model, rows) in sorted(cards.items()):
        fam = families.setdefault(model, {"cards": [], "values": {}})
        fam["cards"].append(name)
        for r in rows:
            if r.get("consensus", "yes") == "no" or r["test"] in NOISY:
                continue
            try:
                fam["values"].setdefault(r["test"], []).append(float(r["units_vs_base"]))
            except ValueError:
                pass
    out = [
        "// Generated by tools/windows/gen_expected.py from docs/opbench: do not edit, rerun it when reports are added.",
        "// What cards of each family (cost model) measure in the OpBench throughput tests: the median cost over the",
        "// family's cards (one report each). Only hardware, no names of the people who ran them.",
        "#pragma once",
        "",
        "namespace expected {",
        "",
        "struct Family {",
        "  const char* model;",
        "  const char* label;  // architectures",
        "  int cards;",
        "  const char* costs;  // \"test cost test cost ...\"",
        "};",
        "",
        "inline const Family kFamilies[] = {",
    ]
    for model in sorted(families):
        fam = families[model]
        costs = " ".join(f"{t} {statistics.median(v):.1f}" for t, v in sorted(fam["values"].items()))
        label = " / ".join(labels.get(model, [model]))
        out.append(f'    {{"{model}", "{label}", {len(fam["cards"])},')
        # Split long strings into several literals.
        parts = []
        cur = ""
        for tok in re.findall(r"\S+ \S+", costs):
            if len(cur) + len(tok) > 100:
                parts.append(cur)
                cur = ""
            cur += tok + " "
        parts.append(cur)
        for i, p in enumerate(parts):
            out.append(f'     "{p}"' + ("}," if i == len(parts) - 1 else ""))
    out += [
        "};",
        "",
        "// Card name (without (R) / (TM)) -> family, first match wins (ECMAScript regex search).",
        "struct Rule {",
        "  const char* pattern;",
        "  const char* model;",
        "};",
        "inline const Rule kRules[] = {",
    ]
    for pattern, model in site.MODEL_RULES:
        out.append(f'    {{R"({pattern})", "{model}"}},')
    out += ["};", "", "// Generic names that only the device ID tells apart.", "struct Device {", "  unsigned id;",
            "  const char* model;", "};", "inline const Device kDevices[] = {"]
    for dev, name in sorted(site.NAME_BY_DEVICE.items()):
        model = site.model_of(site.clean_name(name))
        if model:
            out.append(f'    {{{dev}, "{model}"}},')
    out += ["};", "", "}  // namespace expected", ""]
    dst = os.path.join(ROOT, "tools", "windows", "expected.hpp")
    with open(dst, "w", newline="\n") as f:
        f.write("\n".join(out))
    for model in sorted(families):
        print(model, len(families[model]["cards"]), ", ".join(families[model]["cards"]))


if __name__ == "__main__":
    main()
