#include <cstdlib>
#include <string>

#include "ir/parser.hpp"
#include "measure/backends.hpp"
#include "test.hpp"

using namespace sopt;

TEST(backends_dxbc_instructions) {
  const std::string dis =
      "//\n// Generated by Microsoft (R) HLSL Shader Compiler 10.1\n//\nps_5_0\n"
      "dcl_globalFlags refactoringAllowed\ndcl_temps 1\n"
      "sample_l_indexable(texture2d)(float,float,float,float) r0.x, v1.xyxx, t0.xyzw, s0, l(0.000000)\n"
      "add r0.y, -r0.x, l(1.000000)\nmul o0.xyzw, r0.yyyy, r0.xxxx\nret \n// Approximately 4 instruction slots used\n";
  int n = 0;
  const std::string code = dxbcInstructions(dis, n);
  CHECK(n == 3);
  CHECK(code.find("add r0.y") != std::string::npos && code.find("dcl_") == std::string::npos);
}

TEST(backends_canonical_spirv) {
  // Same code, different ids and names: identical after canonicalization.
  const std::string a = "OpName %7 \"x\"\n%7 = OpFAdd %float %5 %6\n%8 = OpFMul %float %7 %7\n";
  const std::string b = "OpName %42 \"y\"\n%42 = OpFAdd %float %40 %41\n%43 = OpFMul %float %42 %42\n";
  const std::string c = "%42 = OpFAdd %float %40 %41\n%43 = OpFMul %float %42 %40\n";
  CHECK(canonicalSpirv(a) == canonicalSpirv(b));
  CHECK(canonicalSpirv(a) != canonicalSpirv(c));
}

// The real compilers, when configured ($SOPT_FXSTAT; DXBC also $SOPT_FXC): x * 2.0 and
// x + x are the same code after fxc; t * (1 - t) and t - t * t are not.
TEST(backends_measure) {
  const char* fxstat = std::getenv("SOPT_FXSTAT");
  if (!fxstat) {
    std::printf("  skipped: SOPT_FXSTAT not set\n");
    return;
  }
  BackendConfig cfg;
  cfg.fxstat = fxstat;
  cfg.spirvDis = std::getenv("SOPT_SPIRV_DIS") ? std::getenv("SOPT_SPIRV_DIS") : "spirv-dis";
  if (const char* f = std::getenv("SOPT_FXC")) cfg.fxc = f;
#ifndef _WIN32
  cfg.wine = std::getenv("SOPT_WINE") ? std::getenv("SOPT_WINE") : "wine";
#endif
  std::vector<InputDecl> in = {{"t", 0.0, 1.0, 0}};
  const Expr e1 = parseExpr("t * 2.0", in), e2 = parseExpr("t + t", in);
  const Expr e3 = parseExpr("t * (1.0 - t)", in), e4 = parseExpr("t - t * t", in);
  const auto m = measureBackends({&e1, &e2, &e3, &e4}, in, cfg);
  for (const auto& c : m) CHECK(c.spirv > 0);
  if (!cfg.fxc.empty()) {
    for (const auto& c : m) CHECK(c.dxbc > 0);
    CHECK(m[0].dxbcCode == m[1].dxbcCode);
    CHECK(m[2].dxbcCode != m[3].dxbcCode);
  }
}
