// Generated by tools/reshade/gen_ieee754.py: edit the generator, not this file.
//
// sopt_IEEE754.fx: checks IEEE 754 / HLSL float rules the way ReShade compiles them for the current API.
// Each test runs three ways:
//   Folded   - literals only: the parser or the backend compiler folds the whole test.
//   Literal  - NaN / inf / -0 are folded to a constant, written into the generated code as a literal and used at
//              run time: shows how ReShade writes special values for the backend.
//   Run time - the values are made on the GPU from a run-time zero, so nothing folds: shows the code ReShade
//              generates for the operator and what the GPU does with it.
// ok = as IEEE 754 / HLSL require, FAIL = wrong, D3D = differs from Direct3D's rule (Vulkan / OpenGL leave the
// result to the driver there), yes / no = informative (either is allowed). Grew out of CeeJay's NaNtest.fx.
//
// Tests (left to right in the effect):
//    0 [ieee] isnan(NaN)                   isnan(N)
//    1 [ieee] isnan(NaN), NaN precise      isnanPrecise(N)
//    2 [ieee] NaN bit test                 isnanBits(N)
//    3 [ieee] x != x (x = NaN)             (N != N)
//    4 [ieee] NaN != another NaN           (N != N2)
//    5 [ieee] NaN != 1                     (N != ONE)
//    6 [ieee] !(x == x) (x = NaN)          !(N == N)
//    7 [ieee] !(NaN < 1)                   !(N < ONE)
//    8 [ieee] !(NaN > 1)                   !(N > ONE)
//    9 [ieee] !(NaN <= 1)                  !(N <= ONE)
//   10 [ieee] !(NaN >= 1)                  !(N >= ONE)
//   11 [ieee] !isinf(NaN)                  !isinf(N)
//   12 [ieee] NaN + 1 is NaN               isnan(N + ONE)
//   13 [ieee] NaN * 0 is NaN               isnan(N * Z)
//   14 [ieee] (bool)NaN is true            (bool)(N)
//   15 [ieee] (bool)-NaN is true           (bool)(-N)
//   16 [ieee] NaN ? 1 : 0 is 1             ((N) ? 1.0 : 0.0) == 1.0
//   17 [d3d ] int(NaN) == 0                (int)(N) == 0
//   18 [d3d ] min(NaN, 1) == 1             min(N, ONE) == 1.0
//   19 [d3d ] max(NaN, 1) == 1             max(N, ONE) == 1.0
//   20 [d3d ] min(1, NaN) == 1             min(ONE, N) == 1.0
//   21 [d3d ] saturate(NaN) == 0           saturate(N) == 0.0
//   22 [d3d ] clamp(NaN, 0, 1) == 0        clamp(N, 0.0, ONE) == 0.0
//   23 [ieee] -0 == +0                     (NZ == Z)
//   24 [ieee] !(-0 < +0)                   !(NZ < Z)
//   25 [ieee] 1 / -0 < 0                   (ONE / NZ) < 0.0
//   26 [ieee] 1 / +0 > 0                   (ONE / Z) > 0.0
//   27 [ieee] rcp(-0) < 0                  rcp(NZ) < 0.0
//   28 [ieee] rcp(+0) > 0                  rcp(Z) > 0.0
//   29 [ieee] 1 / (-0 + +0) > 0            (ONE / (NZ + Z)) > 0.0
//   30 [ieee] 1 / abs(-0) > 0              (ONE / abs(NZ)) > 0.0
//   31 [ieee] -0 has the sign bit          asuint(NZ) == 0x80000000u
//   32 [ieee] sign(-0) == 0                sign(NZ) == 0.0
//   33 [ieee] 1 / 0 > FLT_MAX              PINF > 3.402823466e38
//   34 [ieee] -1 / 0 < -FLT_MAX            NINF < -3.402823466e38
//   35 [ieee] +inf > -inf                  (PINF > NINF)
//   36 [ieee] isinf(+inf) && isinf(-inf)   (isinf(PINF) && isinf(NINF))
//   37 [ieee] inf - inf is NaN             isnan(PINF - PINF2)
//   38 [ieee] inf * 0 is NaN               isnan(PINF * Z)
//   39 [ieee] 1 / inf == 0                 (ONE / PINF) == 0.0
//   40 [ieee] 1 / (1 / -inf) < 0           (ONE / (ONE / NINF)) < 0.0
//   41 [ieee] sqrt(inf) == inf             sqrt(PINF) == PINF
//   42 [ieee] exp2(-inf) == 0              exp2(NINF) == 0.0
//   43 [ieee] exp2(inf) == inf             isinf(exp2(PINF))
//   44 [ieee] rsqrt(+0) == +inf            rsqrt(Z) > 3.402823466e38
//   45 [ieee] log2(+0) == -inf             log2(Z) < -3.402823466e38
//   46 [ieee] sqrt(-1) is NaN              isnan(sqrt(-ONE))
//   47 [ieee] log2(-1) is NaN              isnan(log2(-ONE))
//   48 [ieee] 1 + 2^-23 != 1 (fp32)        (ONE + 1.1920929e-7) != ONE
//   49 [ieee] 0.062499996 != 0.06249999    (Z + 0.062499996) != 0.06249999
//   50 [ieee] 2^24 + 1 == 2^24 (even)      (16777216.0 * ONE + 1.0) == 16777216.0
//   51 [d3d ] round(0.5) == 0 (even)       round(0.5 * ONE) == 0.0
//   52 [ieee] round(1.5) == 2              round(1.5 * ONE) == 2.0
//   53 [d3d ] round(2.5) == 2 (even)       round(2.5 * ONE) == 2.0
//   54 [ieee] frac(-0.25) == 0.75          frac(-0.25 * ONE) == 0.75
//   55 [ieee] -1.5 % 1 == -0.5             ((-1.5 * ONE) % ONE) == -0.5
//   56 [ieee] trunc(-1.5) == -1            trunc(-1.5 * ONE) == -1.0
//   57 [ieee] int(-1.5) == -1              (int)(-1.5 * ONE) == -1
//   58 [d3d ] uint(-1.5) == 0              (uint)(-1.5 * ONE) == 0u
//   59 [d3d ] int(3e9) == 2147483647       (int)(3e9 * ONE) == 2147483647
//   60 [info] FLT_MIN / 2 kept             (1.17549435e-38 * ONE * 0.5) > 0.0
//   61 [info] 1e-40 kept                   (1e-40 * ONE) > 0.0

uniform float sopt_timer < source = "timer"; >;

#define SOPT_SM4 (__RENDERER__ >= 0xa000)

static const int kTests = 62;
static const int kRows = 37;
static const int kGlyphW = 7;
static const int kGlyphH = 13;
static const int2 kT_title = int2(1117, 21);
static const int2 kT_cols = int2(1138, 24);
static const int2 kT_legend1 = int2(1162, 82);
static const int2 kT_legend2 = int2(1244, 96);
static const int2 kT_wrong = int2(1340, 23);
static const int2 kT_d3d = int2(1363, 15);
static const int2 kT_api_d3d9 = int2(1378, 10);
static const int2 kT_api_d3d10 = int2(1388, 11);
static const int2 kT_api_d3d11 = int2(1399, 11);
static const int2 kT_api_d3d12 = int2(1410, 11);
static const int2 kT_api_gl = int2(1421, 6);
static const int2 kT_api_vk = int2(1427, 6);
static const int2 kT_api_other = int2(1433, 5);
static const int2 kT_reshade = int2(1438, 7);
static const int2 kT_ok = int2(1445, 4);
static const int2 kT_fail = int2(1449, 5);
static const int2 kT_d3dw = int2(1454, 5);
static const int2 kT_yes = int2(1459, 4);
static const int2 kT_no = int2(1463, 4);
static const int2 kT_na = int2(1467, 3);

// Workarounds where the compiler assumes no NaN (fxc without D3DCOMPILE_IEEE_STRICTNESS removes isnan(x) and
// x != x): a precise value, or the bit test.
bool isnanPrecise(float x) { precise float v = x; return isnan(v); }
#if SOPT_SM4
bool isnanBits(float x) { return (asuint(x) & 0x7FFFFFFFu) > 0x7F800000u; }
#endif

// Results: bit 0 Folded, bit 1 Literal, bit 2 Run time (1 = test true); 8 = not available here.
uint runTest(int id, float4 zz, float one)
{
	uint r = 0;
	[forcecase] switch (id)
	{
	case 0: // isnan(NaN)
#if SOPT_SM4
		r = ((isnan((0.0 / 0.0))) ? 1u : 0u)
		  + ((isnan(((0.0 / 0.0) * one))) ? 2u : 0u)
		  + ((isnan((zz.x / zz.y))) ? 4u : 0u);
#else
		r = ((isnan((zz.x / zz.y))) ? 4u : 0u);
#endif
		break;
	case 1: // isnan(NaN), NaN precise
#if SOPT_SM4
		r = ((isnanPrecise((0.0 / 0.0))) ? 1u : 0u)
		  + ((isnanPrecise(((0.0 / 0.0) * one))) ? 2u : 0u)
		  + ((isnanPrecise((zz.x / zz.y))) ? 4u : 0u);
#else
		r = ((isnanPrecise((zz.x / zz.y))) ? 4u : 0u);
#endif
		break;
	case 2: // NaN bit test
#if SOPT_SM4
		r = ((isnanBits((0.0 / 0.0))) ? 1u : 0u)
		  + ((isnanBits(((0.0 / 0.0) * one))) ? 2u : 0u)
		  + ((isnanBits((zz.x / zz.y))) ? 4u : 0u);
#else
		r = 8u;
#endif
		break;
	case 3: // x != x (x = NaN)
#if SOPT_SM4
		r = ((((0.0 / 0.0) != (0.0 / 0.0))) ? 1u : 0u)
		  + (((((0.0 / 0.0) * one) != ((0.0 / 0.0) * one))) ? 2u : 0u)
		  + ((((zz.x / zz.y) != (zz.x / zz.y))) ? 4u : 0u);
#else
		r = ((((zz.x / zz.y) != (zz.x / zz.y))) ? 4u : 0u);
#endif
		break;
	case 4: // NaN != another NaN
#if SOPT_SM4
		r = ((((0.0 / 0.0) != (0.0 / 0.0))) ? 1u : 0u)
		  + (((((0.0 / 0.0) * one) != ((0.0 / 0.0) * one))) ? 2u : 0u)
		  + ((((zz.x / zz.y) != (zz.z / zz.w))) ? 4u : 0u);
#else
		r = ((((zz.x / zz.y) != (zz.z / zz.w))) ? 4u : 0u);
#endif
		break;
	case 5: // NaN != 1
#if SOPT_SM4
		r = ((((0.0 / 0.0) != 1.0)) ? 1u : 0u)
		  + (((((0.0 / 0.0) * one) != one)) ? 2u : 0u)
		  + ((((zz.x / zz.y) != one)) ? 4u : 0u);
#else
		r = ((((zz.x / zz.y) != one)) ? 4u : 0u);
#endif
		break;
	case 6: // !(x == x) (x = NaN)
#if SOPT_SM4
		r = ((!((0.0 / 0.0) == (0.0 / 0.0))) ? 1u : 0u)
		  + ((!(((0.0 / 0.0) * one) == ((0.0 / 0.0) * one))) ? 2u : 0u)
		  + ((!((zz.x / zz.y) == (zz.x / zz.y))) ? 4u : 0u);
#else
		r = ((!((zz.x / zz.y) == (zz.x / zz.y))) ? 4u : 0u);
#endif
		break;
	case 7: // !(NaN < 1)
#if SOPT_SM4
		r = ((!((0.0 / 0.0) < 1.0)) ? 1u : 0u)
		  + ((!(((0.0 / 0.0) * one) < one)) ? 2u : 0u)
		  + ((!((zz.x / zz.y) < one)) ? 4u : 0u);
#else
		r = ((!((zz.x / zz.y) < one)) ? 4u : 0u);
#endif
		break;
	case 8: // !(NaN > 1)
#if SOPT_SM4
		r = ((!((0.0 / 0.0) > 1.0)) ? 1u : 0u)
		  + ((!(((0.0 / 0.0) * one) > one)) ? 2u : 0u)
		  + ((!((zz.x / zz.y) > one)) ? 4u : 0u);
#else
		r = ((!((zz.x / zz.y) > one)) ? 4u : 0u);
#endif
		break;
	case 9: // !(NaN <= 1)
#if SOPT_SM4
		r = ((!((0.0 / 0.0) <= 1.0)) ? 1u : 0u)
		  + ((!(((0.0 / 0.0) * one) <= one)) ? 2u : 0u)
		  + ((!((zz.x / zz.y) <= one)) ? 4u : 0u);
#else
		r = ((!((zz.x / zz.y) <= one)) ? 4u : 0u);
#endif
		break;
	case 10: // !(NaN >= 1)
#if SOPT_SM4
		r = ((!((0.0 / 0.0) >= 1.0)) ? 1u : 0u)
		  + ((!(((0.0 / 0.0) * one) >= one)) ? 2u : 0u)
		  + ((!((zz.x / zz.y) >= one)) ? 4u : 0u);
#else
		r = ((!((zz.x / zz.y) >= one)) ? 4u : 0u);
#endif
		break;
	case 11: // !isinf(NaN)
#if SOPT_SM4
		r = ((!isinf((0.0 / 0.0))) ? 1u : 0u)
		  + ((!isinf(((0.0 / 0.0) * one))) ? 2u : 0u)
		  + ((!isinf((zz.x / zz.y))) ? 4u : 0u);
#else
		r = ((!isinf((zz.x / zz.y))) ? 4u : 0u);
#endif
		break;
	case 12: // NaN + 1 is NaN
#if SOPT_SM4
		r = ((isnan((0.0 / 0.0) + 1.0)) ? 1u : 0u)
		  + ((isnan(((0.0 / 0.0) * one) + one)) ? 2u : 0u)
		  + ((isnan((zz.x / zz.y) + one)) ? 4u : 0u);
#else
		r = ((isnan((zz.x / zz.y) + one)) ? 4u : 0u);
#endif
		break;
	case 13: // NaN * 0 is NaN
#if SOPT_SM4
		r = ((isnan((0.0 / 0.0) * 0.0)) ? 1u : 0u)
		  + ((isnan(((0.0 / 0.0) * one) * (0.0 * one))) ? 2u : 0u)
		  + ((isnan((zz.x / zz.y) * zz.w)) ? 4u : 0u);
#else
		r = ((isnan((zz.x / zz.y) * zz.w)) ? 4u : 0u);
#endif
		break;
	case 14: // (bool)NaN is true
#if SOPT_SM4
		r = (((bool)((0.0 / 0.0))) ? 1u : 0u)
		  + (((bool)(((0.0 / 0.0) * one))) ? 2u : 0u)
		  + (((bool)((zz.x / zz.y))) ? 4u : 0u);
#else
		r = (((bool)((zz.x / zz.y))) ? 4u : 0u);
#endif
		break;
	case 15: // (bool)-NaN is true
#if SOPT_SM4
		r = (((bool)(-(0.0 / 0.0))) ? 1u : 0u)
		  + (((bool)(-((0.0 / 0.0) * one))) ? 2u : 0u)
		  + (((bool)(-(zz.x / zz.y))) ? 4u : 0u);
#else
		r = (((bool)(-(zz.x / zz.y))) ? 4u : 0u);
#endif
		break;
	case 16: // NaN ? 1 : 0 is 1
#if SOPT_SM4
		r = (((((0.0 / 0.0)) ? 1.0 : 0.0) == 1.0) ? 1u : 0u)
		  + ((((((0.0 / 0.0) * one)) ? 1.0 : 0.0) == 1.0) ? 2u : 0u)
		  + (((((zz.x / zz.y)) ? 1.0 : 0.0) == 1.0) ? 4u : 0u);
#else
		r = (((((zz.x / zz.y)) ? 1.0 : 0.0) == 1.0) ? 4u : 0u);
#endif
		break;
	case 17: // int(NaN) == 0
#if SOPT_SM4
		r = (((int)((0.0 / 0.0)) == 0) ? 1u : 0u)
		  + (((int)(((0.0 / 0.0) * one)) == 0) ? 2u : 0u)
		  + (((int)((zz.x / zz.y)) == 0) ? 4u : 0u);
#else
		r = 8u;
#endif
		break;
	case 18: // min(NaN, 1) == 1
#if SOPT_SM4
		r = ((min((0.0 / 0.0), 1.0) == 1.0) ? 1u : 0u)
		  + ((min(((0.0 / 0.0) * one), one) == 1.0) ? 2u : 0u)
		  + ((min((zz.x / zz.y), one) == 1.0) ? 4u : 0u);
#else
		r = ((min((zz.x / zz.y), one) == 1.0) ? 4u : 0u);
#endif
		break;
	case 19: // max(NaN, 1) == 1
#if SOPT_SM4
		r = ((max((0.0 / 0.0), 1.0) == 1.0) ? 1u : 0u)
		  + ((max(((0.0 / 0.0) * one), one) == 1.0) ? 2u : 0u)
		  + ((max((zz.x / zz.y), one) == 1.0) ? 4u : 0u);
#else
		r = ((max((zz.x / zz.y), one) == 1.0) ? 4u : 0u);
#endif
		break;
	case 20: // min(1, NaN) == 1
#if SOPT_SM4
		r = ((min(1.0, (0.0 / 0.0)) == 1.0) ? 1u : 0u)
		  + ((min(one, ((0.0 / 0.0) * one)) == 1.0) ? 2u : 0u)
		  + ((min(one, (zz.x / zz.y)) == 1.0) ? 4u : 0u);
#else
		r = ((min(one, (zz.x / zz.y)) == 1.0) ? 4u : 0u);
#endif
		break;
	case 21: // saturate(NaN) == 0
#if SOPT_SM4
		r = ((saturate((0.0 / 0.0)) == 0.0) ? 1u : 0u)
		  + ((saturate(((0.0 / 0.0) * one)) == 0.0) ? 2u : 0u)
		  + ((saturate((zz.x / zz.y)) == 0.0) ? 4u : 0u);
#else
		r = ((saturate((zz.x / zz.y)) == 0.0) ? 4u : 0u);
#endif
		break;
	case 22: // clamp(NaN, 0, 1) == 0
#if SOPT_SM4
		r = ((clamp((0.0 / 0.0), 0.0, 1.0) == 0.0) ? 1u : 0u)
		  + ((clamp(((0.0 / 0.0) * one), 0.0, one) == 0.0) ? 2u : 0u)
		  + ((clamp((zz.x / zz.y), 0.0, one) == 0.0) ? 4u : 0u);
#else
		r = ((clamp((zz.x / zz.y), 0.0, one) == 0.0) ? 4u : 0u);
#endif
		break;
	case 23: // -0 == +0
#if SOPT_SM4
		r = ((((-0.0) == 0.0)) ? 1u : 0u)
		  + ((((-0.0 * one) == (0.0 * one))) ? 2u : 0u)
		  + ((((-zz.z) == zz.w)) ? 4u : 0u);
#else
		r = ((((-zz.z) == zz.w)) ? 4u : 0u);
#endif
		break;
	case 24: // !(-0 < +0)
#if SOPT_SM4
		r = ((!((-0.0) < 0.0)) ? 1u : 0u)
		  + ((!((-0.0 * one) < (0.0 * one))) ? 2u : 0u)
		  + ((!((-zz.z) < zz.w)) ? 4u : 0u);
#else
		r = ((!((-zz.z) < zz.w)) ? 4u : 0u);
#endif
		break;
	case 25: // 1 / -0 < 0
#if SOPT_SM4
		r = (((1.0 / (-0.0)) < 0.0) ? 1u : 0u)
		  + (((one / (-0.0 * one)) < 0.0) ? 2u : 0u)
		  + (((one / (-zz.z)) < 0.0) ? 4u : 0u);
#else
		r = (((one / (-zz.z)) < 0.0) ? 4u : 0u);
#endif
		break;
	case 26: // 1 / +0 > 0
#if SOPT_SM4
		r = (((1.0 / 0.0) > 0.0) ? 1u : 0u)
		  + (((one / (0.0 * one)) > 0.0) ? 2u : 0u)
		  + (((one / zz.w) > 0.0) ? 4u : 0u);
#else
		r = (((one / zz.w) > 0.0) ? 4u : 0u);
#endif
		break;
	case 27: // rcp(-0) < 0
#if SOPT_SM4
		r = ((rcp((-0.0)) < 0.0) ? 1u : 0u)
		  + ((rcp((-0.0 * one)) < 0.0) ? 2u : 0u)
		  + ((rcp((-zz.z)) < 0.0) ? 4u : 0u);
#else
		r = ((rcp((-zz.z)) < 0.0) ? 4u : 0u);
#endif
		break;
	case 28: // rcp(+0) > 0
#if SOPT_SM4
		r = ((rcp(0.0) > 0.0) ? 1u : 0u)
		  + ((rcp((0.0 * one)) > 0.0) ? 2u : 0u)
		  + ((rcp(zz.w) > 0.0) ? 4u : 0u);
#else
		r = ((rcp(zz.w) > 0.0) ? 4u : 0u);
#endif
		break;
	case 29: // 1 / (-0 + +0) > 0
#if SOPT_SM4
		r = (((1.0 / ((-0.0) + 0.0)) > 0.0) ? 1u : 0u)
		  + (((one / ((-0.0 * one) + (0.0 * one))) > 0.0) ? 2u : 0u)
		  + (((one / ((-zz.z) + zz.w)) > 0.0) ? 4u : 0u);
#else
		r = (((one / ((-zz.z) + zz.w)) > 0.0) ? 4u : 0u);
#endif
		break;
	case 30: // 1 / abs(-0) > 0
#if SOPT_SM4
		r = (((1.0 / abs((-0.0))) > 0.0) ? 1u : 0u)
		  + (((one / abs((-0.0 * one))) > 0.0) ? 2u : 0u)
		  + (((one / abs((-zz.z))) > 0.0) ? 4u : 0u);
#else
		r = (((one / abs((-zz.z))) > 0.0) ? 4u : 0u);
#endif
		break;
	case 31: // -0 has the sign bit
#if SOPT_SM4
		r = ((asuint((-0.0)) == 0x80000000u) ? 1u : 0u)
		  + ((asuint((-0.0 * one)) == 0x80000000u) ? 2u : 0u)
		  + ((asuint((-zz.z)) == 0x80000000u) ? 4u : 0u);
#else
		r = 8u;
#endif
		break;
	case 32: // sign(-0) == 0
#if SOPT_SM4
		r = ((sign((-0.0)) == 0.0) ? 1u : 0u)
		  + ((sign((-0.0 * one)) == 0.0) ? 2u : 0u)
		  + ((sign((-zz.z)) == 0.0) ? 4u : 0u);
#else
		r = ((sign((-zz.z)) == 0.0) ? 4u : 0u);
#endif
		break;
	case 33: // 1 / 0 > FLT_MAX
#if SOPT_SM4
		r = (((1.0 / 0.0) > 3.402823466e38) ? 1u : 0u)
		  + ((((1.0 / 0.0) * one) > 3.402823466e38) ? 2u : 0u)
		  + (((one / zz.x) > 3.402823466e38) ? 4u : 0u);
#else
		r = (((one / zz.x) > 3.402823466e38) ? 4u : 0u);
#endif
		break;
	case 34: // -1 / 0 < -FLT_MAX
#if SOPT_SM4
		r = (((-1.0 / 0.0) < -3.402823466e38) ? 1u : 0u)
		  + ((((-1.0 / 0.0) * one) < -3.402823466e38) ? 2u : 0u)
		  + (((-one / zz.z) < -3.402823466e38) ? 4u : 0u);
#else
		r = (((-one / zz.z) < -3.402823466e38) ? 4u : 0u);
#endif
		break;
	case 35: // +inf > -inf
#if SOPT_SM4
		r = ((((1.0 / 0.0) > (-1.0 / 0.0))) ? 1u : 0u)
		  + (((((1.0 / 0.0) * one) > ((-1.0 / 0.0) * one))) ? 2u : 0u)
		  + ((((one / zz.x) > (-one / zz.z))) ? 4u : 0u);
#else
		r = ((((one / zz.x) > (-one / zz.z))) ? 4u : 0u);
#endif
		break;
	case 36: // isinf(+inf) && isinf(-inf)
#if SOPT_SM4
		r = (((isinf((1.0 / 0.0)) && isinf((-1.0 / 0.0)))) ? 1u : 0u)
		  + (((isinf(((1.0 / 0.0) * one)) && isinf(((-1.0 / 0.0) * one)))) ? 2u : 0u)
		  + (((isinf((one / zz.x)) && isinf((-one / zz.z)))) ? 4u : 0u);
#else
		r = (((isinf((one / zz.x)) && isinf((-one / zz.z)))) ? 4u : 0u);
#endif
		break;
	case 37: // inf - inf is NaN
#if SOPT_SM4
		r = ((isnan((1.0 / 0.0) - (1.0 / 0.0))) ? 1u : 0u)
		  + ((isnan(((1.0 / 0.0) * one) - ((1.0 / 0.0) * one))) ? 2u : 0u)
		  + ((isnan((one / zz.x) - (one / zz.w))) ? 4u : 0u);
#else
		r = ((isnan((one / zz.x) - (one / zz.w))) ? 4u : 0u);
#endif
		break;
	case 38: // inf * 0 is NaN
#if SOPT_SM4
		r = ((isnan((1.0 / 0.0) * 0.0)) ? 1u : 0u)
		  + ((isnan(((1.0 / 0.0) * one) * (0.0 * one))) ? 2u : 0u)
		  + ((isnan((one / zz.x) * zz.w)) ? 4u : 0u);
#else
		r = ((isnan((one / zz.x) * zz.w)) ? 4u : 0u);
#endif
		break;
	case 39: // 1 / inf == 0
#if SOPT_SM4
		r = (((1.0 / (1.0 / 0.0)) == 0.0) ? 1u : 0u)
		  + (((one / ((1.0 / 0.0) * one)) == 0.0) ? 2u : 0u)
		  + (((one / (one / zz.x)) == 0.0) ? 4u : 0u);
#else
		r = (((one / (one / zz.x)) == 0.0) ? 4u : 0u);
#endif
		break;
	case 40: // 1 / (1 / -inf) < 0
#if SOPT_SM4
		r = (((1.0 / (1.0 / (-1.0 / 0.0))) < 0.0) ? 1u : 0u)
		  + (((one / (one / ((-1.0 / 0.0) * one))) < 0.0) ? 2u : 0u)
		  + (((one / (one / (-one / zz.z))) < 0.0) ? 4u : 0u);
#else
		r = (((one / (one / (-one / zz.z))) < 0.0) ? 4u : 0u);
#endif
		break;
	case 41: // sqrt(inf) == inf
#if SOPT_SM4
		r = ((sqrt((1.0 / 0.0)) == (1.0 / 0.0)) ? 1u : 0u)
		  + ((sqrt(((1.0 / 0.0) * one)) == ((1.0 / 0.0) * one)) ? 2u : 0u)
		  + ((sqrt((one / zz.x)) == (one / zz.x)) ? 4u : 0u);
#else
		r = ((sqrt((one / zz.x)) == (one / zz.x)) ? 4u : 0u);
#endif
		break;
	case 42: // exp2(-inf) == 0
#if SOPT_SM4
		r = ((exp2((-1.0 / 0.0)) == 0.0) ? 1u : 0u)
		  + ((exp2(((-1.0 / 0.0) * one)) == 0.0) ? 2u : 0u)
		  + ((exp2((-one / zz.z)) == 0.0) ? 4u : 0u);
#else
		r = ((exp2((-one / zz.z)) == 0.0) ? 4u : 0u);
#endif
		break;
	case 43: // exp2(inf) == inf
#if SOPT_SM4
		r = ((isinf(exp2((1.0 / 0.0)))) ? 1u : 0u)
		  + ((isinf(exp2(((1.0 / 0.0) * one)))) ? 2u : 0u)
		  + ((isinf(exp2((one / zz.x)))) ? 4u : 0u);
#else
		r = ((isinf(exp2((one / zz.x)))) ? 4u : 0u);
#endif
		break;
	case 44: // rsqrt(+0) == +inf
#if SOPT_SM4
		r = ((rsqrt(0.0) > 3.402823466e38) ? 1u : 0u)
		  + ((rsqrt((0.0 * one)) > 3.402823466e38) ? 2u : 0u)
		  + ((rsqrt(zz.w) > 3.402823466e38) ? 4u : 0u);
#else
		r = ((rsqrt(zz.w) > 3.402823466e38) ? 4u : 0u);
#endif
		break;
	case 45: // log2(+0) == -inf
#if SOPT_SM4
		r = ((log2(0.0) < -3.402823466e38) ? 1u : 0u)
		  + ((log2((0.0 * one)) < -3.402823466e38) ? 2u : 0u)
		  + ((log2(zz.w) < -3.402823466e38) ? 4u : 0u);
#else
		r = ((log2(zz.w) < -3.402823466e38) ? 4u : 0u);
#endif
		break;
	case 46: // sqrt(-1) is NaN
#if SOPT_SM4
		r = ((isnan(sqrt(-1.0))) ? 1u : 0u)
		  + ((isnan(sqrt(-one))) ? 2u : 0u)
		  + ((isnan(sqrt(-one))) ? 4u : 0u);
#else
		r = ((isnan(sqrt(-one))) ? 4u : 0u);
#endif
		break;
	case 47: // log2(-1) is NaN
#if SOPT_SM4
		r = ((isnan(log2(-1.0))) ? 1u : 0u)
		  + ((isnan(log2(-one))) ? 2u : 0u)
		  + ((isnan(log2(-one))) ? 4u : 0u);
#else
		r = 8u;
#endif
		break;
	case 48: // 1 + 2^-23 != 1 (fp32)
#if SOPT_SM4
		r = (((1.0 + 1.1920929e-7) != 1.0) ? 1u : 0u)
		  + (((one + 1.1920929e-7) != one) ? 2u : 0u)
		  + (((one + 1.1920929e-7) != one) ? 4u : 0u);
#else
		r = (((one + 1.1920929e-7) != one) ? 4u : 0u);
#endif
		break;
	case 49: // 0.062499996 != 0.06249999
#if SOPT_SM4
		r = (((0.0 + 0.062499996) != 0.06249999) ? 1u : 0u)
		  + ((((0.0 * one) + 0.062499996) != 0.06249999) ? 2u : 0u)
		  + (((zz.w + 0.062499996) != 0.06249999) ? 4u : 0u);
#else
		r = (((zz.w + 0.062499996) != 0.06249999) ? 4u : 0u);
#endif
		break;
	case 50: // 2^24 + 1 == 2^24 (even)
#if SOPT_SM4
		r = (((16777216.0 * 1.0 + 1.0) == 16777216.0) ? 1u : 0u)
		  + (((16777216.0 * one + 1.0) == 16777216.0) ? 2u : 0u)
		  + (((16777216.0 * one + 1.0) == 16777216.0) ? 4u : 0u);
#else
		r = (((16777216.0 * one + 1.0) == 16777216.0) ? 4u : 0u);
#endif
		break;
	case 51: // round(0.5) == 0 (even)
#if SOPT_SM4
		r = ((round(0.5 * 1.0) == 0.0) ? 1u : 0u)
		  + ((round(0.5 * one) == 0.0) ? 2u : 0u)
		  + ((round(0.5 * one) == 0.0) ? 4u : 0u);
#else
		r = ((round(0.5 * one) == 0.0) ? 4u : 0u);
#endif
		break;
	case 52: // round(1.5) == 2
#if SOPT_SM4
		r = ((round(1.5 * 1.0) == 2.0) ? 1u : 0u)
		  + ((round(1.5 * one) == 2.0) ? 2u : 0u)
		  + ((round(1.5 * one) == 2.0) ? 4u : 0u);
#else
		r = ((round(1.5 * one) == 2.0) ? 4u : 0u);
#endif
		break;
	case 53: // round(2.5) == 2 (even)
#if SOPT_SM4
		r = ((round(2.5 * 1.0) == 2.0) ? 1u : 0u)
		  + ((round(2.5 * one) == 2.0) ? 2u : 0u)
		  + ((round(2.5 * one) == 2.0) ? 4u : 0u);
#else
		r = ((round(2.5 * one) == 2.0) ? 4u : 0u);
#endif
		break;
	case 54: // frac(-0.25) == 0.75
#if SOPT_SM4
		r = ((frac(-0.25 * 1.0) == 0.75) ? 1u : 0u)
		  + ((frac(-0.25 * one) == 0.75) ? 2u : 0u)
		  + ((frac(-0.25 * one) == 0.75) ? 4u : 0u);
#else
		r = ((frac(-0.25 * one) == 0.75) ? 4u : 0u);
#endif
		break;
	case 55: // -1.5 % 1 == -0.5
#if SOPT_SM4
		r = ((((-1.5 * 1.0) % 1.0) == -0.5) ? 1u : 0u)
		  + ((((-1.5 * one) % one) == -0.5) ? 2u : 0u)
		  + ((((-1.5 * one) % one) == -0.5) ? 4u : 0u);
#else
		r = ((((-1.5 * one) % one) == -0.5) ? 4u : 0u);
#endif
		break;
	case 56: // trunc(-1.5) == -1
#if SOPT_SM4
		r = ((trunc(-1.5 * 1.0) == -1.0) ? 1u : 0u)
		  + ((trunc(-1.5 * one) == -1.0) ? 2u : 0u)
		  + ((trunc(-1.5 * one) == -1.0) ? 4u : 0u);
#else
		r = ((trunc(-1.5 * one) == -1.0) ? 4u : 0u);
#endif
		break;
	case 57: // int(-1.5) == -1
#if SOPT_SM4
		r = (((int)(-1.5 * 1.0) == -1) ? 1u : 0u)
		  + (((int)(-1.5 * one) == -1) ? 2u : 0u)
		  + (((int)(-1.5 * one) == -1) ? 4u : 0u);
#else
		r = 8u;
#endif
		break;
	case 58: // uint(-1.5) == 0
#if SOPT_SM4
		r = (((uint)(-1.5 * 1.0) == 0u) ? 1u : 0u)
		  + (((uint)(-1.5 * one) == 0u) ? 2u : 0u)
		  + (((uint)(-1.5 * one) == 0u) ? 4u : 0u);
#else
		r = 8u;
#endif
		break;
	case 59: // int(3e9) == 2147483647
#if SOPT_SM4
		r = (((int)(3e9 * 1.0) == 2147483647) ? 1u : 0u)
		  + (((int)(3e9 * one) == 2147483647) ? 2u : 0u)
		  + (((int)(3e9 * one) == 2147483647) ? 4u : 0u);
#else
		r = 8u;
#endif
		break;
	case 60: // FLT_MIN / 2 kept
#if SOPT_SM4
		r = (((1.17549435e-38 * 1.0 * 0.5) > 0.0) ? 1u : 0u)
		  + (((1.17549435e-38 * one * 0.5) > 0.0) ? 2u : 0u)
		  + (((1.17549435e-38 * one * 0.5) > 0.0) ? 4u : 0u);
#else
		r = (((1.17549435e-38 * one * 0.5) > 0.0) ? 4u : 0u);
#endif
		break;
	case 61: // 1e-40 kept
#if SOPT_SM4
		r = (((1e-40 * 1.0) > 0.0) ? 1u : 0u)
		  + (((1e-40 * one) > 0.0) ? 2u : 0u)
		  + (((1e-40 * one) > 0.0) ? 4u : 0u);
#else
		r = (((1e-40 * one) > 0.0) ? 4u : 0u);
#endif
		break;
	}
	return r;
}

// Pass 1 runs every test once, one pixel each, into this texture; the screen and the totals read it, so both show
// the same results (fxc compiles a test inside the totals loop differently than in a cell: different folds).
texture2D sopt_IEEE754Results { Width = 62; Height = 1; Format = RGBA8; };
sampler2D sopt_IEEE754ResultsS { Texture = sopt_IEEE754Results; MinFilter = POINT; MagFilter = POINT; MipFilter = POINT; };

float4 IEEE754RunPS(float4 vpos : SV_Position) : SV_Target
{
	float4 zz = floor(sopt_timer * float4(1e-12, 1.1e-12, 1.2e-12, 1.3e-12)); // run-time +0s nothing can fold
	float one = zz.x + 1.0;
	return float(runTest(int(vpos.x), zz, one)) / 255.0;
}

uint result(int id) { return uint(tex2Dfetch(sopt_IEEE754ResultsS, int2(id, 0)).x * 255.0 + 0.5); }

#if SOPT_SM4

static const uint kFont[380] = {
	0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x01020400u, 0x00020408u, 0x00000408u, 0x00000000u,
	0x02850A00u, 0x00000000u, 0x00000000u, 0x00000000u, 0x050A0000u, 0x0FE51A7Eu, 0x00000512u, 0x00000000u,
	0x05C70400u, 0x0D0E060Au, 0x01021E2Au, 0x00000000u, 0x01224300u, 0x090C8C66u, 0x00001848u, 0x00000000u,
	0x00C18E00u, 0x0E76C704u, 0x00003F22u, 0x00000000u, 0x01020400u, 0x00000000u, 0x00000000u, 0x00000000u,
	0x01020C10u, 0x0103060Cu, 0x00040C08u, 0x00000000u, 0x03020404u, 0x03060C18u, 0x00010408u, 0x00000000u,
	0x038A8400u, 0x0002151Cu, 0x00000000u, 0x00000000u, 0x01000000u, 0x011FC408u, 0x00000408u, 0x00000000u,
	0x00000000u, 0x00000000u, 0x00030418u, 0x00000000u, 0x00000000u, 0x00070000u, 0x00000000u, 0x00000000u,
	0x00000000u, 0x00000000u, 0x00000408u, 0x00000000u, 0x020C1000u, 0x00820418u, 0x00008304u, 0x00000000u,
	0x044D8E00u, 0x0458B562u, 0x00000E36u, 0x00000000u, 0x03060F00u, 0x03060C18u, 0x00003F18u, 0x00000000u,
	0x040C8E00u, 0x01860820u, 0x00001F06u, 0x00000000u, 0x040C8E00u, 0x04080E30u, 0x00000F22u, 0x00000000u,
	0x078E1800u, 0x0FEC9B34u, 0x00001830u, 0x00000000u, 0x00409F00u, 0x0408181Eu, 0x00000F32u, 0x00000000u,
	0x00498E00u, 0x0448931Eu, 0x00000E26u, 0x00000000u, 0x06081F00u, 0x01060810u, 0x0000020Cu, 0x00000000u,
	0x04498E00u, 0x0C488E26u, 0x00001E26u, 0x00000000u, 0x044D8E00u, 0x040F1B22u, 0x00000E32u, 0x00000000u,
	0x00000000u, 0x00000408u, 0x00000408u, 0x00000000u, 0x00000000u, 0x00000408u, 0x00030418u, 0x00000000u,
	0x0C000000u, 0x07018338u, 0x00000060u, 0x00000000u, 0x00000000u, 0x0FE03F80u, 0x00000000u, 0x00000000u,
	0x00600000u, 0x01DC380Eu, 0x00000003u, 0x00000000u, 0x040C8E00u, 0x00020410u, 0x00000408u, 0x00000000u,
	0x0CCF0000u, 0x09B37CC2u, 0x07818179u, 0x00000000u, 0x02870C00u, 0x07C99B14u, 0x000021E2u, 0x00000000u,
	0x04488F00u, 0x0C489F22u, 0x00001F62u, 0x00000000u, 0x00499E00u, 0x00408102u, 0x00001E26u, 0x00000000u,
	0x044C8F00u, 0x0458B162u, 0x00000F32u, 0x00000000u, 0x00409F00u, 0x00409F02u, 0x00003F02u, 0x00000000u,
	0x00C1BF00u, 0x00C19F06u, 0x00000306u, 0x00000000u, 0x00499E00u, 0x0C58B902u, 0x00001E66u, 0x00000000u,
	0x0C58B100u, 0x0C58BF62u, 0x00003162u, 0x00000000u, 0x01021F00u, 0x01020408u, 0x00001F08u, 0x00000000u,
	0x060C1E00u, 0x060C1830u, 0x00000F12u, 0x00000000u, 0x034CB100u, 0x0646870Eu, 0x00003122u, 0x00000000u,
	0x00C18300u, 0x00C18306u, 0x00003F06u, 0x00000000u, 0x0EF9F180u, 0x0872EDD7u, 0x000021C3u, 0x00000000u,
	0x0CD9B300u, 0x0E5EB56Au, 0x00003172u, 0x00000000u, 0x044D8E00u, 0x0458B162u, 0x00000E36u, 0x00000000u,
	0x0C589F00u, 0x00409F62u, 0x00000102u, 0x00000000u, 0x044D8E00u, 0x0458B162u, 0x040C0E36u, 0x00000000u,
	0x044C8F00u, 0x044C8F32u, 0x00002162u, 0x00000000u, 0x00498E00u, 0x0C080E06u, 0x00001E22u, 0x00000000u,
	0x01023F80u, 0x01020408u, 0x00000408u, 0x00000000u, 0x04489100u, 0x04489122u, 0x00000E26u, 0x00000000u,
	0x0458B180u, 0x02851A26u, 0x00000C1Cu, 0x00000000u, 0x09706080u, 0x06DDBF5Bu, 0x00001336u, 0x00000000u,
	0x0289B100u, 0x06870C1Cu, 0x000031A2u, 0x00000000u, 0x0688B180u, 0x01020C1Cu, 0x00000408u, 0x00000000u,
	0x06083F00u, 0x00830C10u, 0x00003F06u, 0x00000000u, 0x01020418u, 0x01020408u, 0x00060408u, 0x00000000u,
	0x00818100u, 0x03020404u, 0x00081810u, 0x00000000u, 0x03060C1Cu, 0x03060C18u, 0x00070C18u, 0x00000000u,
	0x044D0C00u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x0000007Fu,
	0x00000404u, 0x00000000u, 0x00000000u, 0x00000000u, 0x03C00000u, 0x044F1020u, 0x00001F32u, 0x00000000u,
	0x03C08102u, 0x0C58B126u, 0x00000F26u, 0x00000000u, 0x07800000u, 0x00C08304u, 0x00001E04u, 0x00000000u,
	0x07881020u, 0x04489136u, 0x00001E36u, 0x00000000u, 0x03800000u, 0x005FB126u, 0x00001E26u, 0x00000000u,
	0x07C20438u, 0x01020408u, 0x00000408u, 0x00000000u, 0x07800000u, 0x04489136u, 0x06481E36u, 0x0000001Cu,
	0x07C08102u, 0x04489126u, 0x00001122u, 0x00000000u, 0x01C00008u, 0x01020408u, 0x00003F08u, 0x00000000u,
	0x03800018u, 0x03060C18u, 0x03060C18u, 0x0000000Eu, 0x04C18306u, 0x02C78716u, 0x00003326u, 0x00000000u,
	0x0102040Eu, 0x01020408u, 0x00001C08u, 0x00000000u, 0x07C00000u, 0x0952A56Au, 0x0000254Au, 0x00000000u,
	0x07C00000u, 0x04489126u, 0x00001122u, 0x00000000u, 0x03800000u, 0x04489126u, 0x00000E26u, 0x00000000u,
	0x03C00000u, 0x04589126u, 0x00408F26u, 0x00000002u, 0x07800000u, 0x04489136u, 0x04081E36u, 0x00000020u,
	0x0F800000u, 0x0081020Cu, 0x00000204u, 0x00000000u, 0x03800000u, 0x04070326u, 0x00000E22u, 0x00000000u,
	0x07C30600u, 0x0183060Cu, 0x00001C08u, 0x00000000u, 0x04400000u, 0x04489122u, 0x00001E36u, 0x00000000u,
	0x0C400000u, 0x028D1322u, 0x00000C1Cu, 0x00000000u, 0x08200000u, 0x06DEA5C1u, 0x00001B36u, 0x00000000u,
	0x04400000u, 0x03860E34u, 0x00003136u, 0x00000000u, 0x0C400000u, 0x028D1322u, 0x01820C1Cu, 0x00000006u,
	0x07C00000u, 0x01820830u, 0x00001F06u, 0x00000000u, 0x01020C30u, 0x01020708u, 0x000C0C08u, 0x00000000u,
	0x01020408u, 0x01020408u, 0x01020408u, 0x00000000u, 0x0102040Eu, 0x01061818u, 0x00038408u, 0x00000000u,
	0x00000000u, 0x000E2700u, 0x00000000u, 0x00000000u,
};
static const uint kText[368] = {
	0x204E614Eu, 0x706D6F63u, 0x73697261u, 0x20736E6Fu, 0x45454928u, 0x35372045u, 0x73692934u, 0x286E616Eu,
	0x294E614Eu, 0x616E7369u, 0x614E286Eu, 0x202C294Eu, 0x204E614Eu, 0x63657270u, 0x4E657369u, 0x62204E61u,
	0x74207469u, 0x78747365u, 0x203D2120u, 0x78282078u, 0x4E203D20u, 0x4E294E61u, 0x21204E61u, 0x6E61203Du,
	0x6568746Fu, 0x614E2072u, 0x4E614E4Eu, 0x203D2120u, 0x78282131u, 0x203D3D20u, 0x28202978u, 0x203D2078u,
	0x294E614Eu, 0x614E2821u, 0x203C204Eu, 0x28212931u, 0x204E614Eu, 0x2931203Eu, 0x614E2821u, 0x3D3C204Eu,
	0x21293120u, 0x4E614E28u, 0x203D3E20u, 0x69212931u, 0x666E6973u, 0x4E614E28u, 0x4E614E29u, 0x31202B20u,
	0x20736920u, 0x4E4E614Eu, 0x2A204E61u, 0x69203020u, 0x614E2073u, 0x4E614E4Eu, 0x206F7420u, 0x6C6F6F62u,
	0x69202F20u, 0x6228746Eu, 0x296C6F6Fu, 0x204E614Eu, 0x74207369u, 0x28657572u, 0x6C6F6F62u, 0x614E2D29u,
	0x7369204Eu, 0x75727420u, 0x4E614E65u, 0x31203F20u, 0x30203A20u, 0x20736920u, 0x746E6931u, 0x4E614E28u,
	0x3D3D2029u, 0x614E3020u, 0x6E69204Eu, 0x6E696D20u, 0x6D202F20u, 0x2F207861u, 0x74617320u, 0x74617275u,
	0x6E696D65u, 0x4E614E28u, 0x2931202Cu, 0x203D3D20u, 0x78616D31u, 0x4E614E28u, 0x2931202Cu, 0x203D3D20u,
	0x6E696D31u, 0x202C3128u, 0x294E614Eu, 0x203D3D20u, 0x74617331u, 0x74617275u, 0x614E2865u, 0x3D20294Eu,
	0x6330203Du, 0x706D616Cu, 0x4E614E28u, 0x2C30202Cu, 0x20293120u, 0x30203D3Du, 0x6E676953u, 0x7A206465u,
	0x2D6F7265u, 0x3D3D2030u, 0x21302B20u, 0x20302D28u, 0x302B203Cu, 0x2F203129u, 0x20302D20u, 0x3130203Cu,
	0x2B202F20u, 0x203E2030u, 0x70637230u, 0x29302D28u, 0x30203C20u, 0x28706372u, 0x2029302Bu, 0x3130203Eu,
	0x28202F20u, 0x2B20302Du, 0x29302B20u, 0x30203E20u, 0x202F2031u, 0x28736261u, 0x2029302Du, 0x2D30203Eu,
	0x61682030u, 0x68742073u, 0x69732065u, 0x62206E67u, 0x69737469u, 0x2D286E67u, 0x3D202930u, 0x4930203Du,
	0x6E69666Eu, 0x31797469u, 0x30202F20u, 0x46203E20u, 0x4D5F544Cu, 0x312D5841u, 0x30202F20u, 0x2D203C20u,
	0x5F544C46u, 0x2B58414Du, 0x20666E69u, 0x692D203Eu, 0x7369666Eu, 0x28666E69u, 0x666E692Bu, 0x26262029u,
	0x69736920u, 0x2D28666Eu, 0x29666E69u, 0x20666E69u, 0x6E69202Du, 0x73692066u, 0x4E614E20u, 0x20666E69u,
	0x2030202Au, 0x4E207369u, 0x20314E61u, 0x6E69202Fu, 0x3D3D2066u, 0x20313020u, 0x3128202Fu, 0x2D202F20u,
	0x29666E69u, 0x30203C20u, 0x74727173u, 0x666E6928u, 0x3D3D2029u, 0x666E6920u, 0x32707865u, 0x6E692D28u,
	0x3D202966u, 0x6530203Du, 0x28327078u, 0x29666E69u, 0x203D3D20u, 0x4D666E69u, 0x20687461u, 0x74207461u,
	0x65206568u, 0x73656764u, 0x72717372u, 0x302B2874u, 0x3D3D2029u, 0x6E692B20u, 0x676F6C66u, 0x302B2832u,
	0x3D3D2029u, 0x6E692D20u, 0x72717366u, 0x312D2874u, 0x73692029u, 0x4E614E20u, 0x32676F6Cu, 0x29312D28u,
	0x20736920u, 0x524E614Eu, 0x646E756Fu, 0x20676E69u, 0x20646E61u, 0x766E6F63u, 0x69737265u, 0x20316E6Fu,
	0x5E32202Bu, 0x2033322Du, 0x31203D21u, 0x70662820u, 0x30293233u, 0x3236302Eu, 0x39393934u, 0x21203639u,
	0x2E30203Du, 0x34323630u, 0x39393939u, 0x34325E32u, 0x31202B20u, 0x203D3D20u, 0x34325E32u, 0x76652820u,
	0x72296E65u, 0x646E756Fu, 0x352E3028u, 0x3D3D2029u, 0x28203020u, 0x6E657665u, 0x756F7229u, 0x3128646Eu,
	0x2029352Eu, 0x32203D3Du, 0x6E756F72u, 0x2E322864u, 0x3D202935u, 0x2032203Du, 0x65766528u, 0x7266296Eu,
	0x2D286361u, 0x35322E30u, 0x3D3D2029u, 0x372E3020u, 0x2E312D35u, 0x20252035u, 0x3D3D2031u, 0x2E302D20u,
	0x75727435u, 0x2D28636Eu, 0x29352E31u, 0x203D3D20u, 0x6E69312Du, 0x312D2874u, 0x2029352Eu, 0x2D203D3Du,
	0x6E697531u, 0x312D2874u, 0x2029352Eu, 0x30203D3Du, 0x28746E69u, 0x29396533u, 0x203D3D20u, 0x37343132u,
	0x36333834u, 0x65443734u, 0x6D726F6Eu, 0x20736C61u, 0x74696528u, 0x20726568u, 0x61207369u, 0x776F6C6Cu,
	0x46296465u, 0x4D5F544Cu, 0x2F204E49u, 0x6B203220u, 0x31747065u, 0x30342D65u, 0x70656B20u, 0x53655274u,
	0x65646168u, 0x45454920u, 0x35372045u, 0x65742034u, 0x46207473u, 0x65646C6Fu, 0x694C2064u, 0x61726574u,
	0x7552206Cu, 0x6974206Eu, 0x6B6F656Du, 0x72203D20u, 0x74686769u, 0x20202020u, 0x4C494146u, 0x77203D20u,
	0x676E6F72u, 0x45492820u, 0x37204545u, 0x2F203435u, 0x534C4820u, 0x2020294Cu, 0x33442020u, 0x203D2044u,
	0x66666964u, 0x20737265u, 0x6D6F7266u, 0x72694420u, 0x33746365u, 0x20732744u, 0x656C7572u, 0x646C6F46u,
	0x203A6465u, 0x6574696Cu, 0x736C6172u, 0x6C6E6F20u, 0x20202079u, 0x6574694Cu, 0x3A6C6172u, 0x4E614E20u,
	0x69202F20u, 0x2F20666Eu, 0x20302D20u, 0x74697277u, 0x206E6574u, 0x61207361u, 0x74696C20u, 0x6C617265u,
	0x52202020u, 0x74206E75u, 0x3A656D69u, 0x64616D20u, 0x6E6F2065u, 0x65687420u, 0x55504720u, 0x6E6F7277u,
	0x49282067u, 0x20454545u, 0x20343537u, 0x4C48202Fu, 0x6E294C53u, 0x6120746Fu, 0x69442073u, 0x74636572u,
	0x69444433u, 0x74636572u, 0x39204433u, 0x65726944u, 0x44337463u, 0x44303120u, 0x63657269u, 0x20443374u,
	0x69443131u, 0x74636572u, 0x31204433u, 0x65704F32u, 0x564C476Eu, 0x616B6C75u, 0x4950416Eu, 0x65523F20u,
	0x64616853u, 0x6F202065u, 0x4146206Bu, 0x20204C49u, 0x20443344u, 0x20736579u, 0x206F6E20u, 0x20202D20u,
};
static const uint kLines[74] = {
	0x001A0001u, 0x000A006Au, 0x01170092u, 0x020C00EEu, 0x0310011Eu, 0x0412015Eu, 0x050801A6u, 0x061301C6u,
	0x070A0212u, 0x080A023Au, 0x090B0262u, 0x0A0B028Eu, 0x0B0B02BAu, 0x0C0E02E6u, 0x0D0E031Eu, 0x00110355u,
	0x0E11039Au, 0x0F1203DEu, 0x10100426u, 0x110D0466u, 0x001B0499u, 0x12100506u, 0x13100546u, 0x14100586u,
	0x151205C6u, 0x1615060Eu, 0x000B0661u, 0x1708068Eu, 0x180A06AEu, 0x190A06D6u, 0x1A0A06FEu, 0x1B0B0726u,
	0x1C0B0752u, 0x1D11077Eu, 0x1E0F07C2u, 0x1F1307FEu, 0x200D084Au, 0x0008087Du, 0x210F089Eu, 0x221108DAu,
	0x230B091Eu, 0x241A094Au, 0x251009B2u, 0x260E09F2u, 0x270C0A2Au, 0x28120A5Au, 0x29100AA2u, 0x2A0F0AE2u,
	0x2B100B1Eu, 0x00110B5Du, 0x2C110BA2u, 0x2D100BE6u, 0x2E0F0C26u, 0x2F0F0C62u, 0x00170C9Du, 0x30150CFAu,
	0x31190D4Eu, 0x32170DB2u, 0x33160E0Eu, 0x340F0E66u, 0x35160EA2u, 0x36130EFAu, 0x37100F46u, 0x38110F86u,
	0x390F0FCAu, 0x3A0F1006u, 0x3B161042u, 0x001D1099u, 0x3C10110Eu, 0x3D0A114Eu, 0x00000000u, 0x00000000u,
	0x00000000u, 0x00000000u,
};
static const uint kKinds[4] = {
	0x00000000u, 0x00001554u, 0x00000000u, 0x0A500440u,
};

int kindOf(int id) { return int((kKinds[id / 16] >> uint((id % 16) * 2)) & 3u); }

// 1 where the glyph of character code c covers cell pixel p (0..kGlyphW-1, 0..kGlyphH-1).
float glyph(uint c, int2 p)
{
	if (c < 32u || c > 126u || p.x < 0 || p.y < 0 || p.x >= kGlyphW || p.y >= kGlyphH) return 0.0;
	uint w = kFont[(c - 32u) * 4u + uint(p.y / 4)];
	return float((w >> uint((p.y % 4) * kGlyphW + p.x)) & 1u);
}

uint textChar(int2 t, int i) { return i < 0 || i >= t.y ? 32u : (kText[(t.x + i) / 4] >> uint(((t.x + i) % 4) * 8)) & 0xFFu; }

// Text t drawn from character cell 'start' on; cell = character cell of this pixel, p = pixel inside it.
float drawText(int2 t, int start, int cell, int2 p) { return glyph(textChar(t, cell - start), p); }

// Digit d (0..9) of number n drawn right-aligned so that its last digit is at cell 'last'.
float drawNumber(uint n, int last, int cell, int2 p)
{
	int k = last - cell;
	if (k < 0 || k > 9) return 0.0;
	uint m = n;
	for (int i = 0; i < k; ++i) m /= 10u;
	if (m == 0u && k > 0) return 0.0;
	return glyph(48u + m % 10u, p);
}

float3 IEEE754PS(float4 vpos : SV_Position) : SV_Target
{
	int s = max(1, min(BUFFER_HEIGHT / 540, BUFFER_WIDTH / 800)); // pixel scale
	int cw = kGlyphW * s;
	int lh = kGlyphH * s;
	int2 px = int2(vpos.xy) - int2(2 * cw, lh / 2);
	int cell = px.x >= 0 ? px.x / cw : -1;
	int line = px.y >= 0 ? px.y / lh : -1;
	int2 p = int2(px.x - cell * cw, px.y - line * lh) / s;
	int side = cell >= 52 ? 1 : 0;
	int c0 = cell - side * 52;

	float3 col = float3(0.08, 0.09, 0.11);
	float3 ink = float3(0.92, 0.93, 0.95);

	if (line == 0)
	{
		// Title, API and ReShade version.
		float t = drawText(kT_title, 0, cell, p);
		int2 api = kT_api_other;
		if (__RENDERER__ >= 0x20000) api = kT_api_vk;
		else if (__RENDERER__ >= 0x10000) api = kT_api_gl;
		else if (__RENDERER__ >= 0xc000) api = kT_api_d3d12;
		else if (__RENDERER__ >= 0xb000) api = kT_api_d3d11;
		else if (__RENDERER__ >= 0xa000) api = kT_api_d3d10;
		t += drawText(api, 25, cell, p);
		t += drawText(kT_reshade, 40, cell, p);
		t += drawNumber(uint(__RESHADE__ / 10000), 48, cell, p);
		t += cell == 49 ? glyph(46u, p) : 0.0;
		t += drawNumber(uint((__RESHADE__ / 100) % 100), 50, cell, p);
		t += cell == 51 ? glyph(46u, p) : 0.0;
		t += drawNumber(uint(__RESHADE__ % 100), 52, cell, p);
		return lerp(col, float3(1.0, 0.85, 0.3), saturate(t));
	}
	if (line == 1)
		return lerp(col, ink * 0.75, saturate(drawText(kT_legend1, 0, cell, p)));
	if (line == 2)
	{
		// Totals per column: left half wrong (IEEE 754 / HLSL), right half not as Direct3D.
		if (cell < 0 || (c0 % 8 == 7 && c0 < 24)) return col;
		uint3 wrong = uint3(0u, 0u, 0u);
		uint3 notd3d = uint3(0u, 0u, 0u);
		[loop] for (int i = 0; i < kTests; ++i)
		{
			uint r = result(i);
			if (r == 8u) continue;
			uint3 fails = uint3((r & 1u) ^ 1u, ((r >> 1) & 1u) ^ 1u, ((r >> 2) & 1u) ^ 1u);
			int k = kindOf(i);
			if (k == 0) wrong += fails;
			else if (k == 1) notd3d += fails;
		}
		uint3 n = side == 0 ? wrong : notd3d;
		float t = drawNumber(n.x, 4, c0, p) + drawNumber(n.y, 12, c0, p) + drawNumber(n.z, 20, c0, p);
		t += drawText(side == 0 ? kT_wrong : kT_d3d, 25, c0, p);
		bool bad = side == 0 ? any(n != 0u) : false;
		return lerp(col, bad ? float3(1.0, 0.45, 0.4) : float3(0.5, 0.95, 0.55), saturate(t));
	}
	if (line == 3)
		return lerp(col, ink * 0.6, saturate(drawText(kT_cols, 0, c0, p)));

	int row = line - 4;
	if (row < 0 || row >= kRows || cell < 0) return col;
	uint d = kLines[side * kRows + row];
	int type = int(d & 3u);
	int2 t = int2(int((d >> 2) & 0x3FFFu), int((d >> 16) & 0xFFu));
	if (type == 0) return col;
	if (type == 1)
		return lerp(col, float3(0.45, 0.8, 1.0), saturate(drawText(t, 0, c0, p)));

	int id = int(d >> 24);
	if (c0 >= 25)
		return lerp(col, ink, saturate(drawText(t, 25, c0, p)));
	// Result boxes: 7 cells + 1 gap each.
	int box = c0 / 8;
	if (c0 % 8 == 7 || box > 2) return col;
	int py = px.y - line * lh;
	if (py < s / 2 || py >= lh - s / 2) return col;
	uint r = result(id);
	int k = kindOf(id);
	bool good = (r & (1u << uint(box))) != 0u;
	float3 bg;
	int2 word;
	if (r == 8u) { bg = float3(0.25, 0.25, 0.27); word = kT_na; }
	else if (k == 2) { bg = float3(0.2, 0.35, 0.6); word = good ? kT_yes : kT_no; }
	else if (good) { bg = float3(0.12, 0.45, 0.18); word = kT_ok; }
	else if (k == 1) { bg = float3(0.75, 0.42, 0.05); word = kT_d3dw; }
	else { bg = float3(0.75, 0.12, 0.1); word = kT_fail; }
	return lerp(bg, float3(1.0, 1.0, 1.0), saturate(drawText(word, box * 8, c0, p)));
}

#else

// Direct3D 9 (shader model 3) has no integer bit operations for the font and allows no NaN / inf literals: the run-time
// results only, one box per test, top to bottom in the order listed at the top of this file (green true, red false; grey
// = needs shader model 4).
float3 IEEE754PS(float4 vpos : SV_Position) : SV_Target
{
	float2 c = floor(vpos.xy / float2(48.0, 14.0));
	int id = int(c.y) - 1;
	if (id < 0 || id >= kTests || c.x != 1.0) return float3(0.08, 0.09, 0.11);
	float r = float(result(id));
	if (r > 7.5) return float3(0.25, 0.25, 0.27);
	return r > 3.5 ? float3(0.12, 0.6, 0.18) : float3(0.8, 0.12, 0.1);
}

#endif

void IEEE754VS(in uint id : SV_VertexID, out float4 position : SV_Position)
{
	const float2 uv = float2(id == 2 ? 2.0 : 0.0, id == 1 ? 2.0 : 0.0);
	position = float4(uv * float2(2.0, -2.0) + float2(-1.0, 1.0), 0.0, 1.0);
}

technique sopt_IEEE754 < ui_tooltip = "IEEE 754 / HLSL float rules as ReShade compiles them for this API.\n"
	"Folded = literals only, Literal = NaN / inf / -0 written as literals, Run time = made on the GPU."; >
{
	pass Run
	{
		VertexShader = IEEE754VS;
		PixelShader = IEEE754RunPS;
		RenderTarget = sopt_IEEE754Results;
	}
	pass Show
	{
		VertexShader = IEEE754VS;
		PixelShader = IEEE754PS;
	}
}

