// Generated by tools/reshade/gen_ieee754.py: edit the generator, not this file.
//
// sopt_IEEE754.fx: checks IEEE 754 / HLSL float rules the way ReShade compiles them for the current API.
// Each test runs three ways:
//   Folded   - literals only: the parser or the backend compiler folds the whole test.
//   Literal  - NaN / inf / -0 are folded to a constant, written into the generated code as a literal and used at
//              run time: shows how ReShade writes special values for the backend.
//   Run time - the values are made on the GPU from a run-time zero, so nothing folds: shows the code ReShade
//              generates for the operator and what the GPU does with it.
// ok = as IEEE 754 / HLSL require, FAIL = wrong, D3D = differs from Direct3D's rule (Vulkan / OpenGL leave the
// result to the driver there), yes / no = informative (either is allowed). Grew out of CeeJay's NaNtest.fx.
//
// Tests (left to right in the effect):
//    0 [ieee] isnan(NaN)                   isnan(N)
//    1 [ieee] isnan(NaN), NaN precise      isnanPrecise(N)
//    2 [ieee] NaN bit test                 isnanBits(N)
//    3 [ieee] x != x (x = NaN)             (N != N)
//    4 [ieee] NaN != another NaN           (N != N2)
//    5 [ieee] NaN != 1                     (N != ONE)
//    6 [ieee] !(x == x) (x = NaN)          !(N == N)
//    7 [ieee] !(NaN < 1)                   !(N < ONE)
//    8 [ieee] !(NaN > 1)                   !(N > ONE)
//    9 [ieee] !(NaN <= 1)                  !(N <= ONE)
//   10 [ieee] !(NaN >= 1)                  !(N >= ONE)
//   11 [ieee] !isinf(NaN)                  !isinf(N)
//   12 [ieee] NaN + 1 is NaN               isnan(N + ONE)
//   13 [ieee] NaN * 0 is NaN               isnan(N * Z)
//   14 [ieee] (bool)NaN is true            (bool)(N)
//   15 [ieee] NaN ? 1 : 0 is 1             ((N) ? 1.0 : 0.0) == 1.0
//   16 [d3d ] int(NaN) == 0                (int)(N) == 0
//   17 [d3d ] min(NaN, 1) == 1             min(N, ONE) == 1.0
//   18 [d3d ] max(NaN, 1) == 1             max(N, ONE) == 1.0
//   19 [d3d ] min(1, NaN) == 1             min(ONE, N) == 1.0
//   20 [d3d ] saturate(NaN) == 0           saturate(N) == 0.0
//   21 [d3d ] clamp(NaN, 0, 1) == 0        clamp(N, 0.0, ONE) == 0.0
//   22 [ieee] -0 == +0                     (NZ == Z)
//   23 [ieee] !(-0 < +0)                   !(NZ < Z)
//   24 [ieee] 1 / -0 < 0                   (ONE / NZ) < 0.0
//   25 [ieee] 1 / +0 > 0                   (ONE / Z) > 0.0
//   26 [ieee] rcp(-0) < 0                  rcp(NZ) < 0.0
//   27 [ieee] rcp(+0) > 0                  rcp(Z) > 0.0
//   28 [ieee] 1 / (-0 + +0) > 0            (ONE / (NZ + Z)) > 0.0
//   29 [ieee] 1 / abs(-0) > 0              (ONE / abs(NZ)) > 0.0
//   30 [ieee] -0 has the sign bit          asuint(NZ) == 0x80000000u
//   31 [ieee] sign(-0) == 0                sign(NZ) == 0.0
//   32 [ieee] 1 / 0 > FLT_MAX              PINF > 3.402823466e38
//   33 [ieee] -1 / 0 < -FLT_MAX            NINF < -3.402823466e38
//   34 [ieee] +inf > -inf                  (PINF > NINF)
//   35 [ieee] isinf(+inf) && isinf(-inf)   (isinf(PINF) && isinf(NINF))
//   36 [ieee] inf - inf is NaN             isnan(PINF - PINF2)
//   37 [ieee] inf * 0 is NaN               isnan(PINF * Z)
//   38 [ieee] 1 / inf == 0                 (ONE / PINF) == 0.0
//   39 [ieee] 1 / (1 / -inf) < 0           (ONE / (ONE / NINF)) < 0.0
//   40 [ieee] sqrt(inf) == inf             sqrt(PINF) == PINF
//   41 [ieee] exp2(-inf) == 0              exp2(NINF) == 0.0
//   42 [ieee] exp2(inf) == inf             isinf(exp2(PINF))
//   43 [ieee] rsqrt(+0) == +inf            rsqrt(Z) > 3.402823466e38
//   44 [ieee] log2(+0) == -inf             log2(Z) < -3.402823466e38
//   45 [ieee] sqrt(-1) is NaN              isnan(sqrt(-ONE))
//   46 [ieee] log2(-1) is NaN              isnan(log2(-ONE))
//   47 [ieee] 1 + 2^-23 != 1 (fp32)        (ONE + 1.1920929e-7) != ONE
//   48 [ieee] 0.062499996 != 0.06249999    (Z + 0.062499996) != 0.06249999
//   49 [ieee] 2^24 + 1 == 2^24 (even)      (16777216.0 * ONE + 1.0) == 16777216.0
//   50 [d3d ] round(0.5) == 0 (even)       round(0.5 * ONE) == 0.0
//   51 [ieee] round(1.5) == 2              round(1.5 * ONE) == 2.0
//   52 [d3d ] round(2.5) == 2 (even)       round(2.5 * ONE) == 2.0
//   53 [ieee] frac(-0.25) == 0.75          frac(-0.25 * ONE) == 0.75
//   54 [ieee] -1.5 % 1 == -0.5             ((-1.5 * ONE) % ONE) == -0.5
//   55 [ieee] trunc(-1.5) == -1            trunc(-1.5 * ONE) == -1.0
//   56 [ieee] int(-1.5) == -1              (int)(-1.5 * ONE) == -1
//   57 [d3d ] uint(-1.5) == 0              (uint)(-1.5 * ONE) == 0u
//   58 [d3d ] int(3e9) == 2147483647       (int)(3e9 * ONE) == 2147483647
//   59 [info] FLT_MIN / 2 kept             (1.17549435e-38 * ONE * 0.5) > 0.0
//   60 [info] 1e-40 kept                   (1e-40 * ONE) > 0.0

uniform float sopt_timer < source = "timer"; >;

#define SOPT_SM4 (__RENDERER__ >= 0xa000)

static const int kTests = 61;
static const int kRows = 36;
static const int kGlyphW = 7;
static const int kGlyphH = 13;
static const int2 kT_title = int2(1099, 21);
static const int2 kT_cols = int2(1120, 24);
static const int2 kT_legend1 = int2(1144, 82);
static const int2 kT_legend2 = int2(1226, 96);
static const int2 kT_wrong = int2(1322, 23);
static const int2 kT_d3d = int2(1345, 15);
static const int2 kT_api_d3d9 = int2(1360, 10);
static const int2 kT_api_d3d10 = int2(1370, 11);
static const int2 kT_api_d3d11 = int2(1381, 11);
static const int2 kT_api_d3d12 = int2(1392, 11);
static const int2 kT_api_gl = int2(1403, 6);
static const int2 kT_api_vk = int2(1409, 6);
static const int2 kT_api_other = int2(1415, 5);
static const int2 kT_reshade = int2(1420, 7);
static const int2 kT_ok = int2(1427, 4);
static const int2 kT_fail = int2(1431, 5);
static const int2 kT_d3dw = int2(1436, 5);
static const int2 kT_yes = int2(1441, 4);
static const int2 kT_no = int2(1445, 4);
static const int2 kT_na = int2(1449, 3);

// Workarounds where the compiler assumes no NaN (fxc without D3DCOMPILE_IEEE_STRICTNESS removes isnan(x) and
// x != x): a precise value, or the bit test.
bool isnanPrecise(float x) { precise float v = x; return isnan(v); }
#if SOPT_SM4
bool isnanBits(float x) { return (asuint(x) & 0x7FFFFFFFu) > 0x7F800000u; }
#endif

// Results: bit 0 Folded, bit 1 Literal, bit 2 Run time (1 = test true); 8 = not available here.
uint runTest(int id, float4 zz, float one)
{
	uint r = 0;
	[forcecase] switch (id)
	{
	case 0: // isnan(NaN)
#if SOPT_SM4
		r = ((isnan((0.0 / 0.0))) ? 1u : 0u)
		  + ((isnan(((0.0 / 0.0) * one))) ? 2u : 0u)
		  + ((isnan((zz.x / zz.y))) ? 4u : 0u);
#else
		r = ((isnan((zz.x / zz.y))) ? 4u : 0u);
#endif
		break;
	case 1: // isnan(NaN), NaN precise
#if SOPT_SM4
		r = ((isnanPrecise((0.0 / 0.0))) ? 1u : 0u)
		  + ((isnanPrecise(((0.0 / 0.0) * one))) ? 2u : 0u)
		  + ((isnanPrecise((zz.x / zz.y))) ? 4u : 0u);
#else
		r = ((isnanPrecise((zz.x / zz.y))) ? 4u : 0u);
#endif
		break;
	case 2: // NaN bit test
#if SOPT_SM4
		r = ((isnanBits((0.0 / 0.0))) ? 1u : 0u)
		  + ((isnanBits(((0.0 / 0.0) * one))) ? 2u : 0u)
		  + ((isnanBits((zz.x / zz.y))) ? 4u : 0u);
#else
		r = 8u;
#endif
		break;
	case 3: // x != x (x = NaN)
#if SOPT_SM4
		r = ((((0.0 / 0.0) != (0.0 / 0.0))) ? 1u : 0u)
		  + (((((0.0 / 0.0) * one) != ((0.0 / 0.0) * one))) ? 2u : 0u)
		  + ((((zz.x / zz.y) != (zz.x / zz.y))) ? 4u : 0u);
#else
		r = ((((zz.x / zz.y) != (zz.x / zz.y))) ? 4u : 0u);
#endif
		break;
	case 4: // NaN != another NaN
#if SOPT_SM4
		r = ((((0.0 / 0.0) != (0.0 / 0.0))) ? 1u : 0u)
		  + (((((0.0 / 0.0) * one) != ((0.0 / 0.0) * one))) ? 2u : 0u)
		  + ((((zz.x / zz.y) != (zz.z / zz.w))) ? 4u : 0u);
#else
		r = ((((zz.x / zz.y) != (zz.z / zz.w))) ? 4u : 0u);
#endif
		break;
	case 5: // NaN != 1
#if SOPT_SM4
		r = ((((0.0 / 0.0) != 1.0)) ? 1u : 0u)
		  + (((((0.0 / 0.0) * one) != one)) ? 2u : 0u)
		  + ((((zz.x / zz.y) != one)) ? 4u : 0u);
#else
		r = ((((zz.x / zz.y) != one)) ? 4u : 0u);
#endif
		break;
	case 6: // !(x == x) (x = NaN)
#if SOPT_SM4
		r = ((!((0.0 / 0.0) == (0.0 / 0.0))) ? 1u : 0u)
		  + ((!(((0.0 / 0.0) * one) == ((0.0 / 0.0) * one))) ? 2u : 0u)
		  + ((!((zz.x / zz.y) == (zz.x / zz.y))) ? 4u : 0u);
#else
		r = ((!((zz.x / zz.y) == (zz.x / zz.y))) ? 4u : 0u);
#endif
		break;
	case 7: // !(NaN < 1)
#if SOPT_SM4
		r = ((!((0.0 / 0.0) < 1.0)) ? 1u : 0u)
		  + ((!(((0.0 / 0.0) * one) < one)) ? 2u : 0u)
		  + ((!((zz.x / zz.y) < one)) ? 4u : 0u);
#else
		r = ((!((zz.x / zz.y) < one)) ? 4u : 0u);
#endif
		break;
	case 8: // !(NaN > 1)
#if SOPT_SM4
		r = ((!((0.0 / 0.0) > 1.0)) ? 1u : 0u)
		  + ((!(((0.0 / 0.0) * one) > one)) ? 2u : 0u)
		  + ((!((zz.x / zz.y) > one)) ? 4u : 0u);
#else
		r = ((!((zz.x / zz.y) > one)) ? 4u : 0u);
#endif
		break;
	case 9: // !(NaN <= 1)
#if SOPT_SM4
		r = ((!((0.0 / 0.0) <= 1.0)) ? 1u : 0u)
		  + ((!(((0.0 / 0.0) * one) <= one)) ? 2u : 0u)
		  + ((!((zz.x / zz.y) <= one)) ? 4u : 0u);
#else
		r = ((!((zz.x / zz.y) <= one)) ? 4u : 0u);
#endif
		break;
	case 10: // !(NaN >= 1)
#if SOPT_SM4
		r = ((!((0.0 / 0.0) >= 1.0)) ? 1u : 0u)
		  + ((!(((0.0 / 0.0) * one) >= one)) ? 2u : 0u)
		  + ((!((zz.x / zz.y) >= one)) ? 4u : 0u);
#else
		r = ((!((zz.x / zz.y) >= one)) ? 4u : 0u);
#endif
		break;
	case 11: // !isinf(NaN)
#if SOPT_SM4
		r = ((!isinf((0.0 / 0.0))) ? 1u : 0u)
		  + ((!isinf(((0.0 / 0.0) * one))) ? 2u : 0u)
		  + ((!isinf((zz.x / zz.y))) ? 4u : 0u);
#else
		r = ((!isinf((zz.x / zz.y))) ? 4u : 0u);
#endif
		break;
	case 12: // NaN + 1 is NaN
#if SOPT_SM4
		r = ((isnan((0.0 / 0.0) + 1.0)) ? 1u : 0u)
		  + ((isnan(((0.0 / 0.0) * one) + one)) ? 2u : 0u)
		  + ((isnan((zz.x / zz.y) + one)) ? 4u : 0u);
#else
		r = ((isnan((zz.x / zz.y) + one)) ? 4u : 0u);
#endif
		break;
	case 13: // NaN * 0 is NaN
#if SOPT_SM4
		r = ((isnan((0.0 / 0.0) * 0.0)) ? 1u : 0u)
		  + ((isnan(((0.0 / 0.0) * one) * (0.0 * one))) ? 2u : 0u)
		  + ((isnan((zz.x / zz.y) * zz.w)) ? 4u : 0u);
#else
		r = ((isnan((zz.x / zz.y) * zz.w)) ? 4u : 0u);
#endif
		break;
	case 14: // (bool)NaN is true
#if SOPT_SM4
		r = (((bool)((0.0 / 0.0))) ? 1u : 0u)
		  + (((bool)(((0.0 / 0.0) * one))) ? 2u : 0u)
		  + (((bool)((zz.x / zz.y))) ? 4u : 0u);
#else
		r = (((bool)((zz.x / zz.y))) ? 4u : 0u);
#endif
		break;
	case 15: // NaN ? 1 : 0 is 1
#if SOPT_SM4
		r = (((((0.0 / 0.0)) ? 1.0 : 0.0) == 1.0) ? 1u : 0u)
		  + ((((((0.0 / 0.0) * one)) ? 1.0 : 0.0) == 1.0) ? 2u : 0u)
		  + (((((zz.x / zz.y)) ? 1.0 : 0.0) == 1.0) ? 4u : 0u);
#else
		r = (((((zz.x / zz.y)) ? 1.0 : 0.0) == 1.0) ? 4u : 0u);
#endif
		break;
	case 16: // int(NaN) == 0
#if SOPT_SM4
		r = (((int)((0.0 / 0.0)) == 0) ? 1u : 0u)
		  + (((int)(((0.0 / 0.0) * one)) == 0) ? 2u : 0u)
		  + (((int)((zz.x / zz.y)) == 0) ? 4u : 0u);
#else
		r = 8u;
#endif
		break;
	case 17: // min(NaN, 1) == 1
#if SOPT_SM4
		r = ((min((0.0 / 0.0), 1.0) == 1.0) ? 1u : 0u)
		  + ((min(((0.0 / 0.0) * one), one) == 1.0) ? 2u : 0u)
		  + ((min((zz.x / zz.y), one) == 1.0) ? 4u : 0u);
#else
		r = ((min((zz.x / zz.y), one) == 1.0) ? 4u : 0u);
#endif
		break;
	case 18: // max(NaN, 1) == 1
#if SOPT_SM4
		r = ((max((0.0 / 0.0), 1.0) == 1.0) ? 1u : 0u)
		  + ((max(((0.0 / 0.0) * one), one) == 1.0) ? 2u : 0u)
		  + ((max((zz.x / zz.y), one) == 1.0) ? 4u : 0u);
#else
		r = ((max((zz.x / zz.y), one) == 1.0) ? 4u : 0u);
#endif
		break;
	case 19: // min(1, NaN) == 1
#if SOPT_SM4
		r = ((min(1.0, (0.0 / 0.0)) == 1.0) ? 1u : 0u)
		  + ((min(one, ((0.0 / 0.0) * one)) == 1.0) ? 2u : 0u)
		  + ((min(one, (zz.x / zz.y)) == 1.0) ? 4u : 0u);
#else
		r = ((min(one, (zz.x / zz.y)) == 1.0) ? 4u : 0u);
#endif
		break;
	case 20: // saturate(NaN) == 0
#if SOPT_SM4
		r = ((saturate((0.0 / 0.0)) == 0.0) ? 1u : 0u)
		  + ((saturate(((0.0 / 0.0) * one)) == 0.0) ? 2u : 0u)
		  + ((saturate((zz.x / zz.y)) == 0.0) ? 4u : 0u);
#else
		r = ((saturate((zz.x / zz.y)) == 0.0) ? 4u : 0u);
#endif
		break;
	case 21: // clamp(NaN, 0, 1) == 0
#if SOPT_SM4
		r = ((clamp((0.0 / 0.0), 0.0, 1.0) == 0.0) ? 1u : 0u)
		  + ((clamp(((0.0 / 0.0) * one), 0.0, one) == 0.0) ? 2u : 0u)
		  + ((clamp((zz.x / zz.y), 0.0, one) == 0.0) ? 4u : 0u);
#else
		r = ((clamp((zz.x / zz.y), 0.0, one) == 0.0) ? 4u : 0u);
#endif
		break;
	case 22: // -0 == +0
#if SOPT_SM4
		r = ((((-0.0) == 0.0)) ? 1u : 0u)
		  + ((((-0.0 * one) == (0.0 * one))) ? 2u : 0u)
		  + ((((-zz.z) == zz.w)) ? 4u : 0u);
#else
		r = ((((-zz.z) == zz.w)) ? 4u : 0u);
#endif
		break;
	case 23: // !(-0 < +0)
#if SOPT_SM4
		r = ((!((-0.0) < 0.0)) ? 1u : 0u)
		  + ((!((-0.0 * one) < (0.0 * one))) ? 2u : 0u)
		  + ((!((-zz.z) < zz.w)) ? 4u : 0u);
#else
		r = ((!((-zz.z) < zz.w)) ? 4u : 0u);
#endif
		break;
	case 24: // 1 / -0 < 0
#if SOPT_SM4
		r = (((1.0 / (-0.0)) < 0.0) ? 1u : 0u)
		  + (((one / (-0.0 * one)) < 0.0) ? 2u : 0u)
		  + (((one / (-zz.z)) < 0.0) ? 4u : 0u);
#else
		r = (((one / (-zz.z)) < 0.0) ? 4u : 0u);
#endif
		break;
	case 25: // 1 / +0 > 0
#if SOPT_SM4
		r = (((1.0 / 0.0) > 0.0) ? 1u : 0u)
		  + (((one / (0.0 * one)) > 0.0) ? 2u : 0u)
		  + (((one / zz.w) > 0.0) ? 4u : 0u);
#else
		r = (((one / zz.w) > 0.0) ? 4u : 0u);
#endif
		break;
	case 26: // rcp(-0) < 0
#if SOPT_SM4
		r = ((rcp((-0.0)) < 0.0) ? 1u : 0u)
		  + ((rcp((-0.0 * one)) < 0.0) ? 2u : 0u)
		  + ((rcp((-zz.z)) < 0.0) ? 4u : 0u);
#else
		r = ((rcp((-zz.z)) < 0.0) ? 4u : 0u);
#endif
		break;
	case 27: // rcp(+0) > 0
#if SOPT_SM4
		r = ((rcp(0.0) > 0.0) ? 1u : 0u)
		  + ((rcp((0.0 * one)) > 0.0) ? 2u : 0u)
		  + ((rcp(zz.w) > 0.0) ? 4u : 0u);
#else
		r = ((rcp(zz.w) > 0.0) ? 4u : 0u);
#endif
		break;
	case 28: // 1 / (-0 + +0) > 0
#if SOPT_SM4
		r = (((1.0 / ((-0.0) + 0.0)) > 0.0) ? 1u : 0u)
		  + (((one / ((-0.0 * one) + (0.0 * one))) > 0.0) ? 2u : 0u)
		  + (((one / ((-zz.z) + zz.w)) > 0.0) ? 4u : 0u);
#else
		r = (((one / ((-zz.z) + zz.w)) > 0.0) ? 4u : 0u);
#endif
		break;
	case 29: // 1 / abs(-0) > 0
#if SOPT_SM4
		r = (((1.0 / abs((-0.0))) > 0.0) ? 1u : 0u)
		  + (((one / abs((-0.0 * one))) > 0.0) ? 2u : 0u)
		  + (((one / abs((-zz.z))) > 0.0) ? 4u : 0u);
#else
		r = (((one / abs((-zz.z))) > 0.0) ? 4u : 0u);
#endif
		break;
	case 30: // -0 has the sign bit
#if SOPT_SM4
		r = ((asuint((-0.0)) == 0x80000000u) ? 1u : 0u)
		  + ((asuint((-0.0 * one)) == 0x80000000u) ? 2u : 0u)
		  + ((asuint((-zz.z)) == 0x80000000u) ? 4u : 0u);
#else
		r = 8u;
#endif
		break;
	case 31: // sign(-0) == 0
#if SOPT_SM4
		r = ((sign((-0.0)) == 0.0) ? 1u : 0u)
		  + ((sign((-0.0 * one)) == 0.0) ? 2u : 0u)
		  + ((sign((-zz.z)) == 0.0) ? 4u : 0u);
#else
		r = ((sign((-zz.z)) == 0.0) ? 4u : 0u);
#endif
		break;
	case 32: // 1 / 0 > FLT_MAX
#if SOPT_SM4
		r = (((1.0 / 0.0) > 3.402823466e38) ? 1u : 0u)
		  + ((((1.0 / 0.0) * one) > 3.402823466e38) ? 2u : 0u)
		  + (((one / zz.x) > 3.402823466e38) ? 4u : 0u);
#else
		r = (((one / zz.x) > 3.402823466e38) ? 4u : 0u);
#endif
		break;
	case 33: // -1 / 0 < -FLT_MAX
#if SOPT_SM4
		r = (((-1.0 / 0.0) < -3.402823466e38) ? 1u : 0u)
		  + ((((-1.0 / 0.0) * one) < -3.402823466e38) ? 2u : 0u)
		  + (((-one / zz.z) < -3.402823466e38) ? 4u : 0u);
#else
		r = (((-one / zz.z) < -3.402823466e38) ? 4u : 0u);
#endif
		break;
	case 34: // +inf > -inf
#if SOPT_SM4
		r = ((((1.0 / 0.0) > (-1.0 / 0.0))) ? 1u : 0u)
		  + (((((1.0 / 0.0) * one) > ((-1.0 / 0.0) * one))) ? 2u : 0u)
		  + ((((one / zz.x) > (-one / zz.z))) ? 4u : 0u);
#else
		r = ((((one / zz.x) > (-one / zz.z))) ? 4u : 0u);
#endif
		break;
	case 35: // isinf(+inf) && isinf(-inf)
#if SOPT_SM4
		r = (((isinf((1.0 / 0.0)) && isinf((-1.0 / 0.0)))) ? 1u : 0u)
		  + (((isinf(((1.0 / 0.0) * one)) && isinf(((-1.0 / 0.0) * one)))) ? 2u : 0u)
		  + (((isinf((one / zz.x)) && isinf((-one / zz.z)))) ? 4u : 0u);
#else
		r = (((isinf((one / zz.x)) && isinf((-one / zz.z)))) ? 4u : 0u);
#endif
		break;
	case 36: // inf - inf is NaN
#if SOPT_SM4
		r = ((isnan((1.0 / 0.0) - (1.0 / 0.0))) ? 1u : 0u)
		  + ((isnan(((1.0 / 0.0) * one) - ((1.0 / 0.0) * one))) ? 2u : 0u)
		  + ((isnan((one / zz.x) - (one / zz.w))) ? 4u : 0u);
#else
		r = ((isnan((one / zz.x) - (one / zz.w))) ? 4u : 0u);
#endif
		break;
	case 37: // inf * 0 is NaN
#if SOPT_SM4
		r = ((isnan((1.0 / 0.0) * 0.0)) ? 1u : 0u)
		  + ((isnan(((1.0 / 0.0) * one) * (0.0 * one))) ? 2u : 0u)
		  + ((isnan((one / zz.x) * zz.w)) ? 4u : 0u);
#else
		r = ((isnan((one / zz.x) * zz.w)) ? 4u : 0u);
#endif
		break;
	case 38: // 1 / inf == 0
#if SOPT_SM4
		r = (((1.0 / (1.0 / 0.0)) == 0.0) ? 1u : 0u)
		  + (((one / ((1.0 / 0.0) * one)) == 0.0) ? 2u : 0u)
		  + (((one / (one / zz.x)) == 0.0) ? 4u : 0u);
#else
		r = (((one / (one / zz.x)) == 0.0) ? 4u : 0u);
#endif
		break;
	case 39: // 1 / (1 / -inf) < 0
#if SOPT_SM4
		r = (((1.0 / (1.0 / (-1.0 / 0.0))) < 0.0) ? 1u : 0u)
		  + (((one / (one / ((-1.0 / 0.0) * one))) < 0.0) ? 2u : 0u)
		  + (((one / (one / (-one / zz.z))) < 0.0) ? 4u : 0u);
#else
		r = (((one / (one / (-one / zz.z))) < 0.0) ? 4u : 0u);
#endif
		break;
	case 40: // sqrt(inf) == inf
#if SOPT_SM4
		r = ((sqrt((1.0 / 0.0)) == (1.0 / 0.0)) ? 1u : 0u)
		  + ((sqrt(((1.0 / 0.0) * one)) == ((1.0 / 0.0) * one)) ? 2u : 0u)
		  + ((sqrt((one / zz.x)) == (one / zz.x)) ? 4u : 0u);
#else
		r = ((sqrt((one / zz.x)) == (one / zz.x)) ? 4u : 0u);
#endif
		break;
	case 41: // exp2(-inf) == 0
#if SOPT_SM4
		r = ((exp2((-1.0 / 0.0)) == 0.0) ? 1u : 0u)
		  + ((exp2(((-1.0 / 0.0) * one)) == 0.0) ? 2u : 0u)
		  + ((exp2((-one / zz.z)) == 0.0) ? 4u : 0u);
#else
		r = ((exp2((-one / zz.z)) == 0.0) ? 4u : 0u);
#endif
		break;
	case 42: // exp2(inf) == inf
#if SOPT_SM4
		r = ((isinf(exp2((1.0 / 0.0)))) ? 1u : 0u)
		  + ((isinf(exp2(((1.0 / 0.0) * one)))) ? 2u : 0u)
		  + ((isinf(exp2((one / zz.x)))) ? 4u : 0u);
#else
		r = ((isinf(exp2((one / zz.x)))) ? 4u : 0u);
#endif
		break;
	case 43: // rsqrt(+0) == +inf
#if SOPT_SM4
		r = ((rsqrt(0.0) > 3.402823466e38) ? 1u : 0u)
		  + ((rsqrt((0.0 * one)) > 3.402823466e38) ? 2u : 0u)
		  + ((rsqrt(zz.w) > 3.402823466e38) ? 4u : 0u);
#else
		r = ((rsqrt(zz.w) > 3.402823466e38) ? 4u : 0u);
#endif
		break;
	case 44: // log2(+0) == -inf
#if SOPT_SM4
		r = ((log2(0.0) < -3.402823466e38) ? 1u : 0u)
		  + ((log2((0.0 * one)) < -3.402823466e38) ? 2u : 0u)
		  + ((log2(zz.w) < -3.402823466e38) ? 4u : 0u);
#else
		r = ((log2(zz.w) < -3.402823466e38) ? 4u : 0u);
#endif
		break;
	case 45: // sqrt(-1) is NaN
#if SOPT_SM4
		r = ((isnan(sqrt(-1.0))) ? 1u : 0u)
		  + ((isnan(sqrt(-one))) ? 2u : 0u)
		  + ((isnan(sqrt(-one))) ? 4u : 0u);
#else
		r = ((isnan(sqrt(-one))) ? 4u : 0u);
#endif
		break;
	case 46: // log2(-1) is NaN
#if SOPT_SM4
		r = ((isnan(log2(-1.0))) ? 1u : 0u)
		  + ((isnan(log2(-one))) ? 2u : 0u)
		  + ((isnan(log2(-one))) ? 4u : 0u);
#else
		r = 8u;
#endif
		break;
	case 47: // 1 + 2^-23 != 1 (fp32)
#if SOPT_SM4
		r = (((1.0 + 1.1920929e-7) != 1.0) ? 1u : 0u)
		  + (((one + 1.1920929e-7) != one) ? 2u : 0u)
		  + (((one + 1.1920929e-7) != one) ? 4u : 0u);
#else
		r = (((one + 1.1920929e-7) != one) ? 4u : 0u);
#endif
		break;
	case 48: // 0.062499996 != 0.06249999
#if SOPT_SM4
		r = (((0.0 + 0.062499996) != 0.06249999) ? 1u : 0u)
		  + ((((0.0 * one) + 0.062499996) != 0.06249999) ? 2u : 0u)
		  + (((zz.w + 0.062499996) != 0.06249999) ? 4u : 0u);
#else
		r = (((zz.w + 0.062499996) != 0.06249999) ? 4u : 0u);
#endif
		break;
	case 49: // 2^24 + 1 == 2^24 (even)
#if SOPT_SM4
		r = (((16777216.0 * 1.0 + 1.0) == 16777216.0) ? 1u : 0u)
		  + (((16777216.0 * one + 1.0) == 16777216.0) ? 2u : 0u)
		  + (((16777216.0 * one + 1.0) == 16777216.0) ? 4u : 0u);
#else
		r = (((16777216.0 * one + 1.0) == 16777216.0) ? 4u : 0u);
#endif
		break;
	case 50: // round(0.5) == 0 (even)
#if SOPT_SM4
		r = ((round(0.5 * 1.0) == 0.0) ? 1u : 0u)
		  + ((round(0.5 * one) == 0.0) ? 2u : 0u)
		  + ((round(0.5 * one) == 0.0) ? 4u : 0u);
#else
		r = ((round(0.5 * one) == 0.0) ? 4u : 0u);
#endif
		break;
	case 51: // round(1.5) == 2
#if SOPT_SM4
		r = ((round(1.5 * 1.0) == 2.0) ? 1u : 0u)
		  + ((round(1.5 * one) == 2.0) ? 2u : 0u)
		  + ((round(1.5 * one) == 2.0) ? 4u : 0u);
#else
		r = ((round(1.5 * one) == 2.0) ? 4u : 0u);
#endif
		break;
	case 52: // round(2.5) == 2 (even)
#if SOPT_SM4
		r = ((round(2.5 * 1.0) == 2.0) ? 1u : 0u)
		  + ((round(2.5 * one) == 2.0) ? 2u : 0u)
		  + ((round(2.5 * one) == 2.0) ? 4u : 0u);
#else
		r = ((round(2.5 * one) == 2.0) ? 4u : 0u);
#endif
		break;
	case 53: // frac(-0.25) == 0.75
#if SOPT_SM4
		r = ((frac(-0.25 * 1.0) == 0.75) ? 1u : 0u)
		  + ((frac(-0.25 * one) == 0.75) ? 2u : 0u)
		  + ((frac(-0.25 * one) == 0.75) ? 4u : 0u);
#else
		r = ((frac(-0.25 * one) == 0.75) ? 4u : 0u);
#endif
		break;
	case 54: // -1.5 % 1 == -0.5
#if SOPT_SM4
		r = ((((-1.5 * 1.0) % 1.0) == -0.5) ? 1u : 0u)
		  + ((((-1.5 * one) % one) == -0.5) ? 2u : 0u)
		  + ((((-1.5 * one) % one) == -0.5) ? 4u : 0u);
#else
		r = ((((-1.5 * one) % one) == -0.5) ? 4u : 0u);
#endif
		break;
	case 55: // trunc(-1.5) == -1
#if SOPT_SM4
		r = ((trunc(-1.5 * 1.0) == -1.0) ? 1u : 0u)
		  + ((trunc(-1.5 * one) == -1.0) ? 2u : 0u)
		  + ((trunc(-1.5 * one) == -1.0) ? 4u : 0u);
#else
		r = ((trunc(-1.5 * one) == -1.0) ? 4u : 0u);
#endif
		break;
	case 56: // int(-1.5) == -1
#if SOPT_SM4
		r = (((int)(-1.5 * 1.0) == -1) ? 1u : 0u)
		  + (((int)(-1.5 * one) == -1) ? 2u : 0u)
		  + (((int)(-1.5 * one) == -1) ? 4u : 0u);
#else
		r = 8u;
#endif
		break;
	case 57: // uint(-1.5) == 0
#if SOPT_SM4
		r = (((uint)(-1.5 * 1.0) == 0u) ? 1u : 0u)
		  + (((uint)(-1.5 * one) == 0u) ? 2u : 0u)
		  + (((uint)(-1.5 * one) == 0u) ? 4u : 0u);
#else
		r = 8u;
#endif
		break;
	case 58: // int(3e9) == 2147483647
#if SOPT_SM4
		r = (((int)(3e9 * 1.0) == 2147483647) ? 1u : 0u)
		  + (((int)(3e9 * one) == 2147483647) ? 2u : 0u)
		  + (((int)(3e9 * one) == 2147483647) ? 4u : 0u);
#else
		r = 8u;
#endif
		break;
	case 59: // FLT_MIN / 2 kept
#if SOPT_SM4
		r = (((1.17549435e-38 * 1.0 * 0.5) > 0.0) ? 1u : 0u)
		  + (((1.17549435e-38 * one * 0.5) > 0.0) ? 2u : 0u)
		  + (((1.17549435e-38 * one * 0.5) > 0.0) ? 4u : 0u);
#else
		r = (((1.17549435e-38 * one * 0.5) > 0.0) ? 4u : 0u);
#endif
		break;
	case 60: // 1e-40 kept
#if SOPT_SM4
		r = (((1e-40 * 1.0) > 0.0) ? 1u : 0u)
		  + (((1e-40 * one) > 0.0) ? 2u : 0u)
		  + (((1e-40 * one) > 0.0) ? 4u : 0u);
#else
		r = (((1e-40 * one) > 0.0) ? 4u : 0u);
#endif
		break;
	}
	return r;
}

#if SOPT_SM4

static const uint kFont[380] = {
	0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x01020400u, 0x00020408u, 0x00000408u, 0x00000000u,
	0x02850A00u, 0x00000000u, 0x00000000u, 0x00000000u, 0x050A0000u, 0x0FE51A7Eu, 0x00000512u, 0x00000000u,
	0x05C70400u, 0x0D0E060Au, 0x01021E2Au, 0x00000000u, 0x01224300u, 0x090C8C66u, 0x00001848u, 0x00000000u,
	0x00C18E00u, 0x0E76C704u, 0x00003F22u, 0x00000000u, 0x01020400u, 0x00000000u, 0x00000000u, 0x00000000u,
	0x01020C10u, 0x0103060Cu, 0x00040C08u, 0x00000000u, 0x03020404u, 0x03060C18u, 0x00010408u, 0x00000000u,
	0x038A8400u, 0x0002151Cu, 0x00000000u, 0x00000000u, 0x01000000u, 0x011FC408u, 0x00000408u, 0x00000000u,
	0x00000000u, 0x00000000u, 0x00030418u, 0x00000000u, 0x00000000u, 0x00070000u, 0x00000000u, 0x00000000u,
	0x00000000u, 0x00000000u, 0x00000408u, 0x00000000u, 0x020C1000u, 0x00820418u, 0x00008304u, 0x00000000u,
	0x044D8E00u, 0x0458B562u, 0x00000E36u, 0x00000000u, 0x03060F00u, 0x03060C18u, 0x00003F18u, 0x00000000u,
	0x040C8E00u, 0x01860820u, 0x00001F06u, 0x00000000u, 0x040C8E00u, 0x04080E30u, 0x00000F22u, 0x00000000u,
	0x078E1800u, 0x0FEC9B34u, 0x00001830u, 0x00000000u, 0x00409F00u, 0x0408181Eu, 0x00000F32u, 0x00000000u,
	0x00498E00u, 0x0448931Eu, 0x00000E26u, 0x00000000u, 0x06081F00u, 0x01060810u, 0x0000020Cu, 0x00000000u,
	0x04498E00u, 0x0C488E26u, 0x00001E26u, 0x00000000u, 0x044D8E00u, 0x040F1B22u, 0x00000E32u, 0x00000000u,
	0x00000000u, 0x00000408u, 0x00000408u, 0x00000000u, 0x00000000u, 0x00000408u, 0x00030418u, 0x00000000u,
	0x0C000000u, 0x07018338u, 0x00000060u, 0x00000000u, 0x00000000u, 0x0FE03F80u, 0x00000000u, 0x00000000u,
	0x00600000u, 0x01DC380Eu, 0x00000003u, 0x00000000u, 0x040C8E00u, 0x00020410u, 0x00000408u, 0x00000000u,
	0x0CCF0000u, 0x09B37CC2u, 0x07818179u, 0x00000000u, 0x02870C00u, 0x07C99B14u, 0x000021E2u, 0x00000000u,
	0x04488F00u, 0x0C489F22u, 0x00001F62u, 0x00000000u, 0x00499E00u, 0x00408102u, 0x00001E26u, 0x00000000u,
	0x044C8F00u, 0x0458B162u, 0x00000F32u, 0x00000000u, 0x00409F00u, 0x00409F02u, 0x00003F02u, 0x00000000u,
	0x00C1BF00u, 0x00C19F06u, 0x00000306u, 0x00000000u, 0x00499E00u, 0x0C58B902u, 0x00001E66u, 0x00000000u,
	0x0C58B100u, 0x0C58BF62u, 0x00003162u, 0x00000000u, 0x01021F00u, 0x01020408u, 0x00001F08u, 0x00000000u,
	0x060C1E00u, 0x060C1830u, 0x00000F12u, 0x00000000u, 0x034CB100u, 0x0646870Eu, 0x00003122u, 0x00000000u,
	0x00C18300u, 0x00C18306u, 0x00003F06u, 0x00000000u, 0x0EF9F180u, 0x0872EDD7u, 0x000021C3u, 0x00000000u,
	0x0CD9B300u, 0x0E5EB56Au, 0x00003172u, 0x00000000u, 0x044D8E00u, 0x0458B162u, 0x00000E36u, 0x00000000u,
	0x0C589F00u, 0x00409F62u, 0x00000102u, 0x00000000u, 0x044D8E00u, 0x0458B162u, 0x040C0E36u, 0x00000000u,
	0x044C8F00u, 0x044C8F32u, 0x00002162u, 0x00000000u, 0x00498E00u, 0x0C080E06u, 0x00001E22u, 0x00000000u,
	0x01023F80u, 0x01020408u, 0x00000408u, 0x00000000u, 0x04489100u, 0x04489122u, 0x00000E26u, 0x00000000u,
	0x0458B180u, 0x02851A26u, 0x00000C1Cu, 0x00000000u, 0x09706080u, 0x06DDBF5Bu, 0x00001336u, 0x00000000u,
	0x0289B100u, 0x06870C1Cu, 0x000031A2u, 0x00000000u, 0x0688B180u, 0x01020C1Cu, 0x00000408u, 0x00000000u,
	0x06083F00u, 0x00830C10u, 0x00003F06u, 0x00000000u, 0x01020418u, 0x01020408u, 0x00060408u, 0x00000000u,
	0x00818100u, 0x03020404u, 0x00081810u, 0x00000000u, 0x03060C1Cu, 0x03060C18u, 0x00070C18u, 0x00000000u,
	0x044D0C00u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x00000000u, 0x0000007Fu,
	0x00000404u, 0x00000000u, 0x00000000u, 0x00000000u, 0x03C00000u, 0x044F1020u, 0x00001F32u, 0x00000000u,
	0x03C08102u, 0x0C58B126u, 0x00000F26u, 0x00000000u, 0x07800000u, 0x00C08304u, 0x00001E04u, 0x00000000u,
	0x07881020u, 0x04489136u, 0x00001E36u, 0x00000000u, 0x03800000u, 0x005FB126u, 0x00001E26u, 0x00000000u,
	0x07C20438u, 0x01020408u, 0x00000408u, 0x00000000u, 0x07800000u, 0x04489136u, 0x06481E36u, 0x0000001Cu,
	0x07C08102u, 0x04489126u, 0x00001122u, 0x00000000u, 0x01C00008u, 0x01020408u, 0x00003F08u, 0x00000000u,
	0x03800018u, 0x03060C18u, 0x03060C18u, 0x0000000Eu, 0x04C18306u, 0x02C78716u, 0x00003326u, 0x00000000u,
	0x0102040Eu, 0x01020408u, 0x00001C08u, 0x00000000u, 0x07C00000u, 0x0952A56Au, 0x0000254Au, 0x00000000u,
	0x07C00000u, 0x04489126u, 0x00001122u, 0x00000000u, 0x03800000u, 0x04489126u, 0x00000E26u, 0x00000000u,
	0x03C00000u, 0x04589126u, 0x00408F26u, 0x00000002u, 0x07800000u, 0x04489136u, 0x04081E36u, 0x00000020u,
	0x0F800000u, 0x0081020Cu, 0x00000204u, 0x00000000u, 0x03800000u, 0x04070326u, 0x00000E22u, 0x00000000u,
	0x07C30600u, 0x0183060Cu, 0x00001C08u, 0x00000000u, 0x04400000u, 0x04489122u, 0x00001E36u, 0x00000000u,
	0x0C400000u, 0x028D1322u, 0x00000C1Cu, 0x00000000u, 0x08200000u, 0x06DEA5C1u, 0x00001B36u, 0x00000000u,
	0x04400000u, 0x03860E34u, 0x00003136u, 0x00000000u, 0x0C400000u, 0x028D1322u, 0x01820C1Cu, 0x00000006u,
	0x07C00000u, 0x01820830u, 0x00001F06u, 0x00000000u, 0x01020C30u, 0x01020708u, 0x000C0C08u, 0x00000000u,
	0x01020408u, 0x01020408u, 0x01020408u, 0x00000000u, 0x0102040Eu, 0x01061818u, 0x00038408u, 0x00000000u,
	0x00000000u, 0x000E2700u, 0x00000000u, 0x00000000u,
};
static const uint kText[363] = {
	0x204E614Eu, 0x706D6F63u, 0x73697261u, 0x20736E6Fu, 0x45454928u, 0x35372045u, 0x73692934u, 0x286E616Eu,
	0x294E614Eu, 0x616E7369u, 0x614E286Eu, 0x202C294Eu, 0x204E614Eu, 0x63657270u, 0x4E657369u, 0x62204E61u,
	0x74207469u, 0x78747365u, 0x203D2120u, 0x78282078u, 0x4E203D20u, 0x4E294E61u, 0x21204E61u, 0x6E61203Du,
	0x6568746Fu, 0x614E2072u, 0x4E614E4Eu, 0x203D2120u, 0x78282131u, 0x203D3D20u, 0x28202978u, 0x203D2078u,
	0x294E614Eu, 0x614E2821u, 0x203C204Eu, 0x28212931u, 0x204E614Eu, 0x2931203Eu, 0x614E2821u, 0x3D3C204Eu,
	0x21293120u, 0x4E614E28u, 0x203D3E20u, 0x69212931u, 0x666E6973u, 0x4E614E28u, 0x4E614E29u, 0x31202B20u,
	0x20736920u, 0x4E4E614Eu, 0x2A204E61u, 0x69203020u, 0x614E2073u, 0x4E614E4Eu, 0x206F7420u, 0x6C6F6F62u,
	0x69202F20u, 0x6228746Eu, 0x296C6F6Fu, 0x204E614Eu, 0x74207369u, 0x4E657572u, 0x3F204E61u, 0x3A203120u,
	0x69203020u, 0x69312073u, 0x4E28746Eu, 0x20294E61u, 0x30203D3Du, 0x204E614Eu, 0x6D206E69u, 0x2F206E69u,
	0x78616D20u, 0x73202F20u, 0x72757461u, 0x6D657461u, 0x4E286E69u, 0x202C4E61u, 0x3D202931u, 0x6D31203Du,
	0x4E287861u, 0x202C4E61u, 0x3D202931u, 0x6D31203Du, 0x31286E69u, 0x614E202Cu, 0x3D20294Eu, 0x7331203Du,
	0x72757461u, 0x28657461u, 0x294E614Eu, 0x203D3D20u, 0x616C6330u, 0x4E28706Du, 0x202C4E61u, 0x31202C30u,
	0x3D3D2029u, 0x69533020u, 0x64656E67u, 0x72657A20u, 0x20302D6Fu, 0x2B203D3Du, 0x2D282130u, 0x203C2030u,
	0x3129302Bu, 0x2D202F20u, 0x203C2030u, 0x2F203130u, 0x20302B20u, 0x7230203Eu, 0x2D287063u, 0x3C202930u,
	0x63723020u, 0x302B2870u, 0x203E2029u, 0x2F203130u, 0x302D2820u, 0x2B202B20u, 0x3E202930u, 0x20313020u,
	0x6261202Fu, 0x302D2873u, 0x203E2029u, 0x20302D30u, 0x20736168u, 0x20656874u, 0x6E676973u, 0x74696220u,
	0x6E676973u, 0x29302D28u, 0x203D3D20u, 0x666E4930u, 0x74696E69u, 0x2F203179u, 0x3E203020u, 0x544C4620u,
	0x58414D5Fu, 0x2F20312Du, 0x3C203020u, 0x4C462D20u, 0x414D5F54u, 0x6E692B58u, 0x203E2066u, 0x666E692Du,
	0x6E697369u, 0x692B2866u, 0x2029666Eu, 0x69202626u, 0x666E6973u, 0x6E692D28u, 0x6E692966u, 0x202D2066u,
	0x20666E69u, 0x4E207369u, 0x6E694E61u, 0x202A2066u, 0x73692030u, 0x4E614E20u, 0x202F2031u, 0x20666E69u,
	0x30203D3Du, 0x202F2031u, 0x2F203128u, 0x6E692D20u, 0x3C202966u, 0x71733020u, 0x69287472u, 0x2029666Eu,
	0x69203D3Du, 0x7865666Eu, 0x2D283270u, 0x29666E69u, 0x203D3D20u, 0x70786530u, 0x6E692832u, 0x3D202966u,
	0x6E69203Du, 0x74614D66u, 0x74612068u, 0x65687420u, 0x67646520u, 0x73727365u, 0x28747271u, 0x2029302Bu,
	0x2B203D3Du, 0x6C666E69u, 0x2832676Fu, 0x2029302Bu, 0x2D203D3Du, 0x73666E69u, 0x28747271u, 0x2029312Du,
	0x4E207369u, 0x6F6C4E61u, 0x2D283267u, 0x69202931u, 0x614E2073u, 0x756F524Eu, 0x6E69646Eu, 0x6E612067u,
	0x6F632064u, 0x7265766Eu, 0x6E6F6973u, 0x202B2031u, 0x322D5E32u, 0x3D212033u, 0x28203120u, 0x32337066u,
	0x302E3029u, 0x39343236u, 0x36393939u, 0x203D2120u, 0x36302E30u, 0x39393432u, 0x5E323939u, 0x2B203432u,
	0x3D203120u, 0x5E32203Du, 0x28203432u, 0x6E657665u, 0x756F7229u, 0x3028646Eu, 0x2029352Eu, 0x30203D3Du,
	0x76652820u, 0x72296E65u, 0x646E756Fu, 0x352E3128u, 0x3D3D2029u, 0x6F723220u, 0x28646E75u, 0x29352E32u,
	0x203D3D20u, 0x65282032u, 0x296E6576u, 0x63617266u, 0x2E302D28u, 0x20293532u, 0x30203D3Du, 0x2D35372Eu,
	0x20352E31u, 0x20312025u, 0x2D203D3Du, 0x74352E30u, 0x636E7572u, 0x2E312D28u, 0x3D202935u, 0x312D203Du,
	0x28746E69u, 0x352E312Du, 0x3D3D2029u, 0x75312D20u, 0x28746E69u, 0x352E312Du, 0x3D3D2029u, 0x6E693020u,
	0x65332874u, 0x3D202939u, 0x3132203Du, 0x38343734u, 0x37343633u, 0x6F6E6544u, 0x6C616D72u, 0x65282073u,
	0x65687469u, 0x73692072u, 0x6C6C6120u, 0x6465776Fu, 0x544C4629u, 0x4E494D5Fu, 0x32202F20u, 0x70656B20u,
	0x2D653174u, 0x6B203034u, 0x52747065u, 0x61685365u, 0x49206564u, 0x20454545u, 0x20343537u, 0x74736574u,
	0x6C6F4620u, 0x20646564u, 0x6574694Cu, 0x206C6172u, 0x206E7552u, 0x656D6974u, 0x3D206B6Fu, 0x67697220u,
	0x20207468u, 0x41462020u, 0x3D204C49u, 0x6F727720u, 0x2820676Eu, 0x45454549u, 0x34353720u, 0x48202F20u,
	0x294C534Cu, 0x20202020u, 0x20443344u, 0x6964203Du, 0x72656666u, 0x72662073u, 0x44206D6Fu, 0x63657269u,
	0x27443374u, 0x75722073u, 0x6F46656Cu, 0x6465646Cu, 0x696C203Au, 0x61726574u, 0x6F20736Cu, 0x20796C6Eu,
	0x694C2020u, 0x61726574u, 0x4E203A6Cu, 0x2F204E61u, 0x666E6920u, 0x2D202F20u, 0x72772030u, 0x65747469u,
	0x7361206Eu, 0x6C206120u, 0x72657469u, 0x20206C61u, 0x6E755220u, 0x6D697420u, 0x6D203A65u, 0x20656461u,
	0x74206E6Fu, 0x47206568u, 0x72775550u, 0x20676E6Fu, 0x45454928u, 0x35372045u, 0x202F2034u, 0x4C534C48u,
	0x746F6E29u, 0x20736120u, 0x65726944u, 0x44337463u, 0x65726944u, 0x44337463u, 0x69443920u, 0x74636572u,
	0x31204433u, 0x72694430u, 0x33746365u, 0x31312044u, 0x65726944u, 0x44337463u, 0x4F323120u, 0x476E6570u,
	0x6C75564Cu, 0x416E616Bu, 0x3F204950u, 0x68536552u, 0x20656461u, 0x206B6F20u, 0x4C494146u, 0x33442020u,
	0x65792044u, 0x6E202073u, 0x2D20206Fu,
};
static const uint kLines[72] = {
	0x001A0001u, 0x000A006Au, 0x01170092u, 0x020C00EEu, 0x0310011Eu, 0x0412015Eu, 0x050801A6u, 0x061301C6u,
	0x070A0212u, 0x080A023Au, 0x090B0262u, 0x0A0B028Eu, 0x0B0B02BAu, 0x0C0E02E6u, 0x0D0E031Eu, 0x00110355u,
	0x0E11039Au, 0x0F1003DEu, 0x100D041Eu, 0x001B0451u, 0x111004BEu, 0x121004FEu, 0x1310053Eu, 0x1412057Eu,
	0x151505C6u, 0x000B0619u, 0x16080646u, 0x170A0666u, 0x180A068Eu, 0x190A06B6u, 0x1A0B06DEu, 0x1B0B070Au,
	0x1C110736u, 0x1D0F077Au, 0x1E1307B6u, 0x1F0D0802u, 0x00080835u, 0x200F0856u, 0x21110892u, 0x220B08D6u,
	0x231A0902u, 0x2410096Au, 0x250E09AAu, 0x260C09E2u, 0x27120A12u, 0x28100A5Au, 0x290F0A9Au, 0x2A100AD6u,
	0x00110B15u, 0x2B110B5Au, 0x2C100B9Eu, 0x2D0F0BDEu, 0x2E0F0C1Au, 0x00170C55u, 0x2F150CB2u, 0x30190D06u,
	0x31170D6Au, 0x32160DC6u, 0x330F0E1Eu, 0x34160E5Au, 0x35130EB2u, 0x36100EFEu, 0x37110F3Eu, 0x380F0F82u,
	0x390F0FBEu, 0x3A160FFAu, 0x001D1051u, 0x3B1010C6u, 0x3C0A1106u, 0x00000000u, 0x00000000u, 0x00000000u,
};
static const uint kKinds[4] = {
	0x00000000u, 0x00000555u, 0x00000000u, 0x02940110u,
};

int kindOf(int id) { return int((kKinds[id / 16] >> uint((id % 16) * 2)) & 3u); }

// 1 where the glyph of character code c covers cell pixel p (0..kGlyphW-1, 0..kGlyphH-1).
float glyph(uint c, int2 p)
{
	if (c < 32u || c > 126u || p.x < 0 || p.y < 0 || p.x >= kGlyphW || p.y >= kGlyphH) return 0.0;
	uint w = kFont[(c - 32u) * 4u + uint(p.y / 4)];
	return float((w >> uint((p.y % 4) * kGlyphW + p.x)) & 1u);
}

uint textChar(int2 t, int i) { return i < 0 || i >= t.y ? 32u : (kText[(t.x + i) / 4] >> uint(((t.x + i) % 4) * 8)) & 0xFFu; }

// Text t drawn from character cell 'start' on; cell = character cell of this pixel, p = pixel inside it.
float drawText(int2 t, int start, int cell, int2 p) { return glyph(textChar(t, cell - start), p); }

// Digit d (0..9) of number n drawn right-aligned so that its last digit is at cell 'last'.
float drawNumber(uint n, int last, int cell, int2 p)
{
	int k = last - cell;
	if (k < 0 || k > 9) return 0.0;
	uint m = n;
	for (int i = 0; i < k; ++i) m /= 10u;
	if (m == 0u && k > 0) return 0.0;
	return glyph(48u + m % 10u, p);
}

float3 IEEE754PS(float4 vpos : SV_Position) : SV_Target
{
	float4 zz = floor(sopt_timer * float4(1e-12, 1.1e-12, 1.2e-12, 1.3e-12)); // run-time +0s nothing can fold
	float one = zz.x + 1.0;
	int s = max(1, min(BUFFER_HEIGHT / 540, BUFFER_WIDTH / 800)); // pixel scale
	int cw = kGlyphW * s;
	int lh = kGlyphH * s;
	int2 px = int2(vpos.xy) - int2(2 * cw, lh / 2);
	int cell = px.x >= 0 ? px.x / cw : -1;
	int line = px.y >= 0 ? px.y / lh : -1;
	int2 p = int2(px.x - cell * cw, px.y - line * lh) / s;
	int side = cell >= 52 ? 1 : 0;
	int c0 = cell - side * 52;

	float3 col = float3(0.08, 0.09, 0.11);
	float3 ink = float3(0.92, 0.93, 0.95);

	if (line == 0)
	{
		// Title, API and ReShade version.
		float t = drawText(kT_title, 0, cell, p);
		int2 api = kT_api_other;
		if (__RENDERER__ >= 0x20000) api = kT_api_vk;
		else if (__RENDERER__ >= 0x10000) api = kT_api_gl;
		else if (__RENDERER__ >= 0xc000) api = kT_api_d3d12;
		else if (__RENDERER__ >= 0xb000) api = kT_api_d3d11;
		else if (__RENDERER__ >= 0xa000) api = kT_api_d3d10;
		t += drawText(api, 25, cell, p);
		t += drawText(kT_reshade, 40, cell, p);
		t += drawNumber(uint(__RESHADE__ / 10000), 48, cell, p);
		t += cell == 49 ? glyph(46u, p) : 0.0;
		t += drawNumber(uint((__RESHADE__ / 100) % 100), 50, cell, p);
		t += cell == 51 ? glyph(46u, p) : 0.0;
		t += drawNumber(uint(__RESHADE__ % 100), 52, cell, p);
		return lerp(col, float3(1.0, 0.85, 0.3), saturate(t));
	}
	if (line == 1)
		return lerp(col, ink * 0.75, saturate(drawText(kT_legend1, 0, cell, p)));
	if (line == 2)
	{
		// Totals per column: left half wrong (IEEE 754 / HLSL), right half not as Direct3D.
		if (cell < 0 || (c0 % 8 == 7 && c0 < 24)) return col;
		uint3 wrong = uint3(0u, 0u, 0u);
		uint3 notd3d = uint3(0u, 0u, 0u);
		[loop] for (int i = 0; i < kTests; ++i)
		{
			uint r = runTest(i, zz, one);
			if (r == 8u) continue;
			uint3 fails = uint3((r & 1u) ^ 1u, ((r >> 1) & 1u) ^ 1u, ((r >> 2) & 1u) ^ 1u);
			int k = kindOf(i);
			if (k == 0) wrong += fails;
			else if (k == 1) notd3d += fails;
		}
		uint3 n = side == 0 ? wrong : notd3d;
		float t = drawNumber(n.x, 4, c0, p) + drawNumber(n.y, 12, c0, p) + drawNumber(n.z, 20, c0, p);
		t += drawText(side == 0 ? kT_wrong : kT_d3d, 25, c0, p);
		bool bad = side == 0 ? any(n != 0u) : false;
		return lerp(col, bad ? float3(1.0, 0.45, 0.4) : float3(0.5, 0.95, 0.55), saturate(t));
	}
	if (line == 3)
		return lerp(col, ink * 0.6, saturate(drawText(kT_cols, 0, c0, p)));

	int row = line - 4;
	if (row < 0 || row >= kRows || cell < 0) return col;
	uint d = kLines[side * kRows + row];
	int type = int(d & 3u);
	int2 t = int2(int((d >> 2) & 0x3FFFu), int((d >> 16) & 0xFFu));
	if (type == 0) return col;
	if (type == 1)
		return lerp(col, float3(0.45, 0.8, 1.0), saturate(drawText(t, 0, c0, p)));

	int id = int(d >> 24);
	if (c0 >= 25)
		return lerp(col, ink, saturate(drawText(t, 25, c0, p)));
	// Result boxes: 7 cells + 1 gap each.
	int box = c0 / 8;
	if (c0 % 8 == 7 || box > 2) return col;
	int py = px.y - line * lh;
	if (py < s / 2 || py >= lh - s / 2) return col;
	uint r = runTest(id, zz, one);
	int k = kindOf(id);
	bool good = (r & (1u << uint(box))) != 0u;
	float3 bg;
	int2 word;
	if (r == 8u) { bg = float3(0.25, 0.25, 0.27); word = kT_na; }
	else if (k == 2) { bg = float3(0.2, 0.35, 0.6); word = good ? kT_yes : kT_no; }
	else if (good) { bg = float3(0.12, 0.45, 0.18); word = kT_ok; }
	else if (k == 1) { bg = float3(0.75, 0.42, 0.05); word = kT_d3dw; }
	else { bg = float3(0.75, 0.12, 0.1); word = kT_fail; }
	return lerp(bg, float3(1.0, 1.0, 1.0), saturate(drawText(word, box * 8, c0, p)));
}

#else

// Direct3D 9 (shader model 3) has no integer bit operations for the font and allows no NaN / inf literals: the run-time
// results only, one box per test, top to bottom in the order listed at the top of this file (green true, red false; grey
// = needs shader model 4).
float3 IEEE754PS(float4 vpos : SV_Position) : SV_Target
{
	float4 zz = floor(sopt_timer * float4(1e-12, 1.1e-12, 1.2e-12, 1.3e-12));
	float one = zz.x + 1.0;
	float2 c = floor(vpos.xy / float2(48.0, 14.0));
	int id = int(c.y) - 1;
	if (id < 0 || id >= kTests || c.x != 1.0) return float3(0.08, 0.09, 0.11);
	float r = float(runTest(id, zz, one));
	if (r > 7.5) return float3(0.25, 0.25, 0.27);
	return r > 3.5 ? float3(0.12, 0.6, 0.18) : float3(0.8, 0.12, 0.1);
}

#endif

void IEEE754VS(in uint id : SV_VertexID, out float4 position : SV_Position)
{
	const float2 uv = float2(id == 2 ? 2.0 : 0.0, id == 1 ? 2.0 : 0.0);
	position = float4(uv * float2(2.0, -2.0) + float2(-1.0, 1.0), 0.0, 1.0);
}

technique sopt_IEEE754 < ui_tooltip = "IEEE 754 / HLSL float rules as ReShade compiles them for this API.\n"
	"Folded = literals only, Literal = NaN / inf / -0 written as literals, Run time = made on the GPU."; >
{
	pass
	{
		VertexShader = IEEE754VS;
		PixelShader = IEEE754PS;
	}
}

